// @generated by scripts/gen-management.mjs from management-registry.json and
// openapi.json. DO NOT EDIT — your changes will be overwritten. Regenerate with
// `node scripts/gen-management.mjs`; CI verifies the committed output is current.

/**
 * Generated §27 surface conformance: every operation is reached once.
 *
 * Per operation: the SDK issues the registry's method against the registry's
 * path, and parses the response shape `openapi.json` declares. Semantics that
 * are not per-operation — sparse-update key sets, secret redaction, error
 * mapping, pagination walks, the manifest — are tested by hand in the other
 * `test/management.*.test.ts` files.
 */

import { describe, expect, it } from 'vitest';

import { EXAMPLE_ID, ORG_ID, TENANT_ID, expectedSurface, mountJson, withServer } from './managementSupport.js';
import { Sensitive } from '../src/core/sensitive.js';

describe('organizations namespace', () => {
  it('organizations.list', async () => {
    await withServer(async (server, client) => {
      mountJson(server, 'GET', `/api/v1/organizations`, 200, {"items":[{"created_at":"2026-08-26T00:00:00Z","id":"11111111-1111-4111-8111-111111111111","metadata":{},"name":"example","slug":"example","updated_at":"2026-08-26T00:00:00Z"}],"total":1,"offset":0,"limit":50});
      await client.organizations.list({ limit: 50 });
      await client.organizations.listAll({ limit: 50 });
    });
  });
  it('organizations.get', async () => {
    await withServer(async (server, client) => {
      mountJson(server, 'GET', `/api/v1/organizations/${ORG_ID}`, 200, {"created_at":"2026-08-26T00:00:00Z","id":"11111111-1111-4111-8111-111111111111","metadata":{},"name":"example","slug":"example","updated_at":"2026-08-26T00:00:00Z"});
      await client.organizations.get();
    });
  });
  it('organizations.update', async () => {
    await withServer(async (server, client) => {
      mountJson(server, 'PUT', `/api/v1/organizations/${ORG_ID}`, 200, {"created_at":"2026-08-26T00:00:00Z","id":"11111111-1111-4111-8111-111111111111","metadata":{},"name":"example","slug":"example","updated_at":"2026-08-26T00:00:00Z"});
      await client.organizations.update({  });
    });
  });
});

describe('tenants namespace', () => {
  it('tenants.list', async () => {
    await withServer(async (server, client) => {
      mountJson(server, 'GET', `/api/v1/organizations/${ORG_ID}/tenants`, 200, {"items":[{"created_at":"2026-08-26T00:00:00Z","id":"11111111-1111-4111-8111-111111111111","metadata":{},"name":"example","organization_id":"11111111-1111-4111-8111-111111111111","slug":"example","status":"Active","updated_at":"2026-08-26T00:00:00Z"}],"total":1,"offset":0,"limit":50});
      await client.tenants.list({ limit: 50 });
      await client.tenants.listAll({ limit: 50 });
    });
  });
  it('tenants.create', async () => {
    await withServer(async (server, client) => {
      mountJson(server, 'POST', `/api/v1/organizations/${ORG_ID}/tenants`, 201, {"created_at":"2026-08-26T00:00:00Z","id":"11111111-1111-4111-8111-111111111111","metadata":{},"name":"example","organization_id":"11111111-1111-4111-8111-111111111111","slug":"example","status":"Active","updated_at":"2026-08-26T00:00:00Z"});
      await client.tenants.create({ name: 'example', slug: 'example' });
    });
  });
  it('tenants.get', async () => {
    await withServer(async (server, client) => {
      mountJson(server, 'GET', `/api/v1/organizations/${ORG_ID}/tenants/${EXAMPLE_ID}`, 200, {"created_at":"2026-08-26T00:00:00Z","id":"11111111-1111-4111-8111-111111111111","metadata":{},"name":"example","organization_id":"11111111-1111-4111-8111-111111111111","slug":"example","status":"Active","updated_at":"2026-08-26T00:00:00Z"});
      await client.tenants.get(EXAMPLE_ID);
    });
  });
  it('tenants.update', async () => {
    await withServer(async (server, client) => {
      mountJson(server, 'PUT', `/api/v1/organizations/${ORG_ID}/tenants/${EXAMPLE_ID}`, 200, {"created_at":"2026-08-26T00:00:00Z","id":"11111111-1111-4111-8111-111111111111","metadata":{},"name":"example","organization_id":"11111111-1111-4111-8111-111111111111","slug":"example","status":"Active","updated_at":"2026-08-26T00:00:00Z"});
      await client.tenants.update(EXAMPLE_ID, {  });
    });
  });
  it('tenants.delete', async () => {
    await withServer(async (server, client) => {
      mountJson(server, 'DELETE', `/api/v1/organizations/${ORG_ID}/tenants/${EXAMPLE_ID}`, 204, undefined);
      await client.tenants.delete(EXAMPLE_ID);
    });
  });
  it('tenants.export_audit', async () => {
    await withServer(async (server, client) => {
      mountJson(server, 'POST', `/api/v1/organizations/${ORG_ID}/tenants/${EXAMPLE_ID}/audit-export`, 200, undefined);
      await client.tenants.exportAudit(EXAMPLE_ID);
    });
  });
});

describe('users namespace', () => {
  it('users.list', async () => {
    await withServer(async (server, client) => {
      mountJson(server, 'GET', `/api/v1/users`, 200, {"items":[{"created_at":"2026-08-26T00:00:00Z","email":"example","email_verified":true,"failed_login_attempts":1,"id":"11111111-1111-4111-8111-111111111111","is_locked":true,"metadata":{},"mfa_enabled":true,"status":"Active","tenant_id":"11111111-1111-4111-8111-111111111111","updated_at":"2026-08-26T00:00:00Z","username":"example"}],"total":1,"offset":0,"limit":50});
      await client.users.list({ limit: 50 });
      await client.users.listAll({ limit: 50 });
    });
  });
  it('users.create', async () => {
    await withServer(async (server, client) => {
      mountJson(server, 'POST', `/api/v1/users`, 201, {"created_at":"2026-08-26T00:00:00Z","email":"example","email_verified":true,"failed_login_attempts":1,"id":"11111111-1111-4111-8111-111111111111","is_locked":true,"metadata":{},"mfa_enabled":true,"status":"Active","tenant_id":"11111111-1111-4111-8111-111111111111","updated_at":"2026-08-26T00:00:00Z","username":"example"});
      await client.users.create({ email: 'example', password: new Sensitive('example'), username: 'example' });
    });
  });
  it('users.get', async () => {
    await withServer(async (server, client) => {
      mountJson(server, 'GET', `/api/v1/users/${EXAMPLE_ID}`, 200, {"created_at":"2026-08-26T00:00:00Z","email":"example","email_verified":true,"failed_login_attempts":1,"id":"11111111-1111-4111-8111-111111111111","is_locked":true,"metadata":{},"mfa_enabled":true,"status":"Active","tenant_id":"11111111-1111-4111-8111-111111111111","updated_at":"2026-08-26T00:00:00Z","username":"example"});
      await client.users.get(EXAMPLE_ID);
    });
  });
  it('users.update', async () => {
    await withServer(async (server, client) => {
      mountJson(server, 'PUT', `/api/v1/users/${EXAMPLE_ID}`, 200, {"created_at":"2026-08-26T00:00:00Z","email":"example","email_verified":true,"failed_login_attempts":1,"id":"11111111-1111-4111-8111-111111111111","is_locked":true,"metadata":{},"mfa_enabled":true,"status":"Active","tenant_id":"11111111-1111-4111-8111-111111111111","updated_at":"2026-08-26T00:00:00Z","username":"example"});
      await client.users.update(EXAMPLE_ID, {  });
    });
  });
  it('users.delete', async () => {
    await withServer(async (server, client) => {
      mountJson(server, 'DELETE', `/api/v1/users/${EXAMPLE_ID}`, 204, undefined);
      await client.users.delete(EXAMPLE_ID);
    });
  });
  it('users.list_mfa_methods', async () => {
    await withServer(async (server, client) => {
      mountJson(server, 'GET', `/api/v1/users/${EXAMPLE_ID}/mfa-methods`, 200, [{"created_at":"example","method_id":"example","method_type":"Totp","name":"example"}]);
      await client.users.listMfaMethods(EXAMPLE_ID);
    });
  });
  it('users.delete_mfa_method', async () => {
    await withServer(async (server, client) => {
      mountJson(server, 'DELETE', `/api/v1/users/${EXAMPLE_ID}/mfa-methods/example`, 204, undefined);
      await client.users.deleteMfaMethod(EXAMPLE_ID, 'example');
    });
  });
  it('users.reset_mfa', async () => {
    await withServer(async (server, client) => {
      mountJson(server, 'POST', `/api/v1/users/${EXAMPLE_ID}/reset-mfa`, 204, undefined);
      await client.users.resetMfa(EXAMPLE_ID);
    });
  });
  it('users.unlock', async () => {
    await withServer(async (server, client) => {
      mountJson(server, 'POST', `/api/v1/users/${EXAMPLE_ID}/unlock`, 200, {"created_at":"2026-08-26T00:00:00Z","email":"example","email_verified":true,"failed_login_attempts":1,"id":"11111111-1111-4111-8111-111111111111","is_locked":true,"metadata":{},"mfa_enabled":true,"status":"Active","tenant_id":"11111111-1111-4111-8111-111111111111","updated_at":"2026-08-26T00:00:00Z","username":"example"});
      await client.users.unlock(EXAMPLE_ID);
    });
  });
  it('users.list_roles', async () => {
    await withServer(async (server, client) => {
      mountJson(server, 'GET', `/api/v1/users/${EXAMPLE_ID}/roles`, 200, [{"role":{"created_at":"2026-08-26T00:00:00Z","description":"example","id":"11111111-1111-4111-8111-111111111111","is_global":true,"name":"example","tenant_id":"11111111-1111-4111-8111-111111111111","updated_at":"2026-08-26T00:00:00Z"}}]);
      await client.users.listRoles(EXAMPLE_ID);
    });
  });
});

describe('groups namespace', () => {
  it('groups.list', async () => {
    await withServer(async (server, client) => {
      mountJson(server, 'GET', `/api/v1/groups`, 200, {"items":[{"created_at":"2026-08-26T00:00:00Z","description":"example","id":"11111111-1111-4111-8111-111111111111","metadata":{},"name":"example","tenant_id":"11111111-1111-4111-8111-111111111111","updated_at":"2026-08-26T00:00:00Z"}],"total":1,"offset":0,"limit":50});
      await client.groups.list({ limit: 50 });
      await client.groups.listAll({ limit: 50 });
    });
  });
  it('groups.create', async () => {
    await withServer(async (server, client) => {
      mountJson(server, 'POST', `/api/v1/groups`, 201, {"created_at":"2026-08-26T00:00:00Z","description":"example","id":"11111111-1111-4111-8111-111111111111","metadata":{},"name":"example","tenant_id":"11111111-1111-4111-8111-111111111111","updated_at":"2026-08-26T00:00:00Z"});
      await client.groups.create({ description: 'example', name: 'example' });
    });
  });
  it('groups.get', async () => {
    await withServer(async (server, client) => {
      mountJson(server, 'GET', `/api/v1/groups/${EXAMPLE_ID}`, 200, {"created_at":"2026-08-26T00:00:00Z","description":"example","id":"11111111-1111-4111-8111-111111111111","metadata":{},"name":"example","tenant_id":"11111111-1111-4111-8111-111111111111","updated_at":"2026-08-26T00:00:00Z"});
      await client.groups.get(EXAMPLE_ID);
    });
  });
  it('groups.update', async () => {
    await withServer(async (server, client) => {
      mountJson(server, 'PUT', `/api/v1/groups/${EXAMPLE_ID}`, 200, {"created_at":"2026-08-26T00:00:00Z","description":"example","id":"11111111-1111-4111-8111-111111111111","metadata":{},"name":"example","tenant_id":"11111111-1111-4111-8111-111111111111","updated_at":"2026-08-26T00:00:00Z"});
      await client.groups.update(EXAMPLE_ID, {  });
    });
  });
  it('groups.delete', async () => {
    await withServer(async (server, client) => {
      mountJson(server, 'DELETE', `/api/v1/groups/${EXAMPLE_ID}`, 204, undefined);
      await client.groups.delete(EXAMPLE_ID);
    });
  });
  it('groups.list_members', async () => {
    await withServer(async (server, client) => {
      mountJson(server, 'GET', `/api/v1/groups/${EXAMPLE_ID}/members`, 200, {"items":[{"created_at":"2026-08-26T00:00:00Z","email":"example","email_verified":true,"failed_login_attempts":1,"id":"11111111-1111-4111-8111-111111111111","is_locked":true,"metadata":{},"mfa_enabled":true,"status":"Active","tenant_id":"11111111-1111-4111-8111-111111111111","updated_at":"2026-08-26T00:00:00Z","username":"example"}],"total":1,"offset":0,"limit":50});
      await client.groups.listMembers(EXAMPLE_ID, { limit: 50 });
      await client.groups.listMembersAll(EXAMPLE_ID, { limit: 50 });
    });
  });
  it('groups.add_member', async () => {
    await withServer(async (server, client) => {
      mountJson(server, 'POST', `/api/v1/groups/${EXAMPLE_ID}/members`, 204, undefined);
      await client.groups.addMember(EXAMPLE_ID, { user_id: '11111111-1111-4111-8111-111111111111' });
    });
  });
  it('groups.remove_member', async () => {
    await withServer(async (server, client) => {
      mountJson(server, 'DELETE', `/api/v1/groups/${EXAMPLE_ID}/members/${EXAMPLE_ID}`, 204, undefined);
      await client.groups.removeMember(EXAMPLE_ID, EXAMPLE_ID);
    });
  });
  it('groups.list_roles', async () => {
    await withServer(async (server, client) => {
      mountJson(server, 'GET', `/api/v1/groups/${EXAMPLE_ID}/roles`, 200, [{"role":{"created_at":"2026-08-26T00:00:00Z","description":"example","id":"11111111-1111-4111-8111-111111111111","is_global":true,"name":"example","tenant_id":"11111111-1111-4111-8111-111111111111","updated_at":"2026-08-26T00:00:00Z"}}]);
      await client.groups.listRoles(EXAMPLE_ID);
    });
  });
  it('groups.list_service_accounts', async () => {
    await withServer(async (server, client) => {
      mountJson(server, 'GET', `/api/v1/groups/${EXAMPLE_ID}/service-accounts`, 200, {"items":[{"client_id":"example","created_at":"2026-08-26T00:00:00Z","id":"11111111-1111-4111-8111-111111111111","name":"example","status":"Active","tenant_id":"11111111-1111-4111-8111-111111111111","updated_at":"2026-08-26T00:00:00Z"}],"total":1,"offset":0,"limit":50});
      await client.groups.listServiceAccounts(EXAMPLE_ID, { limit: 50 });
      await client.groups.listServiceAccountsAll(EXAMPLE_ID, { limit: 50 });
    });
  });
  it('groups.add_service_account', async () => {
    await withServer(async (server, client) => {
      mountJson(server, 'POST', `/api/v1/groups/${EXAMPLE_ID}/service-accounts`, 204, undefined);
      await client.groups.addServiceAccount(EXAMPLE_ID, { service_account_id: '11111111-1111-4111-8111-111111111111' });
    });
  });
  it('groups.remove_service_account', async () => {
    await withServer(async (server, client) => {
      mountJson(server, 'DELETE', `/api/v1/groups/${EXAMPLE_ID}/service-accounts/${EXAMPLE_ID}`, 204, undefined);
      await client.groups.removeServiceAccount(EXAMPLE_ID, EXAMPLE_ID);
    });
  });
});

describe('roles namespace', () => {
  it('roles.list', async () => {
    await withServer(async (server, client) => {
      mountJson(server, 'GET', `/api/v1/roles`, 200, {"items":[{"created_at":"2026-08-26T00:00:00Z","description":"example","id":"11111111-1111-4111-8111-111111111111","is_global":true,"name":"example","tenant_id":"11111111-1111-4111-8111-111111111111","updated_at":"2026-08-26T00:00:00Z"}],"total":1,"offset":0,"limit":50});
      await client.roles.list({ limit: 50 });
      await client.roles.listAll({ limit: 50 });
    });
  });
  it('roles.create', async () => {
    await withServer(async (server, client) => {
      mountJson(server, 'POST', `/api/v1/roles`, 201, {"created_at":"2026-08-26T00:00:00Z","description":"example","id":"11111111-1111-4111-8111-111111111111","is_global":true,"name":"example","tenant_id":"11111111-1111-4111-8111-111111111111","updated_at":"2026-08-26T00:00:00Z"});
      await client.roles.create({ description: 'example', is_global: true, name: 'example' });
    });
  });
  it('roles.get', async () => {
    await withServer(async (server, client) => {
      mountJson(server, 'GET', `/api/v1/roles/${EXAMPLE_ID}`, 200, {"created_at":"2026-08-26T00:00:00Z","description":"example","id":"11111111-1111-4111-8111-111111111111","is_global":true,"name":"example","tenant_id":"11111111-1111-4111-8111-111111111111","updated_at":"2026-08-26T00:00:00Z"});
      await client.roles.get(EXAMPLE_ID);
    });
  });
  it('roles.update', async () => {
    await withServer(async (server, client) => {
      mountJson(server, 'PUT', `/api/v1/roles/${EXAMPLE_ID}`, 200, {"created_at":"2026-08-26T00:00:00Z","description":"example","id":"11111111-1111-4111-8111-111111111111","is_global":true,"name":"example","tenant_id":"11111111-1111-4111-8111-111111111111","updated_at":"2026-08-26T00:00:00Z"});
      await client.roles.update(EXAMPLE_ID, {  });
    });
  });
  it('roles.delete', async () => {
    await withServer(async (server, client) => {
      mountJson(server, 'DELETE', `/api/v1/roles/${EXAMPLE_ID}`, 204, undefined);
      await client.roles.delete(EXAMPLE_ID);
    });
  });
  it('roles.list_users', async () => {
    await withServer(async (server, client) => {
      mountJson(server, 'GET', `/api/v1/roles/${EXAMPLE_ID}/users`, 200, [{"user":{"created_at":"2026-08-26T00:00:00Z","email":"example","email_verified":true,"failed_login_attempts":1,"id":"11111111-1111-4111-8111-111111111111","is_locked":true,"metadata":{},"mfa_enabled":true,"status":"Active","tenant_id":"11111111-1111-4111-8111-111111111111","updated_at":"2026-08-26T00:00:00Z","username":"example"}}]);
      await client.roles.listUsers(EXAMPLE_ID);
    });
  });
  it('roles.assign_to_user', async () => {
    await withServer(async (server, client) => {
      mountJson(server, 'POST', `/api/v1/roles/${EXAMPLE_ID}/users`, 204, undefined);
      await client.roles.assignToUser(EXAMPLE_ID, { user_id: '11111111-1111-4111-8111-111111111111' });
    });
  });
  it('roles.unassign_from_user', async () => {
    await withServer(async (server, client) => {
      mountJson(server, 'DELETE', `/api/v1/roles/${EXAMPLE_ID}/users/${EXAMPLE_ID}`, 204, undefined);
      await client.roles.unassignFromUser(EXAMPLE_ID, EXAMPLE_ID, undefined);
    });
  });
  it('roles.list_groups', async () => {
    await withServer(async (server, client) => {
      mountJson(server, 'GET', `/api/v1/roles/${EXAMPLE_ID}/groups`, 200, [{"group":{"created_at":"2026-08-26T00:00:00Z","description":"example","id":"11111111-1111-4111-8111-111111111111","metadata":{},"name":"example","tenant_id":"11111111-1111-4111-8111-111111111111","updated_at":"2026-08-26T00:00:00Z"}}]);
      await client.roles.listGroups(EXAMPLE_ID);
    });
  });
  it('roles.assign_to_group', async () => {
    await withServer(async (server, client) => {
      mountJson(server, 'POST', `/api/v1/roles/${EXAMPLE_ID}/groups`, 204, undefined);
      await client.roles.assignToGroup(EXAMPLE_ID, { group_id: '11111111-1111-4111-8111-111111111111' });
    });
  });
  it('roles.unassign_from_group', async () => {
    await withServer(async (server, client) => {
      mountJson(server, 'DELETE', `/api/v1/roles/${EXAMPLE_ID}/groups/${EXAMPLE_ID}`, 204, undefined);
      await client.roles.unassignFromGroup(EXAMPLE_ID, EXAMPLE_ID, undefined);
    });
  });
  it('roles.list_permissions', async () => {
    await withServer(async (server, client) => {
      mountJson(server, 'GET', `/api/v1/roles/${EXAMPLE_ID}/permissions`, 200, [{"effect":"allow","permission":{"action":"example","created_at":"2026-08-26T00:00:00Z","description":"example","id":"11111111-1111-4111-8111-111111111111","tenant_id":"11111111-1111-4111-8111-111111111111","updated_at":"2026-08-26T00:00:00Z"},"scope_ids":[],"scopes":[]}]);
      await client.roles.listPermissions(EXAMPLE_ID);
    });
  });
  it('roles.grant_permission', async () => {
    await withServer(async (server, client) => {
      mountJson(server, 'POST', `/api/v1/roles/${EXAMPLE_ID}/permissions`, 204, undefined);
      await client.roles.grantPermission(EXAMPLE_ID, { permission_id: '11111111-1111-4111-8111-111111111111' });
    });
  });
  it('roles.revoke_permission', async () => {
    await withServer(async (server, client) => {
      mountJson(server, 'DELETE', `/api/v1/roles/${EXAMPLE_ID}/permissions/${EXAMPLE_ID}`, 204, undefined);
      await client.roles.revokePermission(EXAMPLE_ID, EXAMPLE_ID);
    });
  });
  it('roles.list_service_accounts', async () => {
    await withServer(async (server, client) => {
      mountJson(server, 'GET', `/api/v1/roles/${EXAMPLE_ID}/service-accounts`, 200, [{"service_account":{"client_id":"example","created_at":"2026-08-26T00:00:00Z","id":"11111111-1111-4111-8111-111111111111","name":"example","status":"Active","tenant_id":"11111111-1111-4111-8111-111111111111","updated_at":"2026-08-26T00:00:00Z"}}]);
      await client.roles.listServiceAccounts(EXAMPLE_ID);
    });
  });
  it('roles.assign_to_service_account', async () => {
    await withServer(async (server, client) => {
      mountJson(server, 'POST', `/api/v1/roles/${EXAMPLE_ID}/service-accounts`, 204, undefined);
      await client.roles.assignToServiceAccount(EXAMPLE_ID, { service_account_id: '11111111-1111-4111-8111-111111111111' });
    });
  });
  it('roles.unassign_from_service_account', async () => {
    await withServer(async (server, client) => {
      mountJson(server, 'DELETE', `/api/v1/roles/${EXAMPLE_ID}/service-accounts/${EXAMPLE_ID}`, 204, undefined);
      await client.roles.unassignFromServiceAccount(EXAMPLE_ID, EXAMPLE_ID, undefined);
    });
  });
});

describe('permissions namespace', () => {
  it('permissions.list', async () => {
    await withServer(async (server, client) => {
      mountJson(server, 'GET', `/api/v1/permissions`, 200, {"items":[{"action":"example","created_at":"2026-08-26T00:00:00Z","description":"example","id":"11111111-1111-4111-8111-111111111111","tenant_id":"11111111-1111-4111-8111-111111111111","updated_at":"2026-08-26T00:00:00Z"}],"total":1,"offset":0,"limit":50});
      await client.permissions.list({ limit: 50 });
      await client.permissions.listAll({ limit: 50 });
    });
  });
  it('permissions.create', async () => {
    await withServer(async (server, client) => {
      mountJson(server, 'POST', `/api/v1/permissions`, 201, {"action":"example","created_at":"2026-08-26T00:00:00Z","description":"example","id":"11111111-1111-4111-8111-111111111111","tenant_id":"11111111-1111-4111-8111-111111111111","updated_at":"2026-08-26T00:00:00Z"});
      await client.permissions.create({ action: 'example', description: 'example' });
    });
  });
  it('permissions.get', async () => {
    await withServer(async (server, client) => {
      mountJson(server, 'GET', `/api/v1/permissions/${EXAMPLE_ID}`, 200, {"action":"example","created_at":"2026-08-26T00:00:00Z","description":"example","id":"11111111-1111-4111-8111-111111111111","tenant_id":"11111111-1111-4111-8111-111111111111","updated_at":"2026-08-26T00:00:00Z"});
      await client.permissions.get(EXAMPLE_ID);
    });
  });
  it('permissions.update', async () => {
    await withServer(async (server, client) => {
      mountJson(server, 'PUT', `/api/v1/permissions/${EXAMPLE_ID}`, 200, {"action":"example","created_at":"2026-08-26T00:00:00Z","description":"example","id":"11111111-1111-4111-8111-111111111111","tenant_id":"11111111-1111-4111-8111-111111111111","updated_at":"2026-08-26T00:00:00Z"});
      await client.permissions.update(EXAMPLE_ID, {  });
    });
  });
  it('permissions.delete', async () => {
    await withServer(async (server, client) => {
      mountJson(server, 'DELETE', `/api/v1/permissions/${EXAMPLE_ID}`, 204, undefined);
      await client.permissions.delete(EXAMPLE_ID);
    });
  });
});

describe('resources namespace', () => {
  it('resources.list', async () => {
    await withServer(async (server, client) => {
      mountJson(server, 'GET', `/api/v1/resources`, 200, {"items":[{"created_at":"2026-08-26T00:00:00Z","id":"11111111-1111-4111-8111-111111111111","metadata":{},"name":"example","resource_type":"example","tenant_id":"11111111-1111-4111-8111-111111111111","updated_at":"2026-08-26T00:00:00Z"}],"total":1,"offset":0,"limit":50});
      await client.resources.list({ limit: 50 });
      await client.resources.listAll({ limit: 50 });
    });
  });
  it('resources.create', async () => {
    await withServer(async (server, client) => {
      mountJson(server, 'POST', `/api/v1/resources`, 201, {"created_at":"2026-08-26T00:00:00Z","id":"11111111-1111-4111-8111-111111111111","metadata":{},"name":"example","resource_type":"example","tenant_id":"11111111-1111-4111-8111-111111111111","updated_at":"2026-08-26T00:00:00Z"});
      await client.resources.create({ name: 'example', resource_type: 'example' });
    });
  });
  it('resources.get', async () => {
    await withServer(async (server, client) => {
      mountJson(server, 'GET', `/api/v1/resources/${EXAMPLE_ID}`, 200, {"created_at":"2026-08-26T00:00:00Z","id":"11111111-1111-4111-8111-111111111111","metadata":{},"name":"example","resource_type":"example","tenant_id":"11111111-1111-4111-8111-111111111111","updated_at":"2026-08-26T00:00:00Z"});
      await client.resources.get(EXAMPLE_ID);
    });
  });
  it('resources.update', async () => {
    await withServer(async (server, client) => {
      mountJson(server, 'PUT', `/api/v1/resources/${EXAMPLE_ID}`, 200, {"created_at":"2026-08-26T00:00:00Z","id":"11111111-1111-4111-8111-111111111111","metadata":{},"name":"example","resource_type":"example","tenant_id":"11111111-1111-4111-8111-111111111111","updated_at":"2026-08-26T00:00:00Z"});
      await client.resources.update(EXAMPLE_ID, {  });
    });
  });
  it('resources.delete', async () => {
    await withServer(async (server, client) => {
      mountJson(server, 'DELETE', `/api/v1/resources/${EXAMPLE_ID}`, 204, undefined);
      await client.resources.delete(EXAMPLE_ID);
    });
  });
  it('resources.list_children', async () => {
    await withServer(async (server, client) => {
      mountJson(server, 'GET', `/api/v1/resources/${EXAMPLE_ID}/children`, 200, [{"created_at":"2026-08-26T00:00:00Z","id":"11111111-1111-4111-8111-111111111111","metadata":{},"name":"example","resource_type":"example","tenant_id":"11111111-1111-4111-8111-111111111111","updated_at":"2026-08-26T00:00:00Z"}]);
      await client.resources.listChildren(EXAMPLE_ID);
    });
  });
  it('resources.list_ancestors', async () => {
    await withServer(async (server, client) => {
      mountJson(server, 'GET', `/api/v1/resources/${EXAMPLE_ID}/ancestors`, 200, [{"created_at":"2026-08-26T00:00:00Z","id":"11111111-1111-4111-8111-111111111111","metadata":{},"name":"example","resource_type":"example","tenant_id":"11111111-1111-4111-8111-111111111111","updated_at":"2026-08-26T00:00:00Z"}]);
      await client.resources.listAncestors(EXAMPLE_ID);
    });
  });
});

describe('scopes namespace', () => {
  it('scopes.list', async () => {
    await withServer(async (server, client) => {
      mountJson(server, 'GET', `/api/v1/resources/${EXAMPLE_ID}/scopes`, 200, [{"created_at":"2026-08-26T00:00:00Z","description":"example","id":"11111111-1111-4111-8111-111111111111","name":"example","resource_id":"11111111-1111-4111-8111-111111111111","tenant_id":"11111111-1111-4111-8111-111111111111","updated_at":"2026-08-26T00:00:00Z"}]);
      await client.scopes.list(EXAMPLE_ID);
    });
  });
  it('scopes.create', async () => {
    await withServer(async (server, client) => {
      mountJson(server, 'POST', `/api/v1/resources/${EXAMPLE_ID}/scopes`, 201, {"created_at":"2026-08-26T00:00:00Z","description":"example","id":"11111111-1111-4111-8111-111111111111","name":"example","resource_id":"11111111-1111-4111-8111-111111111111","tenant_id":"11111111-1111-4111-8111-111111111111","updated_at":"2026-08-26T00:00:00Z"});
      await client.scopes.create(EXAMPLE_ID, { description: 'example', name: 'example' });
    });
  });
  it('scopes.get', async () => {
    await withServer(async (server, client) => {
      mountJson(server, 'GET', `/api/v1/resources/${EXAMPLE_ID}/scopes/${EXAMPLE_ID}`, 200, {"created_at":"2026-08-26T00:00:00Z","description":"example","id":"11111111-1111-4111-8111-111111111111","name":"example","resource_id":"11111111-1111-4111-8111-111111111111","tenant_id":"11111111-1111-4111-8111-111111111111","updated_at":"2026-08-26T00:00:00Z"});
      await client.scopes.get(EXAMPLE_ID, EXAMPLE_ID);
    });
  });
  it('scopes.update', async () => {
    await withServer(async (server, client) => {
      mountJson(server, 'PUT', `/api/v1/resources/${EXAMPLE_ID}/scopes/${EXAMPLE_ID}`, 200, {"created_at":"2026-08-26T00:00:00Z","description":"example","id":"11111111-1111-4111-8111-111111111111","name":"example","resource_id":"11111111-1111-4111-8111-111111111111","tenant_id":"11111111-1111-4111-8111-111111111111","updated_at":"2026-08-26T00:00:00Z"});
      await client.scopes.update(EXAMPLE_ID, EXAMPLE_ID, {  });
    });
  });
  it('scopes.delete', async () => {
    await withServer(async (server, client) => {
      mountJson(server, 'DELETE', `/api/v1/resources/${EXAMPLE_ID}/scopes/${EXAMPLE_ID}`, 204, undefined);
      await client.scopes.delete(EXAMPLE_ID, EXAMPLE_ID);
    });
  });
});

describe('service_accounts namespace', () => {
  it('service_accounts.list', async () => {
    await withServer(async (server, client) => {
      mountJson(server, 'GET', `/api/v1/service-accounts`, 200, {"items":[{"client_id":"example","created_at":"2026-08-26T00:00:00Z","id":"11111111-1111-4111-8111-111111111111","name":"example","status":"Active","tenant_id":"11111111-1111-4111-8111-111111111111","updated_at":"2026-08-26T00:00:00Z"}],"total":1,"offset":0,"limit":50});
      await client.serviceAccounts.list({ limit: 50 });
      await client.serviceAccounts.listAll({ limit: 50 });
    });
  });
  it('service_accounts.create', async () => {
    await withServer(async (server, client) => {
      mountJson(server, 'POST', `/api/v1/service-accounts`, 201, {"client_id":"example","client_secret":"example","created_at":"2026-08-26T00:00:00Z","id":"11111111-1111-4111-8111-111111111111","name":"example","status":"Active","tenant_id":"11111111-1111-4111-8111-111111111111","updated_at":"2026-08-26T00:00:00Z"});
      await client.serviceAccounts.create({ name: 'example' });
    });
  });
  it('service_accounts.get', async () => {
    await withServer(async (server, client) => {
      mountJson(server, 'GET', `/api/v1/service-accounts/${EXAMPLE_ID}`, 200, {"client_id":"example","created_at":"2026-08-26T00:00:00Z","id":"11111111-1111-4111-8111-111111111111","name":"example","status":"Active","tenant_id":"11111111-1111-4111-8111-111111111111","updated_at":"2026-08-26T00:00:00Z"});
      await client.serviceAccounts.get(EXAMPLE_ID);
    });
  });
  it('service_accounts.update', async () => {
    await withServer(async (server, client) => {
      mountJson(server, 'PUT', `/api/v1/service-accounts/${EXAMPLE_ID}`, 200, {"client_id":"example","created_at":"2026-08-26T00:00:00Z","id":"11111111-1111-4111-8111-111111111111","name":"example","status":"Active","tenant_id":"11111111-1111-4111-8111-111111111111","updated_at":"2026-08-26T00:00:00Z"});
      await client.serviceAccounts.update(EXAMPLE_ID, {  });
    });
  });
  it('service_accounts.delete', async () => {
    await withServer(async (server, client) => {
      mountJson(server, 'DELETE', `/api/v1/service-accounts/${EXAMPLE_ID}`, 204, undefined);
      await client.serviceAccounts.delete(EXAMPLE_ID);
    });
  });
  it('service_accounts.rotate_secret', async () => {
    await withServer(async (server, client) => {
      mountJson(server, 'POST', `/api/v1/service-accounts/${EXAMPLE_ID}/rotate-secret`, 200, {"client_secret":"example"});
      await client.serviceAccounts.rotateSecret(EXAMPLE_ID);
    });
  });
  it('service_accounts.bind_certificate', async () => {
    await withServer(async (server, client) => {
      mountJson(server, 'POST', `/api/v1/service-accounts/${EXAMPLE_ID}/bind-certificate`, 200, undefined);
      await client.serviceAccounts.bindCertificate(EXAMPLE_ID, { certificate_id: '11111111-1111-4111-8111-111111111111' });
    });
  });
  it('service_accounts.list_roles', async () => {
    await withServer(async (server, client) => {
      mountJson(server, 'GET', `/api/v1/service-accounts/${EXAMPLE_ID}/roles`, 200, [{"role":{"created_at":"2026-08-26T00:00:00Z","description":"example","id":"11111111-1111-4111-8111-111111111111","is_global":true,"name":"example","tenant_id":"11111111-1111-4111-8111-111111111111","updated_at":"2026-08-26T00:00:00Z"}}]);
      await client.serviceAccounts.listRoles(EXAMPLE_ID);
    });
  });
  it('service_accounts.list_groups', async () => {
    await withServer(async (server, client) => {
      mountJson(server, 'GET', `/api/v1/service-accounts/${EXAMPLE_ID}/groups`, 200, [{"created_at":"2026-08-26T00:00:00Z","description":"example","id":"11111111-1111-4111-8111-111111111111","metadata":{},"name":"example","tenant_id":"11111111-1111-4111-8111-111111111111","updated_at":"2026-08-26T00:00:00Z"}]);
      await client.serviceAccounts.listGroups(EXAMPLE_ID);
    });
  });
});

describe('certificates namespace', () => {
  it('certificates.list', async () => {
    await withServer(async (server, client) => {
      mountJson(server, 'GET', `/api/v1/certificates`, 200, {"items":[{"cert_type":"User","created_at":"2026-08-26T00:00:00Z","fingerprint":"example","id":"11111111-1111-4111-8111-111111111111","issuer_ca_id":"11111111-1111-4111-8111-111111111111","key_algorithm":"Rsa4096","metadata":{},"not_after":"2026-08-26T00:00:00Z","not_before":"2026-08-26T00:00:00Z","public_cert_pem":"example","status":"Active","subject":"example","tenant_id":"11111111-1111-4111-8111-111111111111"}],"total":1,"offset":0,"limit":50});
      await client.certificates.list({ limit: 50 });
      await client.certificates.listAll({ limit: 50 });
    });
  });
  it('certificates.generate', async () => {
    await withServer(async (server, client) => {
      mountJson(server, 'POST', `/api/v1/certificates`, 201, {"cert_type":"User","created_at":"2026-08-26T00:00:00Z","fingerprint":"example","id":"11111111-1111-4111-8111-111111111111","issuer_ca_id":"11111111-1111-4111-8111-111111111111","key_algorithm":"Rsa4096","metadata":{},"not_after":"2026-08-26T00:00:00Z","not_before":"2026-08-26T00:00:00Z","public_cert_pem":"example","status":"Active","subject":"example","tenant_id":"11111111-1111-4111-8111-111111111111","private_key_pem":"example"});
      await client.certificates.generate({ cert_type: "User", issuer_ca_id: '11111111-1111-4111-8111-111111111111', key_algorithm: "Rsa4096", subject: 'example', validity_days: 1 });
    });
  });
  it('certificates.get', async () => {
    await withServer(async (server, client) => {
      mountJson(server, 'GET', `/api/v1/certificates/${EXAMPLE_ID}`, 200, {"cert_type":"User","created_at":"2026-08-26T00:00:00Z","fingerprint":"example","id":"11111111-1111-4111-8111-111111111111","issuer_ca_id":"11111111-1111-4111-8111-111111111111","key_algorithm":"Rsa4096","metadata":{},"not_after":"2026-08-26T00:00:00Z","not_before":"2026-08-26T00:00:00Z","public_cert_pem":"example","status":"Active","subject":"example","tenant_id":"11111111-1111-4111-8111-111111111111"});
      await client.certificates.get(EXAMPLE_ID);
    });
  });
  it('certificates.revoke', async () => {
    await withServer(async (server, client) => {
      mountJson(server, 'POST', `/api/v1/certificates/${EXAMPLE_ID}/revoke`, 200, undefined);
      await client.certificates.revoke(EXAMPLE_ID);
    });
  });
});

describe('ca_certificates namespace', () => {
  it('ca_certificates.list', async () => {
    await withServer(async (server, client) => {
      mountJson(server, 'GET', `/api/v1/organizations/${ORG_ID}/ca-certificates`, 200, {"items":[{"created_at":"2026-08-26T00:00:00Z","fingerprint":"example","id":"11111111-1111-4111-8111-111111111111","key_algorithm":"Rsa4096","not_after":"2026-08-26T00:00:00Z","not_before":"2026-08-26T00:00:00Z","organization_id":"11111111-1111-4111-8111-111111111111","public_cert_pem":"example","status":"Active","subject":"example"}],"total":1,"offset":0,"limit":50});
      await client.caCertificates.list({ limit: 50 });
      await client.caCertificates.listAll({ limit: 50 });
    });
  });
  it('ca_certificates.generate', async () => {
    await withServer(async (server, client) => {
      mountJson(server, 'POST', `/api/v1/organizations/${ORG_ID}/ca-certificates`, 201, {"created_at":"2026-08-26T00:00:00Z","fingerprint":"example","id":"11111111-1111-4111-8111-111111111111","key_algorithm":"Rsa4096","not_after":"2026-08-26T00:00:00Z","not_before":"2026-08-26T00:00:00Z","organization_id":"11111111-1111-4111-8111-111111111111","public_cert_pem":"example","status":"Active","subject":"example"});
      await client.caCertificates.generate({ key_algorithm: "Rsa4096", subject: 'example', validity_days: 1 });
    });
  });
  it('ca_certificates.import_ca', async () => {
    await withServer(async (server, client) => {
      mountJson(server, 'POST', `/api/v1/organizations/${ORG_ID}/ca-certificates/import`, 201, {"created_at":"2026-08-26T00:00:00Z","fingerprint":"example","id":"11111111-1111-4111-8111-111111111111","key_algorithm":"Rsa4096","not_after":"2026-08-26T00:00:00Z","not_before":"2026-08-26T00:00:00Z","organization_id":"11111111-1111-4111-8111-111111111111","public_cert_pem":"example","status":"Active","subject":"example"});
      await client.caCertificates.importCa({ public_cert_pem: 'example' });
    });
  });
  it('ca_certificates.get', async () => {
    await withServer(async (server, client) => {
      mountJson(server, 'GET', `/api/v1/organizations/${ORG_ID}/ca-certificates/${EXAMPLE_ID}`, 200, {"created_at":"2026-08-26T00:00:00Z","fingerprint":"example","id":"11111111-1111-4111-8111-111111111111","key_algorithm":"Rsa4096","not_after":"2026-08-26T00:00:00Z","not_before":"2026-08-26T00:00:00Z","organization_id":"11111111-1111-4111-8111-111111111111","public_cert_pem":"example","status":"Active","subject":"example"});
      await client.caCertificates.get(EXAMPLE_ID);
    });
  });
  it('ca_certificates.revoke', async () => {
    await withServer(async (server, client) => {
      mountJson(server, 'POST', `/api/v1/organizations/${ORG_ID}/ca-certificates/${EXAMPLE_ID}/revoke`, 200, undefined);
      await client.caCertificates.revoke(EXAMPLE_ID);
    });
  });
  it('ca_certificates.migrate_custody', async () => {
    await withServer(async (server, client) => {
      mountJson(server, 'POST', `/api/v1/organizations/${ORG_ID}/ca-certificates/${EXAMPLE_ID}/migrate-custody`, 200, {"ca_certificate_id":"11111111-1111-4111-8111-111111111111","key_custody":"example","previous_custody":"example"});
      await client.caCertificates.migrateCustody(EXAMPLE_ID);
    });
  });
  it('ca_certificates.set_mtls_trust_anchor', async () => {
    await withServer(async (server, client) => {
      mountJson(server, 'PUT', `/api/v1/organizations/${ORG_ID}/ca-certificates/${EXAMPLE_ID}/mtls-trust-anchor`, 200, {"ca_certificate_id":"11111111-1111-4111-8111-111111111111","message":"example","mtls_trust_anchor":true,"restart_required":true});
      await client.caCertificates.setMtlsTrustAnchor(EXAMPLE_ID, { enabled: true });
    });
  });
  it('ca_certificates.list_signing_cas', async () => {
    await withServer(async (server, client) => {
      mountJson(server, 'GET', `/api/v1/organizations/${ORG_ID}/tenants/${EXAMPLE_ID}/signing-cas`, 200, {"items":[{"created_at":"2026-08-26T00:00:00Z","fingerprint":"example","id":"11111111-1111-4111-8111-111111111111","key_algorithm":"Rsa4096","not_after":"2026-08-26T00:00:00Z","not_before":"2026-08-26T00:00:00Z","organization_id":"11111111-1111-4111-8111-111111111111","public_cert_pem":"example","status":"Active","subject":"example"}],"total":1,"offset":0,"limit":50});
      await client.caCertificates.listSigningCas(EXAMPLE_ID, { limit: 50 });
      await client.caCertificates.listSigningCasAll(EXAMPLE_ID, { limit: 50 });
    });
  });
  it('ca_certificates.generate_signing_ca', async () => {
    await withServer(async (server, client) => {
      mountJson(server, 'POST', `/api/v1/organizations/${ORG_ID}/tenants/${EXAMPLE_ID}/signing-cas`, 201, {"created_at":"2026-08-26T00:00:00Z","fingerprint":"example","id":"11111111-1111-4111-8111-111111111111","key_algorithm":"Rsa4096","not_after":"2026-08-26T00:00:00Z","not_before":"2026-08-26T00:00:00Z","organization_id":"11111111-1111-4111-8111-111111111111","public_cert_pem":"example","status":"Active","subject":"example"});
      await client.caCertificates.generateSigningCa(EXAMPLE_ID, { key_algorithm: "Rsa4096", parent_ca_id: '11111111-1111-4111-8111-111111111111', subject: 'example', validity_days: 1 });
    });
  });
  it('ca_certificates.sign_signing_ca_csr', async () => {
    await withServer(async (server, client) => {
      mountJson(server, 'POST', `/api/v1/organizations/${ORG_ID}/tenants/${EXAMPLE_ID}/signing-cas/sign-csr`, 201, {"created_at":"2026-08-26T00:00:00Z","fingerprint":"example","id":"11111111-1111-4111-8111-111111111111","key_algorithm":"Rsa4096","not_after":"2026-08-26T00:00:00Z","not_before":"2026-08-26T00:00:00Z","organization_id":"11111111-1111-4111-8111-111111111111","public_cert_pem":"example","status":"Active","subject":"example"});
      await client.caCertificates.signSigningCaCsr(EXAMPLE_ID, { csr_pem: 'example', parent_ca_id: '11111111-1111-4111-8111-111111111111', validity_days: 1 });
    });
  });
});

describe('pgp_keys namespace', () => {
  it('pgp_keys.list', async () => {
    await withServer(async (server, client) => {
      mountJson(server, 'GET', `/api/v1/pgp-keys`, 200, {"items":[{"algorithm":"Rsa4096","created_at":"2026-08-26T00:00:00Z","fingerprint":"example","id":"11111111-1111-4111-8111-111111111111","name":"example","public_key_armored":"example","purpose":"AuditSigning","status":"Active","tenant_id":"11111111-1111-4111-8111-111111111111"}],"total":1,"offset":0,"limit":50});
      await client.pgpKeys.list({ limit: 50 });
      await client.pgpKeys.listAll({ limit: 50 });
    });
  });
  it('pgp_keys.generate', async () => {
    await withServer(async (server, client) => {
      mountJson(server, 'POST', `/api/v1/pgp-keys`, 201, {"algorithm":"Rsa4096","created_at":"2026-08-26T00:00:00Z","fingerprint":"example","id":"11111111-1111-4111-8111-111111111111","name":"example","public_key_armored":"example","purpose":"AuditSigning","status":"Active","tenant_id":"11111111-1111-4111-8111-111111111111"});
      await client.pgpKeys.generate({ algorithm: "Rsa4096", email: 'example', name: 'example', purpose: "AuditSigning" });
    });
  });
  it('pgp_keys.get', async () => {
    await withServer(async (server, client) => {
      mountJson(server, 'GET', `/api/v1/pgp-keys/${EXAMPLE_ID}`, 200, {"algorithm":"Rsa4096","created_at":"2026-08-26T00:00:00Z","fingerprint":"example","id":"11111111-1111-4111-8111-111111111111","name":"example","public_key_armored":"example","purpose":"AuditSigning","status":"Active","tenant_id":"11111111-1111-4111-8111-111111111111"});
      await client.pgpKeys.get(EXAMPLE_ID);
    });
  });
  it('pgp_keys.revoke', async () => {
    await withServer(async (server, client) => {
      mountJson(server, 'POST', `/api/v1/pgp-keys/${EXAMPLE_ID}/revoke`, 200, undefined);
      await client.pgpKeys.revoke(EXAMPLE_ID);
    });
  });
  it('pgp_keys.encrypt', async () => {
    await withServer(async (server, client) => {
      mountJson(server, 'POST', `/api/v1/pgp-keys/${EXAMPLE_ID}/encrypt`, 200, {"ciphertext_armored":"example","recipient_key_id":"11111111-1111-4111-8111-111111111111"});
      await client.pgpKeys.encrypt(EXAMPLE_ID, { data_base64: 'example' });
    });
  });
  it('pgp_keys.sign_audit_batch', async () => {
    await withServer(async (server, client) => {
      mountJson(server, 'POST', `/api/v1/pgp-keys/sign-audit-batch`, 200, {"batch_id":"11111111-1111-4111-8111-111111111111","entry_ids":[],"signature_armored":"example","signed_at":"2026-08-26T00:00:00Z","signing_key_id":"11111111-1111-4111-8111-111111111111","tenant_id":"11111111-1111-4111-8111-111111111111"});
      await client.pgpKeys.signAuditBatch({ entry_ids: [] });
    });
  });
});

describe('webhooks namespace', () => {
  it('webhooks.list', async () => {
    await withServer(async (server, client) => {
      mountJson(server, 'GET', `/api/v1/webhooks`, 200, {"items":[{"created_at":"2026-08-26T00:00:00Z","enabled":true,"events":[],"id":"11111111-1111-4111-8111-111111111111","retry_policy":{"backoff_multiplier":1,"initial_delay_secs":1,"max_retries":1},"tenant_id":"11111111-1111-4111-8111-111111111111","updated_at":"2026-08-26T00:00:00Z","url":"example"}],"total":1,"offset":0,"limit":50});
      await client.webhooks.list({ limit: 50 });
      await client.webhooks.listAll({ limit: 50 });
    });
  });
  it('webhooks.create', async () => {
    await withServer(async (server, client) => {
      mountJson(server, 'POST', `/api/v1/webhooks`, 201, {"created_at":"2026-08-26T00:00:00Z","enabled":true,"events":[],"id":"11111111-1111-4111-8111-111111111111","retry_policy":{"backoff_multiplier":1,"initial_delay_secs":1,"max_retries":1},"tenant_id":"11111111-1111-4111-8111-111111111111","updated_at":"2026-08-26T00:00:00Z","url":"example"});
      await client.webhooks.create({ events: [], secret: new Sensitive('example'), url: 'example' });
    });
  });
  it('webhooks.get', async () => {
    await withServer(async (server, client) => {
      mountJson(server, 'GET', `/api/v1/webhooks/${EXAMPLE_ID}`, 200, {"created_at":"2026-08-26T00:00:00Z","enabled":true,"events":[],"id":"11111111-1111-4111-8111-111111111111","retry_policy":{"backoff_multiplier":1,"initial_delay_secs":1,"max_retries":1},"tenant_id":"11111111-1111-4111-8111-111111111111","updated_at":"2026-08-26T00:00:00Z","url":"example"});
      await client.webhooks.get(EXAMPLE_ID);
    });
  });
  it('webhooks.update', async () => {
    await withServer(async (server, client) => {
      mountJson(server, 'PUT', `/api/v1/webhooks/${EXAMPLE_ID}`, 200, {"created_at":"2026-08-26T00:00:00Z","enabled":true,"events":[],"id":"11111111-1111-4111-8111-111111111111","retry_policy":{"backoff_multiplier":1,"initial_delay_secs":1,"max_retries":1},"tenant_id":"11111111-1111-4111-8111-111111111111","updated_at":"2026-08-26T00:00:00Z","url":"example"});
      await client.webhooks.update(EXAMPLE_ID, {  });
    });
  });
  it('webhooks.delete', async () => {
    await withServer(async (server, client) => {
      mountJson(server, 'DELETE', `/api/v1/webhooks/${EXAMPLE_ID}`, 204, undefined);
      await client.webhooks.delete(EXAMPLE_ID);
    });
  });
});

describe('oauth2_clients namespace', () => {
  it('oauth2_clients.list', async () => {
    await withServer(async (server, client) => {
      mountJson(server, 'GET', `/api/v1/oauth2-clients`, 200, {"items":[{"client_id":"example","created_at":"2026-08-26T00:00:00Z","dpop_bound_access_tokens":true,"dpop_require_nonce":true,"grant_types":[],"id":"11111111-1111-4111-8111-111111111111","name":"example","profile":"standard","redirect_uris":[],"require_par":true,"scopes":[],"self_signed_tls_client_auth_thumbprints":[],"tenant_id":"11111111-1111-4111-8111-111111111111","tls_client_certificate_bound_access_tokens":true,"token_endpoint_auth_method":"client_secret_post","updated_at":"2026-08-26T00:00:00Z"}],"total":1,"offset":0,"limit":50});
      await client.oauth2Clients.list({ limit: 50 });
      await client.oauth2Clients.listAll({ limit: 50 });
    });
  });
  it('oauth2_clients.create', async () => {
    await withServer(async (server, client) => {
      mountJson(server, 'POST', `/api/v1/oauth2-clients`, 201, {"client_id":"example","client_secret":"example","created_at":"2026-08-26T00:00:00Z","grant_types":[],"id":"11111111-1111-4111-8111-111111111111","name":"example","redirect_uris":[],"scopes":[],"tenant_id":"11111111-1111-4111-8111-111111111111","updated_at":"2026-08-26T00:00:00Z"});
      await client.oauth2Clients.create({ grant_types: [], name: 'example', redirect_uris: [], scopes: [] });
    });
  });
  it('oauth2_clients.get', async () => {
    await withServer(async (server, client) => {
      mountJson(server, 'GET', `/api/v1/oauth2-clients/${EXAMPLE_ID}`, 200, {"client_id":"example","created_at":"2026-08-26T00:00:00Z","dpop_bound_access_tokens":true,"dpop_require_nonce":true,"grant_types":[],"id":"11111111-1111-4111-8111-111111111111","name":"example","profile":"standard","redirect_uris":[],"require_par":true,"scopes":[],"self_signed_tls_client_auth_thumbprints":[],"tenant_id":"11111111-1111-4111-8111-111111111111","tls_client_certificate_bound_access_tokens":true,"token_endpoint_auth_method":"client_secret_post","updated_at":"2026-08-26T00:00:00Z"});
      await client.oauth2Clients.get(EXAMPLE_ID);
    });
  });
  it('oauth2_clients.update', async () => {
    await withServer(async (server, client) => {
      mountJson(server, 'PUT', `/api/v1/oauth2-clients/${EXAMPLE_ID}`, 200, {"client_id":"example","created_at":"2026-08-26T00:00:00Z","dpop_bound_access_tokens":true,"dpop_require_nonce":true,"grant_types":[],"id":"11111111-1111-4111-8111-111111111111","name":"example","profile":"standard","redirect_uris":[],"require_par":true,"scopes":[],"self_signed_tls_client_auth_thumbprints":[],"tenant_id":"11111111-1111-4111-8111-111111111111","tls_client_certificate_bound_access_tokens":true,"token_endpoint_auth_method":"client_secret_post","updated_at":"2026-08-26T00:00:00Z"});
      await client.oauth2Clients.update(EXAMPLE_ID, {  });
    });
  });
  it('oauth2_clients.delete', async () => {
    await withServer(async (server, client) => {
      mountJson(server, 'DELETE', `/api/v1/oauth2-clients/${EXAMPLE_ID}`, 204, undefined);
      await client.oauth2Clients.delete(EXAMPLE_ID);
    });
  });
});

describe('federation namespace', () => {
  it('federation.list_configs', async () => {
    await withServer(async (server, client) => {
      mountJson(server, 'GET', `/api/v1/federation-configs`, 200, {"items":[{"allow_tenant_inheritance":true,"allowed_algorithms":[],"allowed_issuer_tenants":[],"attribute_map":{},"client_id":"example","created_at":"2026-08-26T00:00:00Z","effective_scopes":[],"enabled":true,"has_bundled_mark":true,"id":"11111111-1111-4111-8111-111111111111","mints_client_secret":true,"pkce_required":true,"protocol":"example","provider":"example","provider_kind":"example","scopes":[],"tenant_id":"11111111-1111-4111-8111-111111111111","token_exchange":{"accepted_audiences":[],"enabled":true,"max_token_age_secs":1,"scope_map":{},"subject_mapping":"example"},"updated_at":"2026-08-26T00:00:00Z"}],"total":1,"offset":0,"limit":50});
      await client.federation.listConfigs({ limit: 50 });
      await client.federation.listConfigsAll({ limit: 50 });
    });
  });
  it('federation.create_config', async () => {
    await withServer(async (server, client) => {
      mountJson(server, 'POST', `/api/v1/federation-configs`, 201, {"allow_tenant_inheritance":true,"allowed_algorithms":[],"allowed_issuer_tenants":[],"attribute_map":{},"client_id":"example","created_at":"2026-08-26T00:00:00Z","effective_scopes":[],"enabled":true,"has_bundled_mark":true,"id":"11111111-1111-4111-8111-111111111111","mints_client_secret":true,"pkce_required":true,"protocol":"example","provider":"example","provider_kind":"example","scopes":[],"tenant_id":"11111111-1111-4111-8111-111111111111","token_exchange":{"accepted_audiences":[],"enabled":true,"max_token_age_secs":1,"scope_map":{},"subject_mapping":"example"},"updated_at":"2026-08-26T00:00:00Z"});
      await client.federation.createConfig({ client_id: 'example', client_secret: new Sensitive('example'), protocol: 'example', provider: 'example' });
    });
  });
  it('federation.get_config', async () => {
    await withServer(async (server, client) => {
      mountJson(server, 'GET', `/api/v1/federation-configs/${EXAMPLE_ID}`, 200, {"allow_tenant_inheritance":true,"allowed_algorithms":[],"allowed_issuer_tenants":[],"attribute_map":{},"client_id":"example","created_at":"2026-08-26T00:00:00Z","effective_scopes":[],"enabled":true,"has_bundled_mark":true,"id":"11111111-1111-4111-8111-111111111111","mints_client_secret":true,"pkce_required":true,"protocol":"example","provider":"example","provider_kind":"example","scopes":[],"tenant_id":"11111111-1111-4111-8111-111111111111","token_exchange":{"accepted_audiences":[],"enabled":true,"max_token_age_secs":1,"scope_map":{},"subject_mapping":"example"},"updated_at":"2026-08-26T00:00:00Z"});
      await client.federation.getConfig(EXAMPLE_ID);
    });
  });
  it('federation.update_config', async () => {
    await withServer(async (server, client) => {
      mountJson(server, 'PUT', `/api/v1/federation-configs/${EXAMPLE_ID}`, 200, {"allow_tenant_inheritance":true,"allowed_algorithms":[],"allowed_issuer_tenants":[],"attribute_map":{},"client_id":"example","created_at":"2026-08-26T00:00:00Z","effective_scopes":[],"enabled":true,"has_bundled_mark":true,"id":"11111111-1111-4111-8111-111111111111","mints_client_secret":true,"pkce_required":true,"protocol":"example","provider":"example","provider_kind":"example","scopes":[],"tenant_id":"11111111-1111-4111-8111-111111111111","token_exchange":{"accepted_audiences":[],"enabled":true,"max_token_age_secs":1,"scope_map":{},"subject_mapping":"example"},"updated_at":"2026-08-26T00:00:00Z"});
      await client.federation.updateConfig(EXAMPLE_ID, {  });
    });
  });
  it('federation.delete_config', async () => {
    await withServer(async (server, client) => {
      mountJson(server, 'DELETE', `/api/v1/federation-configs/${EXAMPLE_ID}`, 204, undefined);
      await client.federation.deleteConfig(EXAMPLE_ID);
    });
  });
  it('federation.list_user_links', async () => {
    await withServer(async (server, client) => {
      mountJson(server, 'GET', `/api/v1/federation-links/user/${EXAMPLE_ID}`, 200, [{"created_at":"2026-08-26T00:00:00Z","external_subject":"example","federation_config_id":"11111111-1111-4111-8111-111111111111","id":"11111111-1111-4111-8111-111111111111","tenant_id":"11111111-1111-4111-8111-111111111111","updated_at":"2026-08-26T00:00:00Z","user_id":"11111111-1111-4111-8111-111111111111"}]);
      await client.federation.listUserLinks(EXAMPLE_ID);
    });
  });
  it('federation.delete_link', async () => {
    await withServer(async (server, client) => {
      mountJson(server, 'DELETE', `/api/v1/federation-links/${EXAMPLE_ID}`, 204, undefined);
      await client.federation.deleteLink(EXAMPLE_ID);
    });
  });
  it('federation.oidc_authorize', async () => {
    await withServer(async (server, client) => {
      mountJson(server, 'POST', `/api/v1/federation/oidc/authorize`, 200, {"url":"example"});
      await client.federation.oidcAuthorize({ config_id: '11111111-1111-4111-8111-111111111111', nonce: 'example', redirect_uri: 'example', state: 'example' });
    });
  });
  it('federation.oidc_callback', async () => {
    await withServer(async (server, client) => {
      mountJson(server, 'POST', `/api/v1/federation/oidc/callback`, 200, {"federation_link_id":"11111111-1111-4111-8111-111111111111","newly_provisioned":true,"user_id":"11111111-1111-4111-8111-111111111111"});
      await client.federation.oidcCallback({ code: 'example', config_id: '11111111-1111-4111-8111-111111111111', nonce: 'example', redirect_uri: 'example', state: 'example' });
    });
  });
});

describe('notification_rules namespace', () => {
  it('notification_rules.list', async () => {
    await withServer(async (server, client) => {
      mountJson(server, 'GET', `/api/v1/notification-rules`, 200, {"items":[{"created_at":"2026-08-26T00:00:00Z","description":"example","enabled":true,"events":[],"id":"11111111-1111-4111-8111-111111111111","name":"example","recipient_emails":[],"tenant_id":"11111111-1111-4111-8111-111111111111","updated_at":"2026-08-26T00:00:00Z"}],"total":1,"offset":0,"limit":50});
      await client.notificationRules.list({ limit: 50 });
      await client.notificationRules.listAll({ limit: 50 });
    });
  });
  it('notification_rules.create', async () => {
    await withServer(async (server, client) => {
      mountJson(server, 'POST', `/api/v1/notification-rules`, 201, {"created_at":"2026-08-26T00:00:00Z","description":"example","enabled":true,"events":[],"id":"11111111-1111-4111-8111-111111111111","name":"example","recipient_emails":[],"tenant_id":"11111111-1111-4111-8111-111111111111","updated_at":"2026-08-26T00:00:00Z"});
      await client.notificationRules.create({ description: 'example', events: [], name: 'example', recipient_emails: [] });
    });
  });
  it('notification_rules.get', async () => {
    await withServer(async (server, client) => {
      mountJson(server, 'GET', `/api/v1/notification-rules/${EXAMPLE_ID}`, 200, {"created_at":"2026-08-26T00:00:00Z","description":"example","enabled":true,"events":[],"id":"11111111-1111-4111-8111-111111111111","name":"example","recipient_emails":[],"tenant_id":"11111111-1111-4111-8111-111111111111","updated_at":"2026-08-26T00:00:00Z"});
      await client.notificationRules.get(EXAMPLE_ID);
    });
  });
  it('notification_rules.update', async () => {
    await withServer(async (server, client) => {
      mountJson(server, 'PUT', `/api/v1/notification-rules/${EXAMPLE_ID}`, 200, {"created_at":"2026-08-26T00:00:00Z","description":"example","enabled":true,"events":[],"id":"11111111-1111-4111-8111-111111111111","name":"example","recipient_emails":[],"tenant_id":"11111111-1111-4111-8111-111111111111","updated_at":"2026-08-26T00:00:00Z"});
      await client.notificationRules.update(EXAMPLE_ID, {  });
    });
  });
  it('notification_rules.delete', async () => {
    await withServer(async (server, client) => {
      mountJson(server, 'DELETE', `/api/v1/notification-rules/${EXAMPLE_ID}`, 204, undefined);
      await client.notificationRules.delete(EXAMPLE_ID);
    });
  });
});

describe('email_config namespace', () => {
  it('email_config.get_org', async () => {
    await withServer(async (server, client) => {
      mountJson(server, 'GET', `/api/v1/organizations/${ORG_ID}/email-config`, 200, {"created_at":"2026-08-26T00:00:00Z","enabled":true,"from_email":"example","from_name":"example","id":"11111111-1111-4111-8111-111111111111","provider":{"host":"example","port":1,"starttls":true,"username":"example","kind":"smtp"},"scope":"Org","scope_id":"11111111-1111-4111-8111-111111111111","updated_at":"2026-08-26T00:00:00Z"});
      await client.emailConfig.getOrg();
    });
  });
  it('email_config.set_org', async () => {
    await withServer(async (server, client) => {
      mountJson(server, 'PUT', `/api/v1/organizations/${ORG_ID}/email-config`, 200, {"created_at":"2026-08-26T00:00:00Z","enabled":true,"from_email":"example","from_name":"example","id":"11111111-1111-4111-8111-111111111111","provider":{"host":"example","port":1,"starttls":true,"username":"example","kind":"smtp"},"scope":"Org","scope_id":"11111111-1111-4111-8111-111111111111","updated_at":"2026-08-26T00:00:00Z"});
      await client.emailConfig.setOrg({ enabled: true, from_email: 'example', from_name: 'example', provider: { kind: "smtp", ...{ host: 'example', port: 1, starttls: true, username: 'example' } } });
    });
  });
  it('email_config.delete_org', async () => {
    await withServer(async (server, client) => {
      mountJson(server, 'DELETE', `/api/v1/organizations/${ORG_ID}/email-config`, 204, undefined);
      await client.emailConfig.deleteOrg();
    });
  });
  it('email_config.test_org', async () => {
    await withServer(async (server, client) => {
      mountJson(server, 'POST', `/api/v1/organizations/${ORG_ID}/email-config/test`, 200, {"provider":"example","to":"example"});
      await client.emailConfig.testOrg();
    });
  });
  it('email_config.get_tenant', async () => {
    await withServer(async (server, client) => {
      mountJson(server, 'GET', `/api/v1/tenants/${TENANT_ID}/email-config`, 200, {});
      await client.emailConfig.getTenant();
    });
  });
  it('email_config.set_tenant', async () => {
    await withServer(async (server, client) => {
      mountJson(server, 'PUT', `/api/v1/tenants/${TENANT_ID}/email-config`, 200, {});
      await client.emailConfig.setTenant({  });
    });
  });
  it('email_config.delete_tenant', async () => {
    await withServer(async (server, client) => {
      mountJson(server, 'DELETE', `/api/v1/tenants/${TENANT_ID}/email-config`, 204, undefined);
      await client.emailConfig.deleteTenant();
    });
  });
  it('email_config.test_tenant', async () => {
    await withServer(async (server, client) => {
      mountJson(server, 'POST', `/api/v1/tenants/${TENANT_ID}/email-config/test`, 200, {"provider":"example","to":"example"});
      await client.emailConfig.testTenant();
    });
  });
});

describe('settings namespace', () => {
  it('settings.get_org', async () => {
    await withServer(async (server, client) => {
      mountJson(server, 'GET', `/api/v1/organizations/${ORG_ID}/settings`, 200, {"certificate":{"default_cert_validity_days":1,"max_cert_validity_days":1},"created_at":"2026-08-26T00:00:00Z","email":{"email_verification_grace_period_hours":1,"email_verification_required":true},"id":"11111111-1111-4111-8111-111111111111","lockout":{"lockout_backoff_multiplier":1,"lockout_duration_secs":1,"max_failed_login_attempts":1,"max_lockout_duration_secs":1},"mfa":{"mfa_challenge_lifetime_secs":1,"mfa_enforced":true},"notification":{"admin_notifications_enabled":true},"opaque":{"opaque_ksf":"example","opaque_mode":"example","opaque_suite":"example"},"password":{"hibp_check_enabled":true,"min_length":1,"password_history_count":1,"require_digits":true,"require_lowercase":true,"require_symbols":true,"require_uppercase":true},"privacy":{"deletion_grace_period_days":1},"scope":"Org","scope_id":"11111111-1111-4111-8111-111111111111","token":{"access_token_lifetime_secs":1,"refresh_token_lifetime_secs":1},"updated_at":"2026-08-26T00:00:00Z"});
      await client.settings.getOrg();
    });
  });
  it('settings.set_org', async () => {
    await withServer(async (server, client) => {
      mountJson(server, 'PUT', `/api/v1/organizations/${ORG_ID}/settings`, 200, {"certificate":{"default_cert_validity_days":1,"max_cert_validity_days":1},"created_at":"2026-08-26T00:00:00Z","email":{"email_verification_grace_period_hours":1,"email_verification_required":true},"id":"11111111-1111-4111-8111-111111111111","lockout":{"lockout_backoff_multiplier":1,"lockout_duration_secs":1,"max_failed_login_attempts":1,"max_lockout_duration_secs":1},"mfa":{"mfa_challenge_lifetime_secs":1,"mfa_enforced":true},"notification":{"admin_notifications_enabled":true},"opaque":{"opaque_ksf":"example","opaque_mode":"example","opaque_suite":"example"},"password":{"hibp_check_enabled":true,"min_length":1,"password_history_count":1,"require_digits":true,"require_lowercase":true,"require_symbols":true,"require_uppercase":true},"privacy":{"deletion_grace_period_days":1},"scope":"Org","scope_id":"11111111-1111-4111-8111-111111111111","token":{"access_token_lifetime_secs":1,"refresh_token_lifetime_secs":1},"updated_at":"2026-08-26T00:00:00Z"});
      await client.settings.setOrg({ access_token_lifetime_secs: 1, admin_notifications_enabled: true, default_cert_validity_days: 1, email_verification_grace_period_hours: 1, email_verification_required: true, hibp_check_enabled: true, lockout_backoff_multiplier: 1, lockout_duration_secs: 1, max_cert_validity_days: 1, max_failed_login_attempts: 1, max_lockout_duration_secs: 1, mfa_challenge_lifetime_secs: 1, mfa_enforced: true, min_length: 1, password_history_count: 1, refresh_token_lifetime_secs: 1, require_digits: true, require_lowercase: true, require_symbols: true, require_uppercase: true });
    });
  });
  it('settings.get_effective', async () => {
    await withServer(async (server, client) => {
      mountJson(server, 'GET', `/api/v1/settings`, 200, {"certificate":{"default_cert_validity_days":1,"max_cert_validity_days":1},"created_at":"2026-08-26T00:00:00Z","email":{"email_verification_grace_period_hours":1,"email_verification_required":true},"id":"11111111-1111-4111-8111-111111111111","lockout":{"lockout_backoff_multiplier":1,"lockout_duration_secs":1,"max_failed_login_attempts":1,"max_lockout_duration_secs":1},"mfa":{"mfa_challenge_lifetime_secs":1,"mfa_enforced":true},"notification":{"admin_notifications_enabled":true},"opaque":{"opaque_ksf":"example","opaque_mode":"example","opaque_suite":"example"},"password":{"hibp_check_enabled":true,"min_length":1,"password_history_count":1,"require_digits":true,"require_lowercase":true,"require_symbols":true,"require_uppercase":true},"privacy":{"deletion_grace_period_days":1},"scope":"Org","scope_id":"11111111-1111-4111-8111-111111111111","token":{"access_token_lifetime_secs":1,"refresh_token_lifetime_secs":1},"updated_at":"2026-08-26T00:00:00Z"});
      await client.settings.getEffective();
    });
  });
  it('settings.set_effective', async () => {
    await withServer(async (server, client) => {
      mountJson(server, 'PUT', `/api/v1/settings`, 200, {"certificate":{"default_cert_validity_days":1,"max_cert_validity_days":1},"created_at":"2026-08-26T00:00:00Z","email":{"email_verification_grace_period_hours":1,"email_verification_required":true},"id":"11111111-1111-4111-8111-111111111111","lockout":{"lockout_backoff_multiplier":1,"lockout_duration_secs":1,"max_failed_login_attempts":1,"max_lockout_duration_secs":1},"mfa":{"mfa_challenge_lifetime_secs":1,"mfa_enforced":true},"notification":{"admin_notifications_enabled":true},"opaque":{"opaque_ksf":"example","opaque_mode":"example","opaque_suite":"example"},"password":{"hibp_check_enabled":true,"min_length":1,"password_history_count":1,"require_digits":true,"require_lowercase":true,"require_symbols":true,"require_uppercase":true},"privacy":{"deletion_grace_period_days":1},"scope":"Org","scope_id":"11111111-1111-4111-8111-111111111111","token":{"access_token_lifetime_secs":1,"refresh_token_lifetime_secs":1},"updated_at":"2026-08-26T00:00:00Z"});
      await client.settings.setEffective({  });
    });
  });
  it('settings.get_tenant_override', async () => {
    await withServer(async (server, client) => {
      mountJson(server, 'GET', `/api/v1/tenants/${TENANT_ID}/settings`, 200, {});
      await client.settings.getTenantOverride();
    });
  });
  it('settings.set_tenant_override', async () => {
    await withServer(async (server, client) => {
      mountJson(server, 'PUT', `/api/v1/tenants/${TENANT_ID}/settings`, 200, {});
      await client.settings.setTenantOverride({  });
    });
  });
  it('settings.delete_tenant_override', async () => {
    await withServer(async (server, client) => {
      mountJson(server, 'DELETE', `/api/v1/tenants/${TENANT_ID}/settings`, 204, undefined);
      await client.settings.deleteTenantOverride();
    });
  });
});

describe('scim_tokens namespace', () => {
  it('scim_tokens.list', async () => {
    await withServer(async (server, client) => {
      mountJson(server, 'GET', `/api/v1/scim-tokens`, 200, [{"created_at":"2026-08-26T00:00:00Z","created_by":"11111111-1111-4111-8111-111111111111","expires_at":"2026-08-26T00:00:00Z","id":"11111111-1111-4111-8111-111111111111","name":"example","status":"active","tenant_id":"11111111-1111-4111-8111-111111111111","user_id":"11111111-1111-4111-8111-111111111111"}]);
      await client.scimTokens.list();
    });
  });
  it('scim_tokens.create', async () => {
    await withServer(async (server, client) => {
      mountJson(server, 'POST', `/api/v1/scim-tokens`, 201, {"created_at":"2026-08-26T00:00:00Z","created_by":"11111111-1111-4111-8111-111111111111","expires_at":"2026-08-26T00:00:00Z","id":"11111111-1111-4111-8111-111111111111","name":"example","status":"active","tenant_id":"11111111-1111-4111-8111-111111111111","user_id":"11111111-1111-4111-8111-111111111111","provisioning_token":"example"});
      await client.scimTokens.create({ name: 'example', user_id: '11111111-1111-4111-8111-111111111111' });
    });
  });
  it('scim_tokens.revoke', async () => {
    await withServer(async (server, client) => {
      mountJson(server, 'DELETE', `/api/v1/scim-tokens/${EXAMPLE_ID}`, 204, undefined);
      await client.scimTokens.revoke(EXAMPLE_ID);
    });
  });
});

describe('reactors namespace', () => {
  it('reactors.list', async () => {
    await withServer(async (server, client) => {
      mountJson(server, 'GET', `/api/v1/reactors`, 200, {"items":[{"created_at":"2026-08-26T00:00:00Z","description":"example","enabled":true,"events":[],"failure_policy":"fail_closed","id":"11111111-1111-4111-8111-111111111111","mode":"intercept","name":"example","priority":1,"recent_timeout_count":1,"recent_veto_count":1,"tenant_id":"11111111-1111-4111-8111-111111111111","timeout_ms":1,"updated_at":"2026-08-26T00:00:00Z"}],"total":1,"offset":0,"limit":50});
      await client.reactors.list({ limit: 50 });
      await client.reactors.listAll({ limit: 50 });
    });
  });
  it('reactors.create', async () => {
    await withServer(async (server, client) => {
      mountJson(server, 'POST', `/api/v1/reactors`, 201, {"created_at":"2026-08-26T00:00:00Z","description":"example","enabled":true,"events":[],"failure_policy":"fail_closed","id":"11111111-1111-4111-8111-111111111111","mode":"intercept","name":"example","priority":1,"recent_timeout_count":1,"recent_veto_count":1,"tenant_id":"11111111-1111-4111-8111-111111111111","timeout_ms":1,"updated_at":"2026-08-26T00:00:00Z"});
      await client.reactors.create({ events: [], mode: "intercept", name: 'example' });
    });
  });
  it('reactors.get', async () => {
    await withServer(async (server, client) => {
      mountJson(server, 'GET', `/api/v1/reactors/${EXAMPLE_ID}`, 200, {"created_at":"2026-08-26T00:00:00Z","description":"example","enabled":true,"events":[],"failure_policy":"fail_closed","id":"11111111-1111-4111-8111-111111111111","mode":"intercept","name":"example","priority":1,"recent_timeout_count":1,"recent_veto_count":1,"tenant_id":"11111111-1111-4111-8111-111111111111","timeout_ms":1,"updated_at":"2026-08-26T00:00:00Z"});
      await client.reactors.get(EXAMPLE_ID);
    });
  });
  it('reactors.update', async () => {
    await withServer(async (server, client) => {
      mountJson(server, 'PUT', `/api/v1/reactors/${EXAMPLE_ID}`, 200, {"created_at":"2026-08-26T00:00:00Z","description":"example","enabled":true,"events":[],"failure_policy":"fail_closed","id":"11111111-1111-4111-8111-111111111111","mode":"intercept","name":"example","priority":1,"recent_timeout_count":1,"recent_veto_count":1,"tenant_id":"11111111-1111-4111-8111-111111111111","timeout_ms":1,"updated_at":"2026-08-26T00:00:00Z"});
      await client.reactors.update(EXAMPLE_ID, {  });
    });
  });
  it('reactors.delete', async () => {
    await withServer(async (server, client) => {
      mountJson(server, 'DELETE', `/api/v1/reactors/${EXAMPLE_ID}`, 204, undefined);
      await client.reactors.delete(EXAMPLE_ID);
    });
  });
  it('reactors.list_events', async () => {
    await withServer(async (server, client) => {
      mountJson(server, 'GET', `/api/v1/reactors/events`, 200, [{"default_failure_policy":"fail_closed","description":"example","interceptable":true,"mutable":true,"mutable_fields":[],"name":"example"}]);
      await client.reactors.listEvents();
    });
  });
});

describe('webauthn_policy namespace', () => {
  it('webauthn_policy.get', async () => {
    await withServer(async (server, client) => {
      mountJson(server, 'GET', `/api/v1/tenants/${TENANT_ID}/webauthn/attestation-policy`, 200, {"block_revoked_status":true,"mode":"none","require_fido_certified":true,"effective_unknown_aaguid":"allow"});
      await client.webauthnPolicy.get();
    });
  });
  it('webauthn_policy.set', async () => {
    await withServer(async (server, client) => {
      mountJson(server, 'PUT', `/api/v1/tenants/${TENANT_ID}/webauthn/attestation-policy`, 200, {"block_revoked_status":true,"mode":"none","require_fido_certified":true});
      await client.webauthnPolicy.set({ block_revoked_status: true, mode: "none", require_fido_certified: true });
    });
  });
  it('webauthn_policy.compliance_report', async () => {
    await withServer(async (server, client) => {
      mountJson(server, 'GET', `/api/v1/tenants/${TENANT_ID}/webauthn/compliance-report`, 200, [{"compliant":true,"credential_id":"11111111-1111-4111-8111-111111111111","name":"example","user_id":"11111111-1111-4111-8111-111111111111"}]);
      await client.webauthnPolicy.complianceReport();
    });
  });
});

describe('audit namespace', () => {
  it('audit.list', async () => {
    await withServer(async (server, client) => {
      mountJson(server, 'GET', `/api/v1/audit-logs`, 200, {"items":[{"action":"example","actor_id":"11111111-1111-4111-8111-111111111111","actor_type":"User","id":"11111111-1111-4111-8111-111111111111","metadata":{},"outcome":"Success","tenant_id":"11111111-1111-4111-8111-111111111111","timestamp":"2026-08-26T00:00:00Z"}],"total":1,"offset":0,"limit":50});
      await client.audit.list({}, { limit: 50 });
      await client.audit.listAll({}, { limit: 50 });
    });
  });
  it('audit.list_system', async () => {
    await withServer(async (server, client) => {
      mountJson(server, 'GET', `/api/v1/audit-logs/system`, 200, {"items":[{"action":"example","actor_id":"11111111-1111-4111-8111-111111111111","actor_type":"User","id":"11111111-1111-4111-8111-111111111111","metadata":{},"outcome":"Success","tenant_id":"11111111-1111-4111-8111-111111111111","timestamp":"2026-08-26T00:00:00Z"}],"total":1,"offset":0,"limit":50});
      await client.audit.listSystem({}, { limit: 50 });
      await client.audit.listSystemAll({}, { limit: 50 });
    });
  });
});

describe('privacy namespace', () => {
  it('privacy.request_export', async () => {
    await withServer(async (server, client) => {
      mountJson(server, 'POST', `/api/v1/account/export`, 200, undefined);
      await client.privacy.requestExport({});
    });
  });
  it('privacy.download_export', async () => {
    await withServer(async (server, client) => {
      mountJson(server, 'GET', `/api/v1/account/export/example`, 200, undefined);
      await client.privacy.downloadExport('example');
    });
  });
  it('privacy.request_delete', async () => {
    await withServer(async (server, client) => {
      mountJson(server, 'POST', `/api/v1/account/delete`, 200, undefined);
      await client.privacy.requestDelete({});
    });
  });
  it('privacy.cancel_delete', async () => {
    await withServer(async (server, client) => {
      mountJson(server, 'GET', `/api/v1/auth/account/delete/cancel`, 200, undefined);
      await client.privacy.cancelDelete('example');
    });
  });
});

describe('platform namespace', () => {
  it('platform.health', async () => {
    await withServer(async (server, client) => {
      mountJson(server, 'GET', `/health`, 200, {"status":"example"});
      await client.platform.health();
    });
  });
  it('platform.ready', async () => {
    await withServer(async (server, client) => {
      mountJson(server, 'GET', `/ready`, 200, {"database":"example","status":"example"});
      await client.platform.ready();
    });
  });
  it('platform.mds_status', async () => {
    await withServer(async (server, client) => {
      mountJson(server, 'GET', `/api/v1/mds/status`, 200, {"entry_count":1,"stale":true});
      await client.platform.mdsStatus();
    });
  });
  it('platform.mds_refresh', async () => {
    await withServer(async (server, client) => {
      mountJson(server, 'POST', `/api/v1/mds/refresh`, 200, {"entry_count":1,"no":1,"outcome":"initial"});
      await client.platform.mdsRefresh();
    });
  });
});

/** §27.9: a partial regeneration must fail here, not ship 140 of 147. */
describe('generated surface', () => {
  it('covers exactly the operations the registry names', () => {
    const exercised = [
          "audit.list",
          "audit.list_system",
          "ca_certificates.generate",
          "ca_certificates.generate_signing_ca",
          "ca_certificates.get",
          "ca_certificates.import_ca",
          "ca_certificates.list",
          "ca_certificates.list_signing_cas",
          "ca_certificates.migrate_custody",
          "ca_certificates.revoke",
          "ca_certificates.set_mtls_trust_anchor",
          "ca_certificates.sign_signing_ca_csr",
          "certificates.generate",
          "certificates.get",
          "certificates.list",
          "certificates.revoke",
          "email_config.delete_org",
          "email_config.delete_tenant",
          "email_config.get_org",
          "email_config.get_tenant",
          "email_config.set_org",
          "email_config.set_tenant",
          "email_config.test_org",
          "email_config.test_tenant",
          "federation.create_config",
          "federation.delete_config",
          "federation.delete_link",
          "federation.get_config",
          "federation.list_configs",
          "federation.list_user_links",
          "federation.oidc_authorize",
          "federation.oidc_callback",
          "federation.update_config",
          "groups.add_member",
          "groups.add_service_account",
          "groups.create",
          "groups.delete",
          "groups.get",
          "groups.list",
          "groups.list_members",
          "groups.list_roles",
          "groups.list_service_accounts",
          "groups.remove_member",
          "groups.remove_service_account",
          "groups.update",
          "notification_rules.create",
          "notification_rules.delete",
          "notification_rules.get",
          "notification_rules.list",
          "notification_rules.update",
          "oauth2_clients.create",
          "oauth2_clients.delete",
          "oauth2_clients.get",
          "oauth2_clients.list",
          "oauth2_clients.update",
          "organizations.get",
          "organizations.list",
          "organizations.update",
          "permissions.create",
          "permissions.delete",
          "permissions.get",
          "permissions.list",
          "permissions.update",
          "pgp_keys.encrypt",
          "pgp_keys.generate",
          "pgp_keys.get",
          "pgp_keys.list",
          "pgp_keys.revoke",
          "pgp_keys.sign_audit_batch",
          "platform.health",
          "platform.mds_refresh",
          "platform.mds_status",
          "platform.ready",
          "privacy.cancel_delete",
          "privacy.download_export",
          "privacy.request_delete",
          "privacy.request_export",
          "reactors.create",
          "reactors.delete",
          "reactors.get",
          "reactors.list",
          "reactors.list_events",
          "reactors.update",
          "resources.create",
          "resources.delete",
          "resources.get",
          "resources.list",
          "resources.list_ancestors",
          "resources.list_children",
          "resources.update",
          "roles.assign_to_group",
          "roles.assign_to_service_account",
          "roles.assign_to_user",
          "roles.create",
          "roles.delete",
          "roles.get",
          "roles.grant_permission",
          "roles.list",
          "roles.list_groups",
          "roles.list_permissions",
          "roles.list_service_accounts",
          "roles.list_users",
          "roles.revoke_permission",
          "roles.unassign_from_group",
          "roles.unassign_from_service_account",
          "roles.unassign_from_user",
          "roles.update",
          "scim_tokens.create",
          "scim_tokens.list",
          "scim_tokens.revoke",
          "scopes.create",
          "scopes.delete",
          "scopes.get",
          "scopes.list",
          "scopes.update",
          "service_accounts.bind_certificate",
          "service_accounts.create",
          "service_accounts.delete",
          "service_accounts.get",
          "service_accounts.list",
          "service_accounts.list_groups",
          "service_accounts.list_roles",
          "service_accounts.rotate_secret",
          "service_accounts.update",
          "settings.delete_tenant_override",
          "settings.get_effective",
          "settings.get_org",
          "settings.get_tenant_override",
          "settings.set_effective",
          "settings.set_org",
          "settings.set_tenant_override",
          "tenants.create",
          "tenants.delete",
          "tenants.export_audit",
          "tenants.get",
          "tenants.list",
          "tenants.update",
          "users.create",
          "users.delete",
          "users.delete_mfa_method",
          "users.get",
          "users.list",
          "users.list_mfa_methods",
          "users.list_roles",
          "users.reset_mfa",
          "users.unlock",
          "users.update",
          "webauthn_policy.compliance_report",
          "webauthn_policy.get",
          "webauthn_policy.set",
          "webhooks.create",
          "webhooks.delete",
          "webhooks.get",
          "webhooks.list",
          "webhooks.update"
    ];
    expect(exercised).toEqual(expectedSurface());
  });
});
