// @generated by scripts/gen-management.mjs from management-registry.json and
// openapi.json. DO NOT EDIT — your changes will be overwritten. Regenerate with
// `node scripts/gen-management.mjs`; CI verifies the committed output is current.


/**
 * Request and response types for the CONTRACT §27 management surface.
 *
 * Three shapes recur and are worth knowing before reading:
 *
 * - **Sparse update bodies.** Every field is optional, and an omitted field is
 *   *absent from the wire body* rather than sent as `null` — so a body
 *   carrying one field changes one field (§27.4 rule 5). This SDK cannot
 *   express "set this field to null", which is the safe direction to be
 *   inexpressive in.
 * - **Replacement bodies.** `SetOrgSettings`, the organization email config,
 *   `WebauthnAttestationPolicy` and `SetMtlsTrustAnchor` have required
 *   fields, because a `PUT` on those routes replaces rather than patches.
 *   TypeScript will not let you build one half-filled, which is the point.
 * - **Types carrying a secret.** These hold a {@link Sensitive} and come with
 *   a private wire twin, because `Sensitive.toJSON()` returns
 *   `"[SENSITIVE]"` — serializing the public type directly would send the
 *   placeholder to the server, and deserializing into it would leave the
 *   secret an ordinary string.
 */
import { Sensitive } from '../core/sensitive.js';

/** `ActorType` (generated from openapi.json). */
export type ActorType =
  | "User"
  | "ServiceAccount"
  | "System";

/** `AddMemberRequest` (generated from openapi.json). */
export interface AddMemberRequest {
  /** `user_id`. */
  user_id: string;
}

/**
 * API-based provider configuration (SendGrid, Postmark, Resend, Brevo).
 *
 * `api_key` follows the same write-only + omit-preserving contract as
 * [`SmtpConfig::password`] (D-01/D-02).
 *
 * Every field is optional, so this is a **sparse** body: what you leave out
 * is left unchanged, and is omitted from the wire request entirely rather
 * than sent as `null` (§27.4 rule 5).
 */
export interface ApiProviderConfig {
  /** Override base URL (useful for testing / self-hosted instances). */
  api_url?: string | null;
}

/** `AssignRoleToGroupRequest` (generated from openapi.json). */
export interface AssignRoleToGroupRequest {
  /** `group_id`. */
  group_id: string;
  /** `resource_id`. */
  resource_id?: string | null;
}

/** `AssignRoleToUserRequest` (generated from openapi.json). */
export interface AssignRoleToUserRequest {
  /** `resource_id`. */
  resource_id?: string | null;
  /** `user_id`. */
  user_id: string;
}

/**
 * What attestation conveyance a registration ceremony requests, and whether
 * the policy is enforced at all.
 *
 * `None` is the default and reproduces today's behavior byte-for-byte:
 * `evaluate` allows every registration unconditionally, with no MDS lookup
 * (D8 step 1).
 */
export type AttestationMode =
  | "none"
  | "indirect"
  | "direct_required";

/** `AuditLogEntry` (generated from openapi.json). */
export interface AuditLogEntry {
  /** `action`. */
  action: string;
  /** `actor_id`. */
  actor_id: string;
  /** `actor_type`. */
  actor_type: ActorType;
  /** `id`. */
  id: string;
  /** `ip_address`. */
  ip_address?: string | null;
  /** `metadata`. */
  metadata: unknown;
  /** `outcome`. */
  outcome: AuditOutcome;
  /** `resource_id`. */
  resource_id?: string | null;
  /** `tenant_id`. */
  tenant_id: string;
  /** `timestamp`. */
  timestamp: string;
}

/** `AuditOutcome` (generated from openapi.json). */
export type AuditOutcome =
  | "Success"
  | "Failure"
  | "Denied";

/** Request to bind a certificate to a service account. */
export interface BindCertificate {
  /** `certificate_id`. */
  certificate_id: string;
}

/**
 * A CA (Certificate Authority) certificate at the organization level.
 *
 * CA certificates are the root of trust for all tenant certificates within
 * the organization. Private keys for signing CAs are encrypted with
 * AES-256-GCM and stored separately; non-signing CAs only store the public
 * certificate.
 */
export interface CaCertificate {
  /**
   * The issuers above [`Self::public_cert_pem`], concatenated PEM, nearest
   * issuer first and the root last.
   *
   * `None` for a CA that is its own root, which is every CA AXIAM generated
   * before Vault's PKI engine was an option. Present for a `vault_pki` CA,
   * where it is the only copy of the root certificate anything outside Vault
   * will ever see — a relying party cannot validate an AXIAM-issued leaf
   * without it, and `root/generate/internal` returns it exactly once.
   */
  chain_pem?: string | null;
  /** `created_at`. */
  created_at: string;
  /** SHA-256 fingerprint of the certificate. */
  fingerprint: string;
  /** `id`. */
  id: string;
  /** `key_algorithm`. */
  key_algorithm: KeyAlgorithm;
  /**
   * Which custodian holds this CA's signing key.
   *
   * Recorded per CA rather than read from configuration, so adopting a new
   * custodian does not strand the CAs that already exist. Not secret — an
   * operator needs to see it, and it discloses only where a key is kept.
   */
  key_custody?: string;
  /**
   * Where the custodian put the key. A Vault path under its mount; `None` for
   * database custody, whose locator is the row itself.
   */
  key_locator?: string | null;
  /**
   * Whether this CA is offered as a trust anchor for mutual TLS.
   *
   * When set, the server exports this CA's **public** certificate to the
   * bundle named by `AXIAM__SERVER__TLS__CLIENT_CA_BUNDLE_PATH` at startup and
   * turns client-certificate authentication on (`optional`) if the operator
   * has not configured it explicitly. A client presenting a certificate that
   * chains to this CA is then verified by the TLS layer itself, which is what
   * `axiam_pki::mtls` needs to authenticate an IoT device or a service account
   * by certificate rather than by secret.
   *
   * # What is and is not copied
   *
   * Only `public_cert_pem` — the certificate. The **private key stays where
   * its custodian put it** (Vault, or sealed into the row) and is never
   * written to the server volume. A trust anchor is public by construction: it
   * is what the server hands every client during the TLS handshake, and every
   * device that has to validate the chain already holds a copy.
   *
   * # Why a restart
   *
   * rustls builds its `RootCertStore` once, when the listener is constructed,
   * and actix-web binds that config for the process's life. Toggling this
   * changes what the *next* boot trusts, and the API says so in its response
   * rather than pretending the change took effect.
   *
   * Defaults to `false`, so a deployment that never touches this keeps exactly
   * the TLS posture it has today.
   */
  mtls_trust_anchor?: boolean;
  /** Validity end. */
  not_after: string;
  /** Validity start. */
  not_before: string;
  /** The organization this CA belongs to. */
  organization_id: string;
  /**
   * The CA in this organization that signed this one.
   *
   * `None` for an organization-level CA, which is either self-signed or
   * imported and has no parent inside AXIAM.
   */
  parent_ca_id?: string | null;
  /**
   * PEM-encoded public certificate.
   *
   * The certificate that *signs*, which under `vault_pki` custody is the
   * intermediate rather than the root beneath which it was created.
   */
  public_cert_pem: string;
  /** `status`. */
  status: CertificateStatus;
  /** The certificate subject (e.g., `CN=ACME Corp Root CA`). */
  subject: string;
  /**
   * The tenant this CA signs for, when it is a tenant signing CA.
   *
   * `None` for an organization-level CA — the trust anchor, and the only kind
   * that existed before tenant signing CAs. `Some` for an intermediate created
   * under one, which exists so a tenant's user, service and device
   * certificates chain through a CA that can be revoked and replaced without
   * touching the anchor the rest of the estate trusts.
   */
  tenant_id?: string | null;
}

/**
 * A tenant-level certificate for users, services, or IoT devices.
 *
 * Certificates are signed by the organization's CA. The private key is
 * returned once on generation and never stored by AXIAM.
 */
export interface Certificate {
  /** `cert_type`. */
  cert_type: CertificateType;
  /** `created_at`. */
  created_at: string;
  /** SHA-256 fingerprint of the certificate. */
  fingerprint: string;
  /** `id`. */
  id: string;
  /** The CA certificate that signed this certificate. */
  issuer_ca_id: string;
  /** `key_algorithm`. */
  key_algorithm: KeyAlgorithm;
  /** Arbitrary key-value metadata (e.g., device serial, user ID binding). */
  metadata: unknown;
  /** Validity end. */
  not_after: string;
  /** Validity start. */
  not_before: string;
  /** PEM-encoded public certificate. */
  public_cert_pem: string;
  /** `status`. */
  status: CertificateStatus;
  /** The certificate subject (e.g., `CN=device-001`). */
  subject: string;
  /** The tenant this certificate belongs to. */
  tenant_id: string;
}

/** Certificate issuance constraints. */
export interface CertificatePolicy {
  /** `default_cert_validity_days`. */
  default_cert_validity_days: number;
  /** `max_cert_validity_days`. */
  max_cert_validity_days: number;
}

/** Status of a certificate in its lifecycle. */
export type CertificateStatus =
  | "Active"
  | "Revoked"
  | "Expired";

/** The purpose for which a certificate was issued. */
export type CertificateType =
  | "User"
  | "Service"
  | "Device";

/**
 * FIDO certification level, as recorded in an MDS `statusReports` entry's
 * `FIDO_CERTIFIED*` status.
 *
 * Variant order is significant: `derive(PartialOrd, Ord)` gives `L1 < L1Plus
 * < L2 < L2Plus < L3 < L3Plus`, which `WebauthnAttestationPolicy::evaluate`
 * (D8 step 9) relies on directly for the `min_certification` boundary check
 * (`entry_level >= policy_min`).
 */
export type CertificationLevel =
  | "L1"
  | "L1Plus"
  | "L2"
  | "L2Plus"
  | "L3"
  | "L3Plus";

/**
 * How a client proves its identity at the token endpoint (RFC 8705 §2, OIDC
 * Core §9 naming).
 *
 * Only the methods AXIAM actually implements are representable. There is
 * deliberately no `none` variant: every AXIAM client is confidential today
 * (see `handle_authorization_code`), and adding a public-client value here
 * before the rest of the server understands one would let an operator
 * register a client whose authentication is silently skipped.
 */
export type ClientAuthMethod =
  | "client_secret_post"
  | "tls_client_auth"
  | "self_signed_tls_client_auth"
  | "private_key_jwt";

/**
 * Which security posture a client is registered under (X5.1).
 *
 * This is the FAPI "one switch". FAPI 2.0 is not a single feature but a
 * bundle of constraints — mandatory PAR, mandatory PKCE with `S256`,
 * mandatory strong client authentication, mandatory sender-constrained
 * tokens, and a refusal of every relaxation the base specs permit. Encoding
 * them as one profile rather than a dozen independent booleans means an
 * operator cannot register a client that is *nearly* FAPI, and a reviewer
 * can answer "is this client financial-grade?" by reading one field.
 *
 * The same philosophy as the rate-limit postures: ordinary clients see no
 * behaviour change at all, because [`Standard`](Self::Standard) is the serde
 * default and every row written before schema v38 decodes to it.
 */
export type ClientProfile =
  | "standard"
  | "fapi2";

/** One credential's compliance outcome (D9). */
export interface ComplianceReportEntry {
  /** `aaguid`. */
  aaguid?: string | null;
  /** `authenticator_name`. */
  authenticator_name?: string | null;
  /**
   * `false` only for a genuine policy violation
   * ([`ComplianceStatus::NonCompliant`]) — a credential with no recorded
   * AAGUID ([`ComplianceStatus::Unknown`], D9's pre-X3 case) is always `true`
   * here, never reported as a violation.
   */
  compliant: boolean;
  /** `credential_id`. */
  credential_id: string;
  /**
   * The credential's user-assigned name (`WebauthnCredential::name`), not the
   * owning user's account name.
   */
  name: string;
  /**
   * `None` only when `compliant` and the credential has a recorded AAGUID; set
   * for every non-compliant *and* every "unknown" (pre-X3) credential.
   */
  reason?: string | null;
  /** `user_id`. */
  user_id: string;
}

/** `CreateCaCertificateRequest` (generated from openapi.json). */
export interface CreateCaCertificateRequest {
  /**
   * Common name for the signing intermediate — `vault_pki` custody only.
   *
   * Under that custodian Vault generates a root and an intermediate beneath
   * it, and this names the second. Defaults to the root's subject with
   * `Intermediate Authority` appended. Ignored by every other custodian, which
   * produces one self-signed CA and has no second certificate to name.
   */
  intermediate_subject?: string | null;
  /** Validity of the signing intermediate, in days. Defaults to the root's. */
  intermediate_validity_days?: number | null;
  /**
   * Issue leaves straight from the generated root instead of creating an
   * intermediate. `vault_pki` custody only, and off by default.
   *
   * The default is the safer one: a root that signs only an intermediate can
   * have that intermediate revoked and replaced without redistributing the
   * trust anchor, and a root that signs leaves cannot.
   */
  issue_from_root?: boolean;
  /** `key_algorithm`. */
  key_algorithm: KeyAlgorithm;
  /** `subject`. */
  subject: string;
  /** Validity duration in days. */
  validity_days: number;
}

/** `CreateCertificateRequest` (generated from openapi.json). */
export interface CreateCertificateRequest {
  /** `cert_type`. */
  cert_type: CertificateType;
  /** `issuer_ca_id`. */
  issuer_ca_id: string;
  /** `key_algorithm`. */
  key_algorithm: KeyAlgorithm;
  /** `metadata`. */
  metadata?: unknown;
  /** `subject`. */
  subject: string;
  /** Validity duration in days. */
  validity_days: number;
}

/** `CreateFederationConfigRequest` (generated from openapi.json). */
export interface CreateFederationConfigRequest {
  /**
   * Accepted JWT signing algorithms (OIDC) or signature algorithms (SAML).
   * Defaults to `["RS256"]` when not provided (CQ-B40/REQ-14 AC-5).
   */
  allowed_algorithms?: string[] | null;
  /** Maps external IdP attributes to AXIAM user fields. */
  attribute_map?: unknown;
  /** OAuth2 client ID registered with the external IdP. */
  client_id: string;
  /**
   * OAuth2 client secret registered with the external IdP.
   *
   * **Secret.** Redacted from every string, log and JSON rendering; call
   * `.expose()` to read it.
   */
  client_secret: Sensitive<string>;
  /**
   * PEM-encoded X.509 certificate for verifying SAML assertions or OIDC
   * signatures (CQ-B40/REQ-14 AC-5). Required for SAML configs.
   */
  idp_signing_cert_pem?: string | null;
  /** OIDC discovery URL or SAML metadata URL. */
  metadata_url?: string | null;
  /** Federation protocol: "OidcConnect" or "Saml". */
  protocol: string;
  /** Display name for the identity provider (e.g., "Google", "Okta"). */
  provider: string;
  /** `token_exchange`. */
  token_exchange?: TokenExchangeTrustRequest | null;
}

/**
 * Wire twin of {@link CreateFederationConfigRequest} — plain strings, never
 * logged.
 */
export interface CreateFederationConfigRequestWire {
  allowed_algorithms?: string[] | null;
  attribute_map?: unknown;
  client_id: string;
  client_secret: string;
  idp_signing_cert_pem?: string | null;
  metadata_url?: string | null;
  protocol: string;
  provider: string;
  token_exchange?: TokenExchangeTrustRequest | null;
}

/**
 * Unwrap a `CreateFederationConfigRequest` for the wire.
 *
 * One of the two places a §27 secret is unwrapped, so that "put a secret on
 * the socket" stays a single greppable call rather than fourteen (§7 rule
 * 4).
 */
export function createFederationConfigRequestToWire(v: CreateFederationConfigRequest): CreateFederationConfigRequestWire {
  return {
    ...v,
    client_secret: v.client_secret.expose(),
  };
}

/** `CreateGroupRequest` (generated from openapi.json). */
export interface CreateGroupRequest {
  /** `description`. */
  description: string;
  /** `metadata`. */
  metadata?: unknown;
  /** `name`. */
  name: string;
}

/** Body of `POST .../tenants/{tenant_id}/signing-cas`. */
export interface CreateIntermediateCaRequest {
  /** `key_algorithm`. */
  key_algorithm: KeyAlgorithm;
  /** The organization CA that signs it. */
  parent_ca_id: string;
  /** Subject for the signing CA, e.g. `CN=ACME R&D Signing CA`. */
  subject: string;
  /** Validity duration in days, capped to the parent's own expiry. */
  validity_days: number;
}

/** `CreateNotificationRuleRequest` (generated from openapi.json). */
export interface CreateNotificationRuleRequest {
  /** Description of what this rule monitors. */
  description: string;
  /** Event types that trigger this rule. */
  events: NotificationEventType[];
  /** Human-readable name for the rule. */
  name: string;
  /** Email addresses to notify. */
  recipient_emails: string[];
}

/** `CreateOAuth2ClientRequest` (generated from openapi.json). */
export interface CreateOAuth2ClientRequest {
  /**
   * B5 — where OIDC back-channel logout tokens are delivered. Omit for a
   * client that does not participate.
   */
  backchannel_logout_uri?: string | null;
  /**
   * RFC 9449 §5.2 — issue DPoP-bound (sender-constrained) access tokens to
   * this client. Independent of both the authentication method and
   * `tls_client_certificate_bound_access_tokens`; a client may ask for both
   * constraints, and a token carrying both must satisfy both.
   */
  dpop_bound_access_tokens?: boolean;
  /**
   * RFC 9449 §8 — require this client's DPoP proofs to carry a server-issued
   * nonce.
   *
   * **Not implemented in this build (SEC-097).** `true` is refused with `400`;
   * only `false` (the default) is accepted. Nothing reads the stored value, so
   * accepting `true` would persist and echo back a security switch that does
   * nothing. DPoP proofs are made single-use at the token endpoint by `jti`
   * replay detection instead — see `docs/security-profiles.md`.
   */
  dpop_require_nonce?: boolean;
  /** Grant types this client is authorized to use. */
  grant_types: string[];
  /**
   * RFC 7591 §2 — the client's public key set, inline, for `private_key_jwt`.
   * Exactly one of `jwks` and `jwks_uri` may be set.
   */
  jwks?: string | null;
  /**
   * RFC 7591 §2 — where the client publishes its public key set. Must be an
   * absolute `https` URL, and is fetched through the SSRF-guarded JWKS cache,
   * which refuses private and loopback addresses.
   */
  jwks_uri?: string | null;
  /** Human-readable name for the client. */
  name: string;
  /**
   * B5 — allow-list for RP-initiated logout's `post_logout_redirect_uri`.
   * Separate from `redirect_uris` on purpose: that list receives authorization
   * codes, this one receives a browser after logout.
   */
  post_logout_redirect_uris?: string[];
  /**
   * X5.1 — the security posture this client is registered under.
   *
   * `"standard"` (the default) is every AXIAM client that has ever existed.
   * `"fapi2"` turns on the whole FAPI 2.0 constraint bundle at once, and the
   * registration is refused unless it also sets `require_par`, a strong
   * `token_endpoint_auth_method` (either mTLS method or `private_key_jwt`),
   * and at least one sender-constraining mechanism
   * (`tls_client_certificate_bound_access_tokens` or
   * `dpop_bound_access_tokens`). See the FAPI operator guide.
   */
  profile?: ClientProfile;
  /**
   * Allowed redirect URIs (must be HTTPS, except localhost for dev). SEC-089:
   * this list doubles as the token-exchange audience allow-list — adding a URI
   * here also authorises it as a token audience for this client, so review
   * additions on exchange-capable clients with that in mind (see
   * `docs/api/token-exchange.md#audience`).
   */
  redirect_uris: string[];
  /**
   * B5 — require this client to push its authorization parameters to
   * `/oauth2/par` (RFC 9126) rather than sending them through the browser.
   */
  require_par?: boolean;
  /** Scopes the client may request. */
  scopes: string[];
  /**
   * Accepted certificate thumbprints for `self_signed_tls_client_auth`, as
   * base64url-unpadded SHA-256 digests of the DER certificate (the same
   * `x5t#S256` encoding as the `cnf` claim). More than one permits an
   * overlapping rotation.
   */
  self_signed_tls_client_auth_thumbprints?: string[];
  /** RFC 8705 §2.1.2 — expected `dNSName` SAN. */
  tls_client_auth_san_dns?: string | null;
  /** RFC 8705 §2.1.2 — expected `uniformResourceIdentifier` SAN. */
  tls_client_auth_san_uri?: string | null;
  /**
   * RFC 8705 §2.1.2 — expected certificate subject DN, RFC 4514 form. Exactly
   * one of the three `tls_client_auth_*` parameters may be set.
   */
  tls_client_auth_subject_dn?: string | null;
  /**
   * RFC 8705 §3.4 — issue certificate-bound (sender-constrained) access tokens
   * to this client. Independent of the authentication method.
   */
  tls_client_certificate_bound_access_tokens?: boolean;
  /**
   * X5.1 — how this client authenticates at the token endpoint (RFC 8705 §2).
   * Defaults to `client_secret_post`.
   */
  token_endpoint_auth_method?: ClientAuthMethod;
}

/** `CreatePermissionRequest` (generated from openapi.json). */
export interface CreatePermissionRequest {
  /** `action`. */
  action: string;
  /** `description`. */
  description: string;
}

/** `CreatePgpKeyRequest` (generated from openapi.json). */
export interface CreatePgpKeyRequest {
  /** `algorithm`. */
  algorithm: PgpKeyAlgorithm;
  /** Email for the OpenPGP User ID. */
  email: string;
  /** `name`. */
  name: string;
  /** `purpose`. */
  purpose: PgpKeyPurpose;
}

/** `CreateReactorRequest` (generated from openapi.json). */
export interface CreateReactorRequest {
  /** `description`. */
  description?: string;
  /** `enabled`. */
  enabled?: boolean;
  /** Event names from the registry (`GET /api/v1/reactors/events`). */
  events: string[];
  /** `failure_policy`. */
  failure_policy?: FailurePolicy | null;
  /** `mode`. */
  mode: ReactorMode;
  /** `name`. */
  name: string;
  /** `priority`. */
  priority?: number;
  /** Omit to take the 500 ms default. Capped at 5 000 ms. */
  timeout_ms?: number | null;
}

/** `CreateResourceRequest` (generated from openapi.json). */
export interface CreateResourceRequest {
  /** `metadata`. */
  metadata?: unknown;
  /** `name`. */
  name: string;
  /** `parent_id`. */
  parent_id?: string | null;
  /** `resource_type`. */
  resource_type: string;
}

/** `CreateRoleRequest` (generated from openapi.json). */
export interface CreateRoleRequest {
  /** `description`. */
  description: string;
  /** `is_global`. */
  is_global: boolean;
  /** `name`. */
  name: string;
}

/** `CreateScimTokenRequest` (generated from openapi.json). */
export interface CreateScimTokenRequest {
  /**
   * Lifetime in days. Defaults to the deployment maximum, and is refused above
   * it.
   */
  expires_in_days?: number | null;
  /** Operator-facing label, e.g. `"okta-production"`. */
  name: string;
  /**
   * The tenant user the token authenticates as. Must already hold
   * `scim:provision` — see [`create`].
   */
  user_id: string;
}

/**
 * The one-time reveal. Same shape as service-account creation: the secret is
 * returned once and only its hash is kept.
 */
export interface CreateScimTokenResponse {
  /** `created_at`. */
  created_at: string;
  /** `created_by`. */
  created_by: string;
  /** `expires_at`. */
  expires_at: string;
  /** `id`. */
  id: string;
  /** `last_used_at`. */
  last_used_at?: string | null;
  /** `name`. */
  name: string;
  /**
   * The plaintext handle — shown once, never retrievable again.
   *
   * **Secret.** Redacted from every string, log and JSON rendering; call
   * `.expose()` to read it.
   */
  provisioning_token: Sensitive<string>;
  /** `revoked_at`. */
  revoked_at?: string | null;
  /** `status`. */
  status: ScimTokenStatus;
  /** `tenant_id`. */
  tenant_id: string;
  /** `user_id`. */
  user_id: string;
}

/**
 * Wire twin of {@link CreateScimTokenResponse} — plain strings, never
 * logged.
 */
export interface CreateScimTokenResponseWire {
  created_at: string;
  created_by: string;
  expires_at: string;
  id: string;
  last_used_at?: string | null;
  name: string;
  provisioning_token: string;
  revoked_at?: string | null;
  status: ScimTokenStatus;
  tenant_id: string;
  user_id: string;
}

/**
 * Wrap the secret fields a `CreateScimTokenResponse` response carries
 * (§27.5).
 */
export function createScimTokenResponseFromWire(w: CreateScimTokenResponseWire): CreateScimTokenResponse {
  return {
    ...w,
    provisioning_token: new Sensitive(w.provisioning_token),
  };
}

/** `CreateScopeRequest` (generated from openapi.json). */
export interface CreateScopeRequest {
  /** `description`. */
  description: string;
  /** `name`. */
  name: string;
}

/** `CreateServiceAccountRequest` (generated from openapi.json). */
export interface CreateServiceAccountRequest {
  /** Optional human-readable description of the account's purpose. */
  description?: string | null;
  /** `name`. */
  name: string;
}

/**
 * Request body for tenant creation (organization_id comes from the URL
 * path).
 */
export interface CreateTenantRequest {
  /** `metadata`. */
  metadata?: unknown;
  /** `name`. */
  name: string;
  /** `slug`. */
  slug: string;
}

/** `CreateUserRequest` (generated from openapi.json). */
export interface CreateUserRequest {
  /** `email`. */
  email: string;
  /** `metadata`. */
  metadata?: unknown;
  /** `opaque`. */
  opaque?: OpaqueEnrollment | null;
  /**
   * `password`.
   *
   * **Secret.** Redacted from every string, log and JSON rendering; call
   * `.expose()` to read it.
   */
  password: Sensitive<string>;
  /** `username`. */
  username: string;
}

/** Wire twin of {@link CreateUserRequest} — plain strings, never logged. */
export interface CreateUserRequestWire {
  email: string;
  metadata?: unknown;
  opaque?: OpaqueEnrollment | null;
  password: string;
  username: string;
}

/**
 * Unwrap a `CreateUserRequest` for the wire.
 *
 * One of the two places a §27 secret is unwrapped, so that "put a secret on
 * the socket" stays a single greppable call rather than fourteen (§7 rule
 * 4).
 */
export function createUserRequestToWire(v: CreateUserRequest): CreateUserRequestWire {
  return {
    ...v,
    password: v.password.expose(),
  };
}

/** `CreateWebhookRequest` (generated from openapi.json). */
export interface CreateWebhookRequest {
  /** Event types to subscribe to (e.g. `["user.created", "auth.login"]`). */
  events: string[];
  /** `retry_policy`. */
  retry_policy?: RetryPolicy | null;
  /**
   * HMAC-SHA256 shared secret for signing payloads.
   *
   * **Secret.** Redacted from every string, log and JSON rendering; call
   * `.expose()` to read it.
   */
  secret: Sensitive<string>;
  /** The HTTPS URL to deliver events to. */
  url: string;
}

/** Wire twin of {@link CreateWebhookRequest} — plain strings, never logged. */
export interface CreateWebhookRequestWire {
  events: string[];
  retry_policy?: RetryPolicy | null;
  secret: string;
  url: string;
}

/**
 * Unwrap a `CreateWebhookRequest` for the wire.
 *
 * One of the two places a §27 secret is unwrapped, so that "put a secret on
 * the socket" stays a single greppable call rather than fourteen (§7 rule
 * 4).
 */
export function createWebhookRequestToWire(v: CreateWebhookRequest): CreateWebhookRequestWire {
  return {
    ...v,
    secret: v.secret.expose(),
  };
}

/** Fully resolved email configuration (all fields present). */
export interface EmailConfig {
  /** `created_at`. */
  created_at: string;
  /** `enabled`. */
  enabled: boolean;
  /** `from_email`. */
  from_email: string;
  /** `from_name`. */
  from_name: string;
  /** `id`. */
  id: string;
  /** `provider`. */
  provider: ProviderConfig;
  /** `reply_to`. */
  reply_to?: string | null;
  /** `scope`. */
  scope: SettingsScope;
  /** The org_id or tenant_id this config belongs to. */
  scope_id: string;
  /** `updated_at`. */
  updated_at: string;
}

/**
 * Partial tenant overrides for email configuration. `None` = inherit from
 * org baseline.
 *
 * Every field is optional, so this is a **sparse** body: what you leave out
 * is left unchanged, and is omitted from the wire request entirely rather
 * than sent as `null` (§27.4 rule 5).
 */
export interface EmailConfigOverride {
  /** `enabled`. */
  enabled?: boolean | null;
  /** `from_email`. */
  from_email?: string | null;
  /** `from_name`. */
  from_name?: string | null;
  /** `provider`. */
  provider?: ProviderConfig | null;
  /** `Some(None)` explicitly clears reply-to; `None` inherits. */
  reply_to?: string | null;
}

/** What a test send did. */
export interface EmailTestResult {
  /** The provider's message id, when it returns one. */
  message_id?: string | null;
  /** Which provider the effective configuration resolved to. */
  provider: string;
  /** Where the message went — always the caller's own address. */
  to: string;
}

/** Email verification requirements. */
export interface EmailVerificationPolicy {
  /** `email_verification_grace_period_hours`. */
  email_verification_grace_period_hours: number;
  /** `email_verification_required`. */
  email_verification_required: boolean;
}

/** Request body for encrypting data. */
export interface EncryptRequest {
  /** Base64-encoded plaintext to encrypt. */
  data_base64: string;
}

/** Result of encrypting data with a PGP public key. */
export interface EncryptedExport {
  /** ASCII-armored PGP encrypted data. */
  ciphertext_armored: string;
  /** `recipient_key_id`. */
  recipient_key_id: string;
}

/**
 * What the server does when an interceptor does not produce a usable reply —
 * timeout, transport failure, bad signature, stale nonce, or a patch the
 * allow-list rejects.
 */
export type FailurePolicy =
  | "fail_closed"
  | "fail_open";

/** Federation config response -- omits client_secret. */
export interface FederationConfigResponse {
  /** `attribute_map`. */
  attribute_map: unknown;
  /** `client_id`. */
  client_id: string;
  /** `created_at`. */
  created_at: string;
  /** `enabled`. */
  enabled: boolean;
  /** `id`. */
  id: string;
  /** `metadata_url`. */
  metadata_url?: string | null;
  /** `protocol`. */
  protocol: string;
  /** `provider`. */
  provider: string;
  /** `tenant_id`. */
  tenant_id: string;
  /** X4 external token-exchange trust. */
  token_exchange: TokenExchangeTrustResponse;
  /** `updated_at`. */
  updated_at: string;
}

/** `FederationLinkResponse` (generated from openapi.json). */
export interface FederationLinkResponse {
  /** `created_at`. */
  created_at: string;
  /** `external_email`. */
  external_email?: string | null;
  /** `external_subject`. */
  external_subject: string;
  /** `federation_config_id`. */
  federation_config_id: string;
  /** `id`. */
  id: string;
  /** `tenant_id`. */
  tenant_id: string;
  /** `updated_at`. */
  updated_at: string;
  /** `user_id`. */
  user_id: string;
}

/**
 * Response returned when a CA certificate is generated.
 *
 * Includes the private key PEM, which is returned **once** and never stored
 * or retrievable again — when the custodian produced one at all. Under
 * `vault_pki` custody the key was born inside Vault and there is nothing to
 * return, which is the point of that custodian rather than a shortcoming of
 * this response.
 */
export interface GeneratedCaCertificate {
  /**
   * The issuers above [`Self::public_cert_pem`], concatenated PEM, nearest
   * issuer first and the root last.
   *
   * `None` for a CA that is its own root, which is every CA AXIAM generated
   * before Vault's PKI engine was an option. Present for a `vault_pki` CA,
   * where it is the only copy of the root certificate anything outside Vault
   * will ever see — a relying party cannot validate an AXIAM-issued leaf
   * without it, and `root/generate/internal` returns it exactly once.
   */
  chain_pem?: string | null;
  /** `created_at`. */
  created_at: string;
  /** SHA-256 fingerprint of the certificate. */
  fingerprint: string;
  /** `id`. */
  id: string;
  /** `key_algorithm`. */
  key_algorithm: KeyAlgorithm;
  /**
   * Which custodian holds this CA's signing key.
   *
   * Recorded per CA rather than read from configuration, so adopting a new
   * custodian does not strand the CAs that already exist. Not secret — an
   * operator needs to see it, and it discloses only where a key is kept.
   */
  key_custody?: string;
  /**
   * Where the custodian put the key. A Vault path under its mount; `None` for
   * database custody, whose locator is the row itself.
   */
  key_locator?: string | null;
  /**
   * Whether this CA is offered as a trust anchor for mutual TLS.
   *
   * When set, the server exports this CA's **public** certificate to the
   * bundle named by `AXIAM__SERVER__TLS__CLIENT_CA_BUNDLE_PATH` at startup and
   * turns client-certificate authentication on (`optional`) if the operator
   * has not configured it explicitly. A client presenting a certificate that
   * chains to this CA is then verified by the TLS layer itself, which is what
   * `axiam_pki::mtls` needs to authenticate an IoT device or a service account
   * by certificate rather than by secret.
   *
   * # What is and is not copied
   *
   * Only `public_cert_pem` — the certificate. The **private key stays where
   * its custodian put it** (Vault, or sealed into the row) and is never
   * written to the server volume. A trust anchor is public by construction: it
   * is what the server hands every client during the TLS handshake, and every
   * device that has to validate the chain already holds a copy.
   *
   * # Why a restart
   *
   * rustls builds its `RootCertStore` once, when the listener is constructed,
   * and actix-web binds that config for the process's life. Toggling this
   * changes what the *next* boot trusts, and the API says so in its response
   * rather than pretending the change took effect.
   *
   * Defaults to `false`, so a deployment that never touches this keeps exactly
   * the TLS posture it has today.
   */
  mtls_trust_anchor?: boolean;
  /** Validity end. */
  not_after: string;
  /** Validity start. */
  not_before: string;
  /** The organization this CA belongs to. */
  organization_id: string;
  /**
   * The CA in this organization that signed this one.
   *
   * `None` for an organization-level CA, which is either self-signed or
   * imported and has no parent inside AXIAM.
   */
  parent_ca_id?: string | null;
  /**
   * PEM-encoded private key — returned only on generation, and only when there
   * is one to return.
   *
   * Absent under `vault_pki` custody, where the key was generated inside Vault
   * and no API exports it. The field is omitted rather than sent as `null` so
   * a client that has always read it keeps working unchanged for every
   * custodian that does produce a key.
   *
   * **Secret.** Redacted from every string, log and JSON rendering; call
   * `.expose()` to read it.
   */
  private_key_pem?: Sensitive<string>;
  /**
   * PEM-encoded public certificate.
   *
   * The certificate that *signs*, which under `vault_pki` custody is the
   * intermediate rather than the root beneath which it was created.
   */
  public_cert_pem: string;
  /** `status`. */
  status: CertificateStatus;
  /** The certificate subject (e.g., `CN=ACME Corp Root CA`). */
  subject: string;
  /**
   * The tenant this CA signs for, when it is a tenant signing CA.
   *
   * `None` for an organization-level CA — the trust anchor, and the only kind
   * that existed before tenant signing CAs. `Some` for an intermediate created
   * under one, which exists so a tenant's user, service and device
   * certificates chain through a CA that can be revoked and replaced without
   * touching the anchor the rest of the estate trusts.
   */
  tenant_id?: string | null;
}

/** Wire twin of {@link GeneratedCaCertificate} — plain strings, never logged. */
export interface GeneratedCaCertificateWire {
  chain_pem?: string | null;
  created_at: string;
  fingerprint: string;
  id: string;
  key_algorithm: KeyAlgorithm;
  key_custody?: string;
  key_locator?: string | null;
  mtls_trust_anchor?: boolean;
  not_after: string;
  not_before: string;
  organization_id: string;
  parent_ca_id?: string | null;
  private_key_pem?: string;
  public_cert_pem: string;
  status: CertificateStatus;
  subject: string;
  tenant_id?: string | null;
}

/**
 * Wrap the secret fields a `GeneratedCaCertificate` response carries
 * (§27.5).
 */
export function generatedCaCertificateFromWire(w: GeneratedCaCertificateWire): GeneratedCaCertificate {
  return {
    ...w,
    private_key_pem: w.private_key_pem === undefined ? undefined : new Sensitive(w.private_key_pem),
  };
}

/**
 * Response returned when a tenant certificate is generated.
 *
 * Includes the private key PEM, returned **once** and never stored.
 */
export interface GeneratedCertificate {
  /** `cert_type`. */
  cert_type: CertificateType;
  /**
   * The issuing chain, concatenated PEM, nearest issuer first.
   *
   * Present only when the signer returned one — which is the `vault_pki` case,
   * where the root's certificate exists nowhere a client could fetch it from.
   * For a CA AXIAM signed with itself the chain is the CA certificate, which
   * `GET .../ca-certificates/{id}` already serves, so the field is omitted
   * rather than restating it.
   */
  chain_pem?: string | null;
  /** `created_at`. */
  created_at: string;
  /** SHA-256 fingerprint of the certificate. */
  fingerprint: string;
  /** `id`. */
  id: string;
  /** The CA certificate that signed this certificate. */
  issuer_ca_id: string;
  /** `key_algorithm`. */
  key_algorithm: KeyAlgorithm;
  /** Arbitrary key-value metadata (e.g., device serial, user ID binding). */
  metadata: unknown;
  /** Validity end. */
  not_after: string;
  /** Validity start. */
  not_before: string;
  /**
   * PEM-encoded private key — returned only on generation.
   *
   * **Secret.** Redacted from every string, log and JSON rendering; call
   * `.expose()` to read it.
   */
  private_key_pem: Sensitive<string>;
  /** PEM-encoded public certificate. */
  public_cert_pem: string;
  /** `status`. */
  status: CertificateStatus;
  /** The certificate subject (e.g., `CN=device-001`). */
  subject: string;
  /** The tenant this certificate belongs to. */
  tenant_id: string;
}

/** Wire twin of {@link GeneratedCertificate} — plain strings, never logged. */
export interface GeneratedCertificateWire {
  cert_type: CertificateType;
  chain_pem?: string | null;
  created_at: string;
  fingerprint: string;
  id: string;
  issuer_ca_id: string;
  key_algorithm: KeyAlgorithm;
  metadata: unknown;
  not_after: string;
  not_before: string;
  private_key_pem: string;
  public_cert_pem: string;
  status: CertificateStatus;
  subject: string;
  tenant_id: string;
}

/** Wrap the secret fields a `GeneratedCertificate` response carries (§27.5). */
export function generatedCertificateFromWire(w: GeneratedCertificateWire): GeneratedCertificate {
  return {
    ...w,
    private_key_pem: new Sensitive(w.private_key_pem),
  };
}

/** Response returned when a PGP key is generated. */
export interface GeneratedPgpKey {
  /** `algorithm`. */
  algorithm: PgpKeyAlgorithm;
  /** `created_at`. */
  created_at: string;
  /** OpenPGP key fingerprint (hex). */
  fingerprint: string;
  /** `id`. */
  id: string;
  /** `name`. */
  name: string;
  /**
   * ASCII-armored private key — returned only on generation for `Export` keys.
   * For `AuditSigning` keys this is `None` (private key is server-side only).
   *
   * **Secret.** Redacted from every string, log and JSON rendering; call
   * `.expose()` to read it.
   */
  private_key_armored?: Sensitive<string>;
  /** `public_key_armored`. */
  public_key_armored: string;
  /** `purpose`. */
  purpose: PgpKeyPurpose;
  /** `status`. */
  status: PgpKeyStatus;
  /** `tenant_id`. */
  tenant_id: string;
}

/** Wire twin of {@link GeneratedPgpKey} — plain strings, never logged. */
export interface GeneratedPgpKeyWire {
  algorithm: PgpKeyAlgorithm;
  created_at: string;
  fingerprint: string;
  id: string;
  name: string;
  private_key_armored?: string;
  public_key_armored: string;
  purpose: PgpKeyPurpose;
  status: PgpKeyStatus;
  tenant_id: string;
}

/** Wrap the secret fields a `GeneratedPgpKey` response carries (§27.5). */
export function generatedPgpKeyFromWire(w: GeneratedPgpKeyWire): GeneratedPgpKey {
  return {
    ...w,
    private_key_armored: w.private_key_armored === undefined ? undefined : new Sensitive(w.private_key_armored),
  };
}

/** `GrantPermissionRequest` (generated from openapi.json). */
export interface GrantPermissionRequest {
  /**
   * B1: `"allow"` (the default) or `"deny"`.
   *
   * A deny grant **overrides every allow**, at any depth of the resource
   * hierarchy and at equal specificity — it is not most-specific-wins. See
   * `claude_dev/deny-override-design.md` for the precedence table and for why
   * that trade was made.
   *
   * Omitting the field means `"allow"`, so every existing client keeps working
   * unchanged and no migration is required.
   */
  effect?: PermissionEffect;
  /** `permission_id`. */
  permission_id: string;
  /** `scope_ids`. */
  scope_ids?: string[];
}

/** A scope named by a grant, resolved to something a human can read. */
export interface GrantedScope {
  /** The scope's id, as it appears in the grant's `scope_ids`. */
  id: string;
  /** The scope's name, e.g. `invoices`. */
  name: string;
  /** The resource the scope belongs to. */
  resource_id: string;
}

/**
 * A group of users that can access resources based on their roles and
 * permissions. Groups simplify role management by allowing roles to be
 * assigned to a group rather than individual users.
 */
export interface Group {
  /** `created_at`. */
  created_at: string;
  /** `description`. */
  description: string;
  /** `id`. */
  id: string;
  /** `metadata`. */
  metadata: unknown;
  /** `name`. */
  name: string;
  /** `tenant_id`. */
  tenant_id: string;
  /** `updated_at`. */
  updated_at: string;
}

/** `HealthResponse` (generated from openapi.json). */
export interface HealthResponse {
  /** `status`. */
  status: string;
}

/**
 * Body of `POST /api/v1/organizations/{org_id}/ca-certificates/import`.
 *
 * Deliberately carries no subject, validity window or key algorithm: all
 * three are read out of the certificate itself. A caller that could name
 * them separately could name a subject the certificate does not have, and
 * AXIAM would enforce the claim while every relying party read the
 * certificate.
 */
export interface ImportCaCertificateRequest {
  /**
   * PEM-encoded private key, if AXIAM is to take custody of it.
   *
   * Omit it to register the certificate as a trust anchor only. Write-only: it
   * goes to the configured custodian on the way in and no endpoint returns it.
   *
   * **Secret.** Redacted from every string, log and JSON rendering; call
   * `.expose()` to read it.
   */
  private_key_pem?: Sensitive<string>;
  /** PEM-encoded CA certificate. */
  public_cert_pem: string;
}

/**
 * Wire twin of {@link ImportCaCertificateRequest} — plain strings, never
 * logged.
 */
export interface ImportCaCertificateRequestWire {
  private_key_pem?: string;
  public_cert_pem: string;
}

/**
 * Unwrap a `ImportCaCertificateRequest` for the wire.
 *
 * One of the two places a §27 secret is unwrapped, so that "put a secret on
 * the socket" stays a single greppable call rather than fourteen (§7 rule
 * 4).
 */
export function importCaCertificateRequestToWire(v: ImportCaCertificateRequest): ImportCaCertificateRequestWire {
  return {
    ...v,
    private_key_pem: v.private_key_pem === undefined ? undefined : v.private_key_pem.expose(),
  };
}

/** The type of key algorithm used for a certificate. */
export type KeyAlgorithm =
  | "Rsa4096"
  | "Ed25519";

/** Account lockout rules. */
export interface LockoutPolicy {
  /** `lockout_backoff_multiplier`. */
  lockout_backoff_multiplier: number;
  /** `lockout_duration_secs`. */
  lockout_duration_secs: number;
  /** `max_failed_login_attempts`. */
  max_failed_login_attempts: number;
  /** `max_lockout_duration_secs`. */
  max_lockout_duration_secs: number;
}

/**
 * `POST /api/v1/mds/refresh` response — the outcome of one ingestion attempt
 * (mirrors `axiam_db::mds_ingest::MdsIngestOutcome`).
 */
export type MdsRefreshOutcome =
  | { outcome: "initial"; entry_count: number; no: number }
  | { outcome: "replaced"; entry_count: number; no: number }
  | { outcome: "no_op_refresh"; no: number }
  | { outcome: "rollback_rejected"; attempted_no: number; stored_no: number };

/**
 * `GET /api/v1/mds/status` response. `no`/`next_update`/`last_refreshed_at`
 * are `None` and `stale` is `false` when MDS has never been ingested — a
 * meaningful, valid answer ("nothing ingested yet"), not an error.
 */
export interface MdsStatusResponse {
  /** `entry_count`. */
  entry_count: number;
  /** `last_refreshed_at`. */
  last_refreshed_at?: string | null;
  /** `next_update`. */
  next_update?: string | null;
  /** `no`. */
  no?: number | null;
  /** `stale`. */
  stale: boolean;
}

/** `MfaMethodResponse` (generated from openapi.json). */
export interface MfaMethodResponse {
  /** `created_at`. */
  created_at: string;
  /** `last_used_at`. */
  last_used_at?: string | null;
  /** `method_id`. */
  method_id: string;
  /** `method_type`. */
  method_type: MfaMethodType;
  /** `name`. */
  name: string;
}

/** Type of MFA method. */
export type MfaMethodType =
  | "Totp"
  | "Passkey"
  | "SecurityKey";

/** Multi-factor authentication policy. */
export interface MfaPolicy {
  /** `mfa_challenge_lifetime_secs`. */
  mfa_challenge_lifetime_secs: number;
  /** `mfa_enforced`. */
  mfa_enforced: boolean;
}

/** What a custody migration did. */
export interface MigrateCustodyResponse {
  /** The CA whose key moved. */
  ca_certificate_id: string;
  /** Where it is now. */
  key_custody: string;
  /** Where the new custodian filed it, when the custodian has a path. */
  key_locator?: string | null;
  /** Where the key was. */
  previous_custody: string;
}

/** The acknowledgement, which is mostly about the restart. */
export interface MtlsTrustAnchorResponse {
  /** The CA this is about. */
  ca_certificate_id: string;
  /** A sentence an operator can act on, rather than a bare boolean. */
  message: string;
  /** The flag as now stored. */
  mtls_trust_anchor: boolean;
  /**
   * Always `true`: rustls builds its client trust store once, when the
   * listener is constructed, so this takes effect at the next start.
   */
  restart_required: boolean;
}

/** Events that can trigger an admin notification. */
export type NotificationEventType =
  | "login_failure"
  | "account_locked"
  | "mfa_enrollment_changed"
  | "password_changed"
  | "password_reset_requested"
  | "role_assigned"
  | "role_unassigned"
  | "permission_granted"
  | "permission_revoked"
  | "certificate_issued"
  | "certificate_revoked"
  | "ca_certificate_revoked"
  | "user_created"
  | "user_deleted"
  | "user_updated"
  | "service_account_created"
  | "service_account_deleted";

/** Admin notification preferences. */
export interface NotificationPolicy {
  /** `admin_notifications_enabled`. */
  admin_notifications_enabled: boolean;
}

/** Notification rule response. */
export interface NotificationRuleResponse {
  /** `created_at`. */
  created_at: string;
  /** `description`. */
  description: string;
  /** `enabled`. */
  enabled: boolean;
  /** `events`. */
  events: NotificationEventType[];
  /** `id`. */
  id: string;
  /** `name`. */
  name: string;
  /** `recipient_emails`. */
  recipient_emails: string[];
  /** `tenant_id`. */
  tenant_id: string;
  /** `updated_at`. */
  updated_at: string;
}

/** Response for client creation -- includes the one-time plaintext secret. */
export interface OAuth2ClientCreatedResponse {
  /** `client_id`. */
  client_id: string;
  /**
   * `client_secret`.
   *
   * **Secret.** Redacted from every string, log and JSON rendering; call
   * `.expose()` to read it.
   */
  client_secret: Sensitive<string>;
  /** `created_at`. */
  created_at: string;
  /** `grant_types`. */
  grant_types: string[];
  /** `id`. */
  id: string;
  /** `name`. */
  name: string;
  /** `redirect_uris`. */
  redirect_uris: string[];
  /** `scopes`. */
  scopes: string[];
  /** `tenant_id`. */
  tenant_id: string;
  /** `updated_at`. */
  updated_at: string;
}

/**
 * Wire twin of {@link OAuth2ClientCreatedResponse} — plain strings, never
 * logged.
 */
export interface OAuth2ClientCreatedResponseWire {
  client_id: string;
  client_secret: string;
  created_at: string;
  grant_types: string[];
  id: string;
  name: string;
  redirect_uris: string[];
  scopes: string[];
  tenant_id: string;
  updated_at: string;
}

/**
 * Wrap the secret fields a `OAuth2ClientCreatedResponse` response carries
 * (§27.5).
 */
export function oAuth2ClientCreatedResponseFromWire(w: OAuth2ClientCreatedResponseWire): OAuth2ClientCreatedResponse {
  return {
    ...w,
    client_secret: new Sensitive(w.client_secret),
  };
}

/** OAuth2 client response -- omits client_secret_hash. */
export interface OAuth2ClientResponse {
  /** `client_id`. */
  client_id: string;
  /** `created_at`. */
  created_at: string;
  /** `dpop_bound_access_tokens`. */
  dpop_bound_access_tokens: boolean;
  /** `dpop_require_nonce`. */
  dpop_require_nonce: boolean;
  /** `grant_types`. */
  grant_types: string[];
  /** `id`. */
  id: string;
  /**
   * X5.1 — echoed so an operator can confirm which key source is registered.
   * The document itself is public key material, so returning it leaks nothing;
   * a `jwks_uri` is likewise public by construction.
   */
  jwks?: string | null;
  /** `jwks_uri`. */
  jwks_uri?: string | null;
  /** `name`. */
  name: string;
  /**
   * X5.1 — the registered posture and mTLS credentials. Read-back matters: an
   * operator auditing which clients are financial-grade should be able to
   * answer it from this endpoint rather than from the database.
   */
  profile: ClientProfile;
  /** `redirect_uris`. */
  redirect_uris: string[];
  /** `require_par`. */
  require_par: boolean;
  /** `scopes`. */
  scopes: string[];
  /** `self_signed_tls_client_auth_thumbprints`. */
  self_signed_tls_client_auth_thumbprints: string[];
  /** `tenant_id`. */
  tenant_id: string;
  /** `tls_client_auth_san_dns`. */
  tls_client_auth_san_dns?: string | null;
  /** `tls_client_auth_san_uri`. */
  tls_client_auth_san_uri?: string | null;
  /** `tls_client_auth_subject_dn`. */
  tls_client_auth_subject_dn?: string | null;
  /** `tls_client_certificate_bound_access_tokens`. */
  tls_client_certificate_bound_access_tokens: boolean;
  /** `token_endpoint_auth_method`. */
  token_endpoint_auth_method: ClientAuthMethod;
  /** `updated_at`. */
  updated_at: string;
}

/** `OidcAuthorizeRequest` (generated from openapi.json). */
export interface OidcAuthorizeRequest {
  /** ID of the federation config to use. */
  config_id: string;
  /** Nonce for replay protection (generated by the caller). */
  nonce: string;
  /** Redirect URI the external IdP should return the user to. */
  redirect_uri: string;
  /** CSRF state value (generated by the caller). */
  state: string;
}

/** `OidcAuthorizeResponse` (generated from openapi.json). */
export interface OidcAuthorizeResponse {
  /** The full authorization URL to redirect the user to. */
  url: string;
}

/** `OidcCallbackRequest` (generated from openapi.json). */
export interface OidcCallbackRequest {
  /** Authorization code returned by the external IdP. */
  code: string;
  /** ID of the federation config used in the authorization request. */
  config_id: string;
  /**
   * Client-supplied nonce (SECHRD-07/D-04: retained for backward compatibility
   * with older callers, but IGNORED for verification — `expected_nonce` always
   * comes from the server-side `FederationLoginState` row looked up via
   * `state`, never from this field).
   */
  nonce: string;
  /** Redirect URI that was used in the authorization request. */
  redirect_uri: string;
  /**
   * CSRF state value from the authorization request. Used to look up the
   * server-side `FederationLoginState` row that holds the real nonce
   * (SECHRD-07/D-04) — required so the callback can find its login state.
   */
  state: string;
}

/** `OidcCallbackResponse` (generated from openapi.json). */
export interface OidcCallbackResponse {
  /** `federation_link_id`. */
  federation_link_id: string;
  /** `newly_provisioned`. */
  newly_provisioned: boolean;
  /** `user_id`. */
  user_id: string;
}

/**
 * The client-supplied half of an OPAQUE enrolment, as it appears inside
 * registration / change-password / reset-completion / bootstrap request
 * bodies.
 *
 * There is no standalone `register/finish` endpoint, deliberately. A record
 * can only be created at a moment when the plaintext password legitimately
 * exists on the client, and every one of those moments is already an
 * endpoint that takes a password. A free-standing finish would be an
 * endpoint whose only job is to attach a credential to an account, which is
 * a thing worth not having.
 *
 * Kept separate from [`CreateOpaqueCredential`] because the tenant, the user
 * and the credential identifier are all decided by the server — a client
 * that could name them could enrol a record against somebody else's account.
 */
export interface OpaqueEnrollment {
  /** The `opaque_session` from the register/start response, echoed verbatim. */
  opaque_session: string;
  /** Lowercase-hex serialized RFC 9807 `RegistrationRecord`. */
  registration_record: string;
}

/**
 * Secure Remote Password policy.
 *
 * `suite` and `ksf` are the parameters a *new* registration record is
 * enrolled with. They deliberately do not apply retroactively: an existing
 * record is only valid under the suite and KSF it was created with, so
 * tightening these takes effect as users next set a password rather than
 * invalidating everybody at once.
 */
export interface OpaquePolicy {
  /**
   * Key-stretching function new records are enrolled under. Both variants are
   * memory-hard; see [`opaque_ksf_is_at_least`] for the tighten-only ordering.
   */
  opaque_ksf: string;
  /** Whether OPAQUE is offered, and whether password login is still accepted. */
  opaque_mode: string;
  /** RFC 9807 ciphersuite new records are enrolled under. */
  opaque_suite: string;
}

/**
 * An organization groups multiple tenants under a single administrative
 * entity.
 *
 * Organizations represent companies, departments, or business units. CA
 * certificates are registered at the organization level, enabling a
 * hierarchical trust model across all tenants.
 */
export interface Organization {
  /** `created_at`. */
  created_at: string;
  /** `id`. */
  id: string;
  /** Arbitrary key-value metadata. */
  metadata: unknown;
  /** Human-readable name. */
  name: string;
  /** URL-safe unique identifier (e.g., `acme-corp`). */
  slug: string;
  /** `updated_at`. */
  updated_at: string;
}

/** Password complexity and history requirements. */
export interface PasswordPolicy {
  /** `hibp_check_enabled`. */
  hibp_check_enabled: boolean;
  /** `min_length`. */
  min_length: number;
  /** `password_history_count`. */
  password_history_count: number;
  /** `require_digits`. */
  require_digits: boolean;
  /** `require_lowercase`. */
  require_lowercase: boolean;
  /** `require_symbols`. */
  require_symbols: boolean;
  /** `require_uppercase`. */
  require_uppercase: boolean;
}

/** `Permission` (generated from openapi.json). */
export interface Permission {
  /** The action this permission represents (e.g., `read`, `write`, `delete`). */
  action: string;
  /** `created_at`. */
  created_at: string;
  /** `description`. */
  description: string;
  /** `id`. */
  id: string;
  /** `tenant_id`. */
  tenant_id: string;
  /** `updated_at`. */
  updated_at: string;
}

/**
 * Whether a grant permits an action or refuses it (B1, deny-override).
 *
 * # Precedence
 *
 * Default deny -> an [`PermissionEffect::Allow`] grant permits -> a
 * [`PermissionEffect::Deny`] grant refuses, **and beats every allow**,
 * wherever either sits in the resource hierarchy. Deny wins; there is no
 * most-specific-wins tie-break.
 *
 * That choice is deliberate and is argued in full in
 * `claude_dev/deny-override-design.md` §2.1. The short version:
 * deny-override buys one checkable property — **adding a deny rule can never
 * widen access, and can never be undone by adding allows** — and
 * most-specific-wins buys expressiveness at the cost of making "is X
 * denied?" unanswerable without enumerating every other rule that might
 * out-specify it.
 *
 * [`PermissionEffect::Allow`] is the default, so data written before this
 * existed, and clients that send no `effect`, both mean "allow". No
 * migration.
 */
export type PermissionEffect =
  | "allow"
  | "deny";

/** An OpenPGP key stored by AXIAM. */
export interface PgpKey {
  /** `algorithm`. */
  algorithm: PgpKeyAlgorithm;
  /** `created_at`. */
  created_at: string;
  /** OpenPGP key fingerprint (hex). */
  fingerprint: string;
  /** `id`. */
  id: string;
  /** `name`. */
  name: string;
  /** `public_key_armored`. */
  public_key_armored: string;
  /** `purpose`. */
  purpose: PgpKeyPurpose;
  /** `status`. */
  status: PgpKeyStatus;
  /** `tenant_id`. */
  tenant_id: string;
}

/** Key algorithm for OpenPGP keys. */
export type PgpKeyAlgorithm =
  | "Rsa4096"
  | "Ed25519";

/** The purpose of an OpenPGP key. */
export type PgpKeyPurpose =
  | "AuditSigning"
  | "Export";

/** Status of an OpenPGP key. */
export type PgpKeyStatus =
  | "Active"
  | "Revoked";

/**
 * `GET` response: the stored policy plus the unknown-AAGUID action it
 * currently *resolves to*.
 *
 * `unknown_aaguid` is nullable, where `null` means "use this mode's default"
 * (deny under `direct_required`, allow otherwise). A client that only saw
 * the stored `null` would have to re-derive that rule itself to display what
 * the policy actually does — and a security rule implemented twice is a
 * security rule that will eventually disagree with itself. So the server
 * resolves it once, here, and reports both: the admin's stored intent and
 * its effect.
 */
export interface PolicyResponse {
  /**
   * `None` = every AAGUID is allowed except `blocked_aaguids`.
   *
   * `Some(vec![])` is a deliberate "nothing may register" policy and is
   * accepted as such: `evaluate` denies every AAGUID against an empty
   * allow-list. Nothing rejects it, precisely because the failure direction is
   * safe — a client that sends `[]` when it meant `null` gets a locked-down
   * tenant, which is visible immediately, rather than an open one, which is
   * not.
   */
  allowed_aaguids?: string[] | null;
  /**
   * Deny registration if the MDS entry has ever reported `REVOKED` or any
   * `*_COMPROMISE` status (sticky — D8 step 7).
   */
  block_revoked_status: boolean;
  /** `blocked_aaguids`. */
  blocked_aaguids?: string[];
  /**
   * The action actually applied to an AAGUID with no MDS metadata, with
   * `unknown_aaguid: null` resolved against `mode`. Read-only — `PUT` ignores
   * it.
   */
  effective_unknown_aaguid: UnknownAaguidAction;
  /** `min_certification`. */
  min_certification?: CertificationLevel | null;
  /** `mode`. */
  mode: AttestationMode;
  /**
   * Require *some* `FIDO_CERTIFIED*` status, any level. Independent of (and
   * checked before) `min_certification`.
   */
  require_fido_certified: boolean;
  /** `unknown_aaguid`. */
  unknown_aaguid?: UnknownAaguidAction | null;
}

/** Data-retention rules that apply after a subject asks to be erased. */
export interface PrivacyPolicy {
  /**
   * How long a requested account erasure stays cancellable before the purge
   * runs, in days.
   *
   * The window exists so an erasure triggered by mistake, or under coercion,
   * can be undone — `POST /api/v1/auth/account/delete/cancel` works for
   * exactly this long. It was fixed at 30 days in the handler, which meant the
   * "cancel a pending deletion" control in the admin UI referred to a duration
   * no operator could see or change.
   *
   * Shorter is the more restrictive direction, so a tenant may lower it and
   * not raise it: it is time spent holding data the subject has already asked
   * to have erased, and GDPR Art. 17(1) asks for that to be "without undue
   * delay". The upper bound of 90 days is where Art. 12(3)'s one-month
   * response deadline plus its two-month extension for complex cases runs out;
   * anything past 30 wants a reason recorded.
   */
  deletion_grace_period_days: number;
}

/** Provider-specific connection details. */
export type ProviderConfig =
  | ({ kind: "smtp" } & SmtpConfig)
  | ({ kind: "send_grid" } & ApiProviderConfig)
  | ({ kind: "postmark" } & ApiProviderConfig)
  | ({ kind: "resend" } & ApiProviderConfig)
  | ({ kind: "brevo" } & ApiProviderConfig);

/** One hookable event, as the registry describes it. */
export interface ReactorEventDescriptor {
  /** `default_failure_policy`. */
  default_failure_policy: FailurePolicy;
  /** `description`. */
  description: string;
  /** `interceptable`. */
  interceptable: boolean;
  /** `mutable`. */
  mutable: boolean;
  /**
   * Exact field names, or a namespace prefix ending in `.` — `ext.` admits
   * `ext.department` and nothing outside the namespace.
   */
  mutable_fields: string[];
  /** `name`. */
  name: string;
}

/** How a reactor participates in an event. */
export type ReactorMode =
  | "intercept"
  | "listen";

/** `ReactorResponse` (generated from openapi.json). */
export interface ReactorResponse {
  /** `created_at`. */
  created_at: string;
  /** `description`. */
  description: string;
  /** `enabled`. */
  enabled: boolean;
  /** `events`. */
  events: string[];
  /** `failure_policy`. */
  failure_policy: FailurePolicy;
  /** `id`. */
  id: string;
  /**
   * When this reactor last consumed from its queue. `null` means it has never
   * connected — which the admin UI shows differently from "connected once,
   * silent since".
   */
  last_seen_at?: string | null;
  /** `mode`. */
  mode: ReactorMode;
  /** `name`. */
  name: string;
  /** `priority`. */
  priority: number;
  /**
   * R2.3: dispatch failures against this registration in the last 24h whose
   * cause was a timeout (as opposed to a rejected reply, a transport failure,
   * or overload), capped at 100 — a health signal read from the audit trail
   * R2.2 started writing, not a replacement for the audit log itself (`GET
   * /api/v1/audit-log` is that).
   */
  recent_timeout_count: number;
  /**
   * R2.3: operations this reactor's own reply *denied* in the last 24h, capped
   * at 100. Distinct from `recent_timeout_count`: a veto is the reactor
   * working as designed; a timeout is the reactor not answering.
   */
  recent_veto_count: number;
  /** `tenant_id`. */
  tenant_id: string;
  /** `timeout_ms`. */
  timeout_ms: number;
  /** `updated_at`. */
  updated_at: string;
}

/** `ReadyResponse` (generated from openapi.json). */
export interface ReadyResponse {
  /** `database`. */
  database: string;
  /** `status`. */
  status: string;
}

/**
 * A permission grant with its scopes resolved.
 *
 * A superset of [`PermissionGrant`]: `scope_ids` is still present and still
 * authoritative, so a client written before `scopes` existed is unaffected.
 */
export interface ResolvedPermissionGrant {
  /** Whether the grant permits or refuses. */
  effect: PermissionEffect;
  /** The permission this grant is about. */
  permission: Permission;
  /** The scope ids the grant is constrained to. Empty is the wildcard. */
  scope_ids: string[];
  /**
   * The scopes `scope_ids` names, in the same order where resolvable.
   *
   * A scope that cannot be resolved is **omitted** rather than represented by
   * a placeholder, so this can be shorter than `scope_ids`. That happens when
   * a scope was deleted while a grant still referenced it, and showing a name
   * for something that no longer exists would be worse than showing one fewer
   * chip beside a count that still says how many ids the grant carries.
   */
  scopes: GrantedScope[];
}

/** `Resource` (generated from openapi.json). */
export interface Resource {
  /** `created_at`. */
  created_at: string;
  /** `id`. */
  id: string;
  /** `metadata`. */
  metadata: unknown;
  /** `name`. */
  name: string;
  /**
   * Parent resource ID for hierarchical organization. `None` for root
   * resources.
   */
  parent_id?: string | null;
  /** The type of resource (e.g., `project`, `service`, `endpoint`). */
  resource_type: string;
  /** `tenant_id`. */
  tenant_id: string;
  /**
   * The `client_id` that registered this resource through the UMA Protection
   * API (X2), or `None` for a resource created any other way.
   *
   * Read-only from every ordinary path: [`UpdateResource`] cannot set it and
   * [`CreateResource`] cannot either, so the only writer is the
   * resource-registration handler. That is deliberate — the field backs a
   * provenance badge in the admin UI, and a provenance marker anyone can write
   * is decoration that reads like evidence.
   */
  uma_registered_by?: string | null;
  /** `updated_at`. */
  updated_at: string;
}

/** Retry policy for failed webhook deliveries. */
export interface RetryPolicy {
  /** Multiplier for exponential backoff. */
  backoff_multiplier: number;
  /** Initial delay between retries in seconds. */
  initial_delay_secs: number;
  /** Maximum number of retry attempts. */
  max_retries: number;
}

/** `Role` (generated from openapi.json). */
export interface Role {
  /** `created_at`. */
  created_at: string;
  /** `description`. */
  description: string;
  /** `id`. */
  id: string;
  /** Global roles grant permissions across all resources. */
  is_global: boolean;
  /** `name`. */
  name: string;
  /** `tenant_id`. */
  tenant_id: string;
  /** `updated_at`. */
  updated_at: string;
}

/**
 * A role together with its assignment context (the resource it is scoped
 * to).
 */
export interface RoleAssignment {
  /** `None` means the role was assigned globally (no resource scope). */
  resource_id?: string | null;
  /** `role`. */
  role: Role;
}

/** A group together with the resource scope of its assignment of this role. */
export interface RoleGroupAssignment {
  /** The assigned group. */
  group: Group;
  /** `None` means the role was assigned globally (no resource scope). */
  resource_id?: string | null;
}

/** A user together with the resource scope of their assignment of this role. */
export interface RoleUserAssignment {
  /** `None` means the role was assigned globally (no resource scope). */
  resource_id?: string | null;
  /** The assigned user. */
  user: UserResponse;
}

/** Response for secret rotation. */
export interface RotateSecretResponse {
  /**
   * `client_secret`.
   *
   * **Secret.** Redacted from every string, log and JSON rendering; call
   * `.expose()` to read it.
   */
  client_secret: Sensitive<string>;
}

/** Wire twin of {@link RotateSecretResponse} — plain strings, never logged. */
export interface RotateSecretResponseWire {
  client_secret: string;
}

/** Wrap the secret fields a `RotateSecretResponse` response carries (§27.5). */
export function rotateSecretResponseFromWire(w: RotateSecretResponseWire): RotateSecretResponse {
  return {
    ...w,
    client_secret: new Sensitive(w.client_secret),
  };
}

/**
 * Metadata only. The handle is never in a list response — it exists in
 * plaintext exactly once, in [`CreateScimTokenResponse`].
 */
export interface ScimTokenResponse {
  /** `created_at`. */
  created_at: string;
  /** `created_by`. */
  created_by: string;
  /** `expires_at`. */
  expires_at: string;
  /** `id`. */
  id: string;
  /** `last_used_at`. */
  last_used_at?: string | null;
  /** `name`. */
  name: string;
  /** `revoked_at`. */
  revoked_at?: string | null;
  /** `status`. */
  status: ScimTokenStatus;
  /** `tenant_id`. */
  tenant_id: string;
  /** `user_id`. */
  user_id: string;
}

/**
 * Why a token is or is not currently usable — for display only. The
 * authentication path never surfaces this distinction on the wire.
 */
export type ScimTokenStatus =
  | "active"
  | "expired"
  | "revoked";

/** `Scope` (generated from openapi.json). */
export interface Scope {
  /** `created_at`. */
  created_at: string;
  /** `description`. */
  description: string;
  /** `id`. */
  id: string;
  /** `name`. */
  name: string;
  /** The resource this scope belongs to. */
  resource_id: string;
  /** `tenant_id`. */
  tenant_id: string;
  /** `updated_at`. */
  updated_at: string;
}

/** Fully resolved security settings (all fields present). */
export interface SecuritySettings {
  /** `certificate`. */
  certificate: CertificatePolicy;
  /** `created_at`. */
  created_at: string;
  /** `email`. */
  email: EmailVerificationPolicy;
  /** `id`. */
  id: string;
  /** `lockout`. */
  lockout: LockoutPolicy;
  /** `mfa`. */
  mfa: MfaPolicy;
  /** `notification`. */
  notification: NotificationPolicy;
  /** `opaque`. */
  opaque: OpaquePolicy;
  /** `password`. */
  password: PasswordPolicy;
  /** `privacy`. */
  privacy: PrivacyPolicy;
  /** `scope`. */
  scope: SettingsScope;
  /** `scope_id`. */
  scope_id: string;
  /** `token`. */
  token: TokenPolicy;
  /** `updated_at`. */
  updated_at: string;
}

/**
 * Response for service account creation — includes the one-time plaintext
 * secret.
 */
export interface ServiceAccountCreatedResponse {
  /** `client_id`. */
  client_id: string;
  /**
   * `client_secret`.
   *
   * **Secret.** Redacted from every string, log and JSON rendering; call
   * `.expose()` to read it.
   */
  client_secret: Sensitive<string>;
  /** `created_at`. */
  created_at: string;
  /** `description`. */
  description?: string | null;
  /** `id`. */
  id: string;
  /** `name`. */
  name: string;
  /** `status`. */
  status: UserStatus;
  /** `tenant_id`. */
  tenant_id: string;
  /** `updated_at`. */
  updated_at: string;
}

/**
 * Wire twin of {@link ServiceAccountCreatedResponse} — plain strings, never
 * logged.
 */
export interface ServiceAccountCreatedResponseWire {
  client_id: string;
  client_secret: string;
  created_at: string;
  description?: string | null;
  id: string;
  name: string;
  status: UserStatus;
  tenant_id: string;
  updated_at: string;
}

/**
 * Wrap the secret fields a `ServiceAccountCreatedResponse` response carries
 * (§27.5).
 */
export function serviceAccountCreatedResponseFromWire(w: ServiceAccountCreatedResponseWire): ServiceAccountCreatedResponse {
  return {
    ...w,
    client_secret: new Sensitive(w.client_secret),
  };
}

/** Public-safe service account representation. */
export interface ServiceAccountResponse {
  /** `client_id`. */
  client_id: string;
  /** `created_at`. */
  created_at: string;
  /** `description`. */
  description?: string | null;
  /** `id`. */
  id: string;
  /** `name`. */
  name: string;
  /** `status`. */
  status: UserStatus;
  /** `tenant_id`. */
  tenant_id: string;
  /** `updated_at`. */
  updated_at: string;
}

/** Body for `PUT .../ca-certificates/{id}/mtls-trust-anchor`. */
export interface SetMtlsTrustAnchor {
  /** Whether this CA should be trusted for client-certificate authentication. */
  enabled: boolean;
}

/** Input for setting organization-level email config. */
export interface SetOrgEmailConfig {
  /** `enabled`. */
  enabled: boolean;
  /** `from_email`. */
  from_email: string;
  /** `from_name`. */
  from_name: string;
  /** `provider`. */
  provider: ProviderConfig;
  /** `reply_to`. */
  reply_to?: string | null;
}

/** Input for setting organization-level security settings. */
export interface SetOrgSettings {
  /** `access_token_lifetime_secs`. */
  access_token_lifetime_secs: number;
  /** `admin_notifications_enabled`. */
  admin_notifications_enabled: boolean;
  /** `default_cert_validity_days`. */
  default_cert_validity_days: number;
  /** `deletion_grace_period_days`. */
  deletion_grace_period_days?: number;
  /** `email_verification_grace_period_hours`. */
  email_verification_grace_period_hours: number;
  /** `email_verification_required`. */
  email_verification_required: boolean;
  /** `hibp_check_enabled`. */
  hibp_check_enabled: boolean;
  /** `lockout_backoff_multiplier`. */
  lockout_backoff_multiplier: number;
  /** `lockout_duration_secs`. */
  lockout_duration_secs: number;
  /** `max_cert_validity_days`. */
  max_cert_validity_days: number;
  /** `max_failed_login_attempts`. */
  max_failed_login_attempts: number;
  /** `max_lockout_duration_secs`. */
  max_lockout_duration_secs: number;
  /** `mfa_challenge_lifetime_secs`. */
  mfa_challenge_lifetime_secs: number;
  /** `mfa_enforced`. */
  mfa_enforced: boolean;
  /** `min_length`. */
  min_length: number;
  /** `opaque_ksf`. */
  opaque_ksf?: string;
  /** `opaque_mode`. */
  opaque_mode?: string;
  /** `opaque_suite`. */
  opaque_suite?: string;
  /** `password_history_count`. */
  password_history_count: number;
  /** `refresh_token_lifetime_secs`. */
  refresh_token_lifetime_secs: number;
  /** `require_digits`. */
  require_digits: boolean;
  /** `require_lowercase`. */
  require_lowercase: boolean;
  /** `require_symbols`. */
  require_symbols: boolean;
  /** `require_uppercase`. */
  require_uppercase: boolean;
}

/** Whether a settings row belongs to an organization or a tenant. */
export type SettingsScope =
  | "Org"
  | "Tenant";

/** Request body for signing an audit batch. */
export interface SignAuditBatchRequest {
  /** `entry_ids`. */
  entry_ids: string[];
}

/**
 * Body of `POST .../tenants/{tenant_id}/signing-cas/sign-csr`.
 *
 * Deliberately carries no key algorithm: it is the CSR's, read out of the
 * request, because a caller who could state it separately could state one
 * the key does not have.
 */
export interface SignIntermediateCsrRequest {
  /** PEM-encoded PKCS#10 certificate signing request. */
  csr_pem: string;
  /** The organization CA that signs it. */
  parent_ca_id: string;
  /** Validity duration in days, capped to the parent's own expiry. */
  validity_days: number;
}

/** A signed batch of audit log entries. */
export interface SignedAuditBatch {
  /** `batch_id`. */
  batch_id: string;
  /** `entry_ids`. */
  entry_ids: string[];
  /** ASCII-armored PGP signed message containing the audit batch payload. */
  signature_armored: string;
  /** `signed_at`. */
  signed_at: string;
  /** `signing_key_id`. */
  signing_key_id: string;
  /** `tenant_id`. */
  tenant_id: string;
}

/**
 * SMTP-specific configuration.
 *
 * `password` is write-only (D-01): `#[serde(skip_serializing)]` means it is
 * never emitted in a GET/serialized response. On the write path (D-02),
 * `#[serde(default)]` lets a caller omit the field entirely (deserializing
 * to `""`); an empty string is the sentinel for "no new secret supplied —
 * preserve whatever is already stored" (see `SurrealEmailConfigRepository::
 * set_org_config`). A non-empty value is a real secret to encrypt+replace.
 */
export interface SmtpConfig {
  /** `host`. */
  host: string;
  /** `port`. */
  port: number;
  /** Use STARTTLS (true) or implicit TLS (false). */
  starttls: boolean;
  /** `username`. */
  username: string;
}

/**
 * A tenant is an isolated context within an organization.
 *
 * Each tenant has its own set of users, roles, permissions, resources,
 * certificates, and configuration. Tenants can represent environments
 * (dev/staging/prod) or separate business contexts.
 */
export interface Tenant {
  /** `created_at`. */
  created_at: string;
  /** `id`. */
  id: string;
  /** Arbitrary key-value metadata. */
  metadata: unknown;
  /** Human-readable name. */
  name: string;
  /** The organization this tenant belongs to. */
  organization_id: string;
  /** URL-safe unique identifier within the organization (e.g., `production`). */
  slug: string;
  /** Lifecycle status. New tenants default to [`TenantStatus::Active`]. */
  status: TenantStatus;
  /** `updated_at`. */
  updated_at: string;
}

/**
 * Partial tenant overrides. `None` = inherit from org baseline.
 *
 * Every field is optional, so this is a **sparse** body: what you leave out
 * is left unchanged, and is omitted from the wire request entirely rather
 * than sent as `null` (§27.4 rule 5).
 */
export interface TenantSettingsOverride {
  /** `access_token_lifetime_secs`. */
  access_token_lifetime_secs?: number | null;
  /** `admin_notifications_enabled`. */
  admin_notifications_enabled?: boolean | null;
  /** `default_cert_validity_days`. */
  default_cert_validity_days?: number | null;
  /** `deletion_grace_period_days`. */
  deletion_grace_period_days?: number | null;
  /** `email_verification_grace_period_hours`. */
  email_verification_grace_period_hours?: number | null;
  /** `email_verification_required`. */
  email_verification_required?: boolean | null;
  /** `hibp_check_enabled`. */
  hibp_check_enabled?: boolean | null;
  /** `lockout_backoff_multiplier`. */
  lockout_backoff_multiplier?: number | null;
  /** `lockout_duration_secs`. */
  lockout_duration_secs?: number | null;
  /** `max_cert_validity_days`. */
  max_cert_validity_days?: number | null;
  /** `max_failed_login_attempts`. */
  max_failed_login_attempts?: number | null;
  /** `max_lockout_duration_secs`. */
  max_lockout_duration_secs?: number | null;
  /** `mfa_challenge_lifetime_secs`. */
  mfa_challenge_lifetime_secs?: number | null;
  /** `mfa_enforced`. */
  mfa_enforced?: boolean | null;
  /** `min_length`. */
  min_length?: number | null;
  /** `opaque_ksf`. */
  opaque_ksf?: string | null;
  /** `opaque_mode`. */
  opaque_mode?: string | null;
  /** `opaque_suite`. */
  opaque_suite?: string | null;
  /** `password_history_count`. */
  password_history_count?: number | null;
  /** `refresh_token_lifetime_secs`. */
  refresh_token_lifetime_secs?: number | null;
  /** `require_digits`. */
  require_digits?: boolean | null;
  /** `require_lowercase`. */
  require_lowercase?: boolean | null;
  /** `require_symbols`. */
  require_symbols?: boolean | null;
  /** `require_uppercase`. */
  require_uppercase?: boolean | null;
}

/**
 * Lifecycle status of a tenant.
 *
 * A `Suspended` tenant remains stored and its data isolated, but is treated
 * as administratively disabled. New tenants are `Active` by default.
 */
export type TenantStatus =
  | "Active"
  | "Suspended";

/**
 * X4 trust for exchanging this provider's tokens (RFC 8693, external
 * issuer).
 *
 * Mirrors [`TokenExchangeTrust`] on the wire rather than reusing it directly
 * so the API surface can carry its own defaults: an admin PUTting a partial
 * block gets the documented default for anything they omitted, instead of a
 * deserialization error listing fields they have never heard of.
 *
 * Every field is optional, so this is a **sparse** body: what you leave out
 * is left unchanged, and is omitted from the wire request entirely rather
 * than sent as `null` (§27.4 rule 5).
 */
export interface TokenExchangeTrustRequest {
  /**
   * Audiences an incoming subject token may name. Required (non-empty) when
   * `enabled`; there is deliberately no accept-all value.
   */
  accepted_audiences?: string[];
  /**
   * Off unless explicitly enabled. Configuring a provider for *login* is not
   * agreement to accept its tokens as API credentials.
   */
  enabled?: boolean;
  /** Per-provider ceiling on the issued AXIAM token's lifetime. */
  max_lifetime_secs?: number | null;
  /** Bound on `now - iat`, independent of the token's own `exp`. */
  max_token_age_secs?: number | null;
  /**
   * External asserted value -> AXIAM scopes. Deny-by-default: an external
   * value with no entry contributes nothing.
   */
  scope_map?: Record<string, unknown>;
  /** `linked_only` (default) or `jit_provision`. */
  subject_mapping?: string | null;
}

/**
 * X4 trust as returned. Same shape as the request; nothing here is secret —
 * an operator reading a provider needs to see exactly what it trusts.
 */
export interface TokenExchangeTrustResponse {
  /** `accepted_audiences`. */
  accepted_audiences: string[];
  /** `enabled`. */
  enabled: boolean;
  /** `max_lifetime_secs`. */
  max_lifetime_secs?: number | null;
  /** `max_token_age_secs`. */
  max_token_age_secs: number;
  /** `scope_map`. */
  scope_map: Record<string, unknown>;
  /** `subject_mapping`. */
  subject_mapping: string;
}

/** Token lifetime configuration. */
export interface TokenPolicy {
  /** `access_token_lifetime_secs`. */
  access_token_lifetime_secs: number;
  /** `refresh_token_lifetime_secs`. */
  refresh_token_lifetime_secs: number;
}

/**
 * What to do with an AAGUID that has no MDS entry (i.e. FIDO Alliance has no
 * metadata for it — not necessarily malicious, MDS coverage is incomplete
 * for some legitimate authenticators).
 */
export type UnknownAaguidAction =
  | "allow"
  | "deny";

/**
 * `UpdateFederationConfigRequest` (generated from openapi.json).
 *
 * Every field is optional, so this is a **sparse** body: what you leave out
 * is left unchanged, and is omitted from the wire request entirely rather
 * than sent as `null` (§27.4 rule 5).
 */
export interface UpdateFederationConfigRequest {
  /** Accepted signature algorithms (CQ-B40/REQ-14 AC-5). */
  allowed_algorithms?: string[] | null;
  /** `attribute_map`. */
  attribute_map?: unknown;
  /** `client_id`. */
  client_id?: string | null;
  /**
   * `client_secret`.
   *
   * **Secret.** Redacted from every string, log and JSON rendering; call
   * `.expose()` to read it.
   */
  client_secret?: Sensitive<string>;
  /** `enabled`. */
  enabled?: boolean | null;
  /**
   * PEM-encoded X.509 certificate for verifying SAML assertions (CQ-B40/REQ-14
   * AC-5). `Some(None)` clears the stored cert.
   */
  idp_signing_cert_pem?: string | null;
  /** `metadata_url`. */
  metadata_url?: string | null;
  /** `provider`. */
  provider?: string | null;
  /** `token_exchange`. */
  token_exchange?: TokenExchangeTrustRequest | null;
}

/**
 * Wire twin of {@link UpdateFederationConfigRequest} — plain strings, never
 * logged.
 */
export interface UpdateFederationConfigRequestWire {
  allowed_algorithms?: string[] | null;
  attribute_map?: unknown;
  client_id?: string | null;
  client_secret?: string;
  enabled?: boolean | null;
  idp_signing_cert_pem?: string | null;
  metadata_url?: string | null;
  provider?: string | null;
  token_exchange?: TokenExchangeTrustRequest | null;
}

/**
 * Unwrap a `UpdateFederationConfigRequest` for the wire.
 *
 * One of the two places a §27 secret is unwrapped, so that "put a secret on
 * the socket" stays a single greppable call rather than fourteen (§7 rule
 * 4).
 */
export function updateFederationConfigRequestToWire(v: UpdateFederationConfigRequest): UpdateFederationConfigRequestWire {
  return {
    ...v,
    client_secret: v.client_secret === undefined ? undefined : v.client_secret.expose(),
  };
}

/**
 * `UpdateGroup` (generated from openapi.json).
 *
 * Every field is optional, so this is a **sparse** body: what you leave out
 * is left unchanged, and is omitted from the wire request entirely rather
 * than sent as `null` (§27.4 rule 5).
 */
export interface UpdateGroup {
  /** `description`. */
  description?: string | null;
  /** `metadata`. */
  metadata?: unknown;
  /** `name`. */
  name?: string | null;
}

/**
 * `UpdateNotificationRuleRequest` (generated from openapi.json).
 *
 * Every field is optional, so this is a **sparse** body: what you leave out
 * is left unchanged, and is omitted from the wire request entirely rather
 * than sent as `null` (§27.4 rule 5).
 */
export interface UpdateNotificationRuleRequest {
  /** `description`. */
  description?: string | null;
  /** `enabled`. */
  enabled?: boolean | null;
  /** `events`. */
  events?: NotificationEventType[] | null;
  /** `name`. */
  name?: string | null;
  /** `recipient_emails`. */
  recipient_emails?: string[] | null;
}

/**
 * `UpdateOAuth2ClientRequest` (generated from openapi.json).
 *
 * Every field is optional, so this is a **sparse** body: what you leave out
 * is left unchanged, and is omitted from the wire request entirely rather
 * than sent as `null` (§27.4 rule 5).
 */
export interface UpdateOAuth2ClientRequest {
  /**
   * Pass an empty string to clear a previously registered URI — the one edit
   * an operator makes when an RP is decommissioned.
   */
  backchannel_logout_uri?: string | null;
  /** `dpop_bound_access_tokens`. */
  dpop_bound_access_tokens?: boolean | null;
  /** `dpop_require_nonce`. */
  dpop_require_nonce?: boolean | null;
  /** `grant_types`. */
  grant_types?: string[] | null;
  /**
   * X5.1 — see the create DTO. `Some("")` clears, so a client can be migrated
   * from an inline key set to a published one.
   */
  jwks?: string | null;
  /** X5.1 — see the create DTO. `Some("")` clears. */
  jwks_uri?: string | null;
  /** `name`. */
  name?: string | null;
  /** `post_logout_redirect_uris`. */
  post_logout_redirect_uris?: string[] | null;
  /** `profile`. */
  profile?: ClientProfile | null;
  /** `redirect_uris`. */
  redirect_uris?: string[] | null;
  /** `require_par`. */
  require_par?: boolean | null;
  /** `scopes`. */
  scopes?: string[] | null;
  /** `self_signed_tls_client_auth_thumbprints`. */
  self_signed_tls_client_auth_thumbprints?: string[] | null;
  /** `tls_client_auth_san_dns`. */
  tls_client_auth_san_dns?: string | null;
  /** `tls_client_auth_san_uri`. */
  tls_client_auth_san_uri?: string | null;
  /** Pass an empty string to clear, as with `backchannel_logout_uri`. */
  tls_client_auth_subject_dn?: string | null;
  /** `tls_client_certificate_bound_access_tokens`. */
  tls_client_certificate_bound_access_tokens?: boolean | null;
  /** `token_endpoint_auth_method`. */
  token_endpoint_auth_method?: ClientAuthMethod | null;
}

/**
 * `UpdateOrganizationRequest` (generated from openapi.json).
 *
 * Every field is optional, so this is a **sparse** body: what you leave out
 * is left unchanged, and is omitted from the wire request entirely rather
 * than sent as `null` (§27.4 rule 5).
 */
export interface UpdateOrganizationRequest {
  /** Free-form metadata (the admin UI stores `description` here). */
  metadata?: unknown;
  /** `name`. */
  name?: string | null;
  /** `slug`. */
  slug?: string | null;
}

/**
 * `UpdatePermissionRequest` (generated from openapi.json).
 *
 * Every field is optional, so this is a **sparse** body: what you leave out
 * is left unchanged, and is omitted from the wire request entirely rather
 * than sent as `null` (§27.4 rule 5).
 */
export interface UpdatePermissionRequest {
  /** `action`. */
  action?: string | null;
  /** `description`. */
  description?: string | null;
}

/**
 * `UpdateReactorRequest` (generated from openapi.json).
 *
 * Every field is optional, so this is a **sparse** body: what you leave out
 * is left unchanged, and is omitted from the wire request entirely rather
 * than sent as `null` (§27.4 rule 5).
 */
export interface UpdateReactorRequest {
  /** `description`. */
  description?: string | null;
  /** `enabled`. */
  enabled?: boolean | null;
  /** `events`. */
  events?: string[] | null;
  /** `failure_policy`. */
  failure_policy?: FailurePolicy | null;
  /** `mode`. */
  mode?: ReactorMode | null;
  /** `name`. */
  name?: string | null;
  /** `priority`. */
  priority?: number | null;
  /** `timeout_ms`. */
  timeout_ms?: number | null;
}

/**
 * `UpdateResourceRequest` (generated from openapi.json).
 *
 * Every field is optional, so this is a **sparse** body: what you leave out
 * is left unchanged, and is omitted from the wire request entirely rather
 * than sent as `null` (§27.4 rule 5).
 */
export interface UpdateResourceRequest {
  /** `metadata`. */
  metadata?: unknown;
  /** `name`. */
  name?: string | null;
  /** `parent_id`. */
  parent_id?: string | null;
  /** `resource_type`. */
  resource_type?: string | null;
}

/**
 * `UpdateRole` (generated from openapi.json).
 *
 * Every field is optional, so this is a **sparse** body: what you leave out
 * is left unchanged, and is omitted from the wire request entirely rather
 * than sent as `null` (§27.4 rule 5).
 */
export interface UpdateRole {
  /** `description`. */
  description?: string | null;
  /** `is_global`. */
  is_global?: boolean | null;
  /** `name`. */
  name?: string | null;
}

/**
 * `UpdateScopeRequest` (generated from openapi.json).
 *
 * Every field is optional, so this is a **sparse** body: what you leave out
 * is left unchanged, and is omitted from the wire request entirely rather
 * than sent as `null` (§27.4 rule 5).
 */
export interface UpdateScopeRequest {
  /** `description`. */
  description?: string | null;
  /** `name`. */
  name?: string | null;
}

/**
 * `UpdateServiceAccount` (generated from openapi.json).
 *
 * Every field is optional, so this is a **sparse** body: what you leave out
 * is left unchanged, and is omitted from the wire request entirely rather
 * than sent as `null` (§27.4 rule 5).
 */
export interface UpdateServiceAccount {
  /** `description`. */
  description?: string | null;
  /** `name`. */
  name?: string | null;
  /** `status`. */
  status?: UserStatus | null;
}

/**
 * Fields that can be updated on an existing tenant.
 *
 * Every field is optional, so this is a **sparse** body: what you leave out
 * is left unchanged, and is omitted from the wire request entirely rather
 * than sent as `null` (§27.4 rule 5).
 */
export interface UpdateTenant {
  /** `metadata`. */
  metadata?: unknown;
  /** `name`. */
  name?: string | null;
  /** `slug`. */
  slug?: string | null;
  /** `status`. */
  status?: TenantStatus | null;
}

/**
 * `UpdateUserRequest` (generated from openapi.json).
 *
 * Every field is optional, so this is a **sparse** body: what you leave out
 * is left unchanged, and is omitted from the wire request entirely rather
 * than sent as `null` (§27.4 rule 5).
 */
export interface UpdateUserRequest {
  /** `email`. */
  email?: string | null;
  /** `metadata`. */
  metadata?: unknown;
  /** `status`. */
  status?: UserStatus | null;
  /** `username`. */
  username?: string | null;
}

/**
 * `UpdateWebhookRequest` (generated from openapi.json).
 *
 * Every field is optional, so this is a **sparse** body: what you leave out
 * is left unchanged, and is omitted from the wire request entirely rather
 * than sent as `null` (§27.4 rule 5).
 */
export interface UpdateWebhookRequest {
  /** `enabled`. */
  enabled?: boolean | null;
  /** `events`. */
  events?: string[] | null;
  /** `retry_policy`. */
  retry_policy?: RetryPolicy | null;
  /**
   * New HMAC-SHA256 shared secret (D-02 secret rotation). Encrypted
   * server-side with AES-256-GCM before storage; omit to leave the existing
   * secret untouched.
   *
   * **Secret.** Redacted from every string, log and JSON rendering; call
   * `.expose()` to read it.
   */
  secret?: Sensitive<string>;
  /** `url`. */
  url?: string | null;
}

/** Wire twin of {@link UpdateWebhookRequest} — plain strings, never logged. */
export interface UpdateWebhookRequestWire {
  enabled?: boolean | null;
  events?: string[] | null;
  retry_policy?: RetryPolicy | null;
  secret?: string;
  url?: string | null;
}

/**
 * Unwrap a `UpdateWebhookRequest` for the wire.
 *
 * One of the two places a §27 secret is unwrapped, so that "put a secret on
 * the socket" stays a single greppable call rather than fourteen (§7 rule
 * 4).
 */
export function updateWebhookRequestToWire(v: UpdateWebhookRequest): UpdateWebhookRequestWire {
  return {
    ...v,
    secret: v.secret === undefined ? undefined : v.secret.expose(),
  };
}

/** Public-safe user representation (no password_hash, no mfa_secret). */
export interface UserResponse {
  /** `created_at`. */
  created_at: string;
  /** `email`. */
  email: string;
  /**
   * True when the user's email address has been verified (`email_verified_at`
   * is set). Exposed for the admin UI / profile.
   */
  email_verified: boolean;
  /** Number of consecutive failed login attempts. */
  failed_login_attempts: number;
  /** `id`. */
  id: string;
  /** Whether the account is currently locked (locked_until is in the future). */
  is_locked: boolean;
  /** Timestamp until which the account is locked, if any. */
  locked_until?: string | null;
  /** `metadata`. */
  metadata: unknown;
  /** `mfa_enabled`. */
  mfa_enabled: boolean;
  /** `status`. */
  status: UserStatus;
  /** `tenant_id`. */
  tenant_id: string;
  /** `updated_at`. */
  updated_at: string;
  /** `username`. */
  username: string;
}

/** `UserStatus` (generated from openapi.json). */
export type UserStatus =
  | "Active"
  | "Inactive"
  | "Locked"
  | "PendingVerification"
  | "Anonymized"
  | "Deleted";

/**
 * Per-tenant WebAuthn attestation policy (D5). One row per tenant; an absent
 * row means [`WebauthnAttestationPolicy::default`], which is today's
 * behavior unchanged.
 */
export interface WebauthnAttestationPolicy {
  /**
   * `None` = every AAGUID is allowed except `blocked_aaguids`.
   *
   * `Some(vec![])` is a deliberate "nothing may register" policy and is
   * accepted as such: `evaluate` denies every AAGUID against an empty
   * allow-list. Nothing rejects it, precisely because the failure direction is
   * safe — a client that sends `[]` when it meant `null` gets a locked-down
   * tenant, which is visible immediately, rather than an open one, which is
   * not.
   */
  allowed_aaguids?: string[] | null;
  /**
   * Deny registration if the MDS entry has ever reported `REVOKED` or any
   * `*_COMPROMISE` status (sticky — D8 step 7).
   */
  block_revoked_status: boolean;
  /** `blocked_aaguids`. */
  blocked_aaguids?: string[];
  /** `min_certification`. */
  min_certification?: CertificationLevel | null;
  /** `mode`. */
  mode: AttestationMode;
  /**
   * Require *some* `FIDO_CERTIFIED*` status, any level. Independent of (and
   * checked before) `min_certification`.
   */
  require_fido_certified: boolean;
  /** `unknown_aaguid`. */
  unknown_aaguid?: UnknownAaguidAction | null;
}

/** Webhook response — omits the shared secret. */
export interface WebhookResponse {
  /** `created_at`. */
  created_at: string;
  /** `enabled`. */
  enabled: boolean;
  /** `events`. */
  events: string[];
  /** `id`. */
  id: string;
  /** `retry_policy`. */
  retry_policy: RetryPolicy;
  /** `tenant_id`. */
  tenant_id: string;
  /** `updated_at`. */
  updated_at: string;
  /** `url`. */
  url: string;
}
