// The SSF receiver helper — CONTRACT.md §32.8's eight helper tests (plus
// poll-not-retried-on-400, discovery and the push-code mapping).
//
// Every key is an Ed25519 key generated by the test from fresh randomness, and
// every SET is signed here: no key literal, no captured token.

import { generateKeyPairSync, randomUUID, sign, type KeyObject } from 'node:crypto';
import { readFileSync } from 'node:fs';
import { http, HttpResponse } from 'msw';
import { setupServer } from 'msw/node';
import { afterAll, afterEach, beforeAll, describe, expect, it } from 'vitest';
import { AuthError, NetworkError } from '../../src/core/index.js';
import { ValidationError } from '../../src/management/errors.js';
import {
  MemoryReplayStore,
  MIN_REPLAY_WINDOW_MS,
  pushErrorCode,
  SetRefusedError,
  setErrFromReason,
  SSF_EVENT_TYPES,
  SsfReceiver,
  type SetFailureReason,
  type SsfReceiverConfig,
} from '../../src/node/ssf.js';
import { AxiamClient } from '../../src/rest/client.js';

const BASE_URL = 'https://axiam-ssf.test';
const ISSUER = 'https://iam.example.test/t/22222222-2222-4222-8222-222222222222';
const AUDIENCE = 'https://rp.example.test';
const JWKS_URI = `${BASE_URL}/oauth2/jwks`;

const server = setupServer();
beforeAll(() => server.listen({ onUnhandledFrame: 'error' }));
afterEach(() => server.resetHandlers());
afterAll(() => server.close());

interface Key {
  kid: string;
  privateKey: KeyObject;
  jwk: Record<string, unknown>;
}

function generateKey(kid = `k-${randomUUID()}`): Key {
  const { privateKey, publicKey } = generateKeyPairSync('ed25519');
  const jwk = { ...(publicKey.export({ format: 'jwk' }) as Record<string, unknown>), kid, alg: 'EdDSA', use: 'sig' };
  return { kid, privateKey, jwk };
}

const b64 = (value: unknown): string => Buffer.from(JSON.stringify(value), 'utf8').toString('base64url');

function signWith(key: Key, header: Record<string, unknown>, claims: Record<string, unknown>): string {
  const input = `${b64(header)}.${b64(claims)}`;
  return `${input}.${sign(null, Buffer.from(input), key.privateKey).toString('base64url')}`;
}

function signSet(key: Key, claims: Record<string, unknown>): string {
  return signWith(key, { alg: 'EdDSA', typ: 'secevent+jwt', kid: key.kid }, claims);
}

function claims(extra: Record<string, unknown> = {}): Record<string, unknown> {
  return {
    iss: ISSUER,
    aud: AUDIENCE,
    iat: 1_791_500_000,
    jti: randomUUID().replace(/-/g, ''),
    txn: 't-1',
    sub_id: { format: 'iss_sub', iss: ISSUER, sub: randomUUID() },
    events: { [SSF_EVENT_TYPES.SESSION_REVOKED]: { event_timestamp: 1_791_500_000 } },
    ...extra,
  };
}

function without(value: Record<string, unknown>, key: string): Record<string, unknown> {
  const copy = { ...value };
  delete copy[key];
  return copy;
}

/** Serve `keys` at the JWKS URI and count the fetches. */
function serveJwks(keys: Array<Record<string, unknown>>): { hits: number } {
  const counter = { hits: 0 };
  server.use(
    http.get(JWKS_URI, () => {
      counter.hits += 1;
      return HttpResponse.json({ keys });
    }),
  );
  return counter;
}

function client(): AxiamClient {
  return new AxiamClient({ baseUrl: BASE_URL, tenantId: randomUUID() });
}

const pollToken = `cc-${randomUUID()}`;

function receiver(overrides: Partial<SsfReceiverConfig> = {}, now?: () => number): SsfReceiver {
  return new SsfReceiver(
    client(),
    { issuer: ISSUER, audience: AUDIENCE, jwksUri: JWKS_URI, accessTokenProvider: async () => pollToken, ...overrides },
    now,
  );
}

async function reasonOf(r: SsfReceiver, set: string): Promise<SetFailureReason> {
  const err = await r.verifySet(set).catch((e: unknown) => e);
  expect(err).toBeInstanceOf(SetRefusedError);
  expect(err).toBeInstanceOf(AuthError);
  return (err as SetRefusedError).reason;
}

// ── 1 ──
describe('§32.8 receiver (1) — a SET signed by the JWKS key verifies into its claims', () => {
  it('every field of the result is the claim; array aud and the media-type typ verify too', async () => {
    const key = generateKey();
    serveJwks([key.jwk]);
    const c = claims();
    const event = await receiver().verifySet(signSet(key, c));
    expect(event).toEqual({
      jti: c.jti,
      iat: 1_791_500_000,
      iss: ISSUER,
      aud: AUDIENCE,
      txn: 't-1',
      eventType: SSF_EVENT_TYPES.SESSION_REVOKED,
      event: { event_timestamp: 1_791_500_000 },
      subId: c.sub_id,
    });

    const arrayAud = claims({ aud: ['other', AUDIENCE] });
    const set = signWith(key, { alg: 'EdDSA', typ: 'Application/SecEvent+JWT', kid: key.kid }, arrayAud);
    const second = await receiver().verifySet(set);
    expect(second.aud).toEqual(['other', AUDIENCE]);
    expect(second.txn).toBe('t-1');
  });
});

// ── 2 ──
describe('§32.8 receiver (2) — a wrong typ or alg is refused, in that order', () => {
  it('typ absent / JWT → invalid_type; alg none / HS256 → invalid_key; garbage → malformed', async () => {
    const key = generateKey();
    serveJwks([key.jwk]);
    const r = receiver();
    const c = claims();
    expect(await reasonOf(r, signWith(key, { alg: 'EdDSA', kid: key.kid }, c))).toBe('invalid_type');
    expect(await reasonOf(r, signWith(key, { alg: 'EdDSA', typ: 'JWT', kid: key.kid }, c))).toBe('invalid_type');
    expect(await reasonOf(r, `${b64({ alg: 'none', typ: 'secevent+jwt' })}.${b64(c)}.`)).toBe('invalid_key');
    const hs = signWith(key, { alg: 'HS256', typ: 'secevent+jwt', kid: key.kid }, c);
    expect(await reasonOf(r, hs)).toBe('invalid_key');
    expect(await reasonOf(r, 'a.b')).toBe('malformed');
    expect(await reasonOf(r, '!!.@@.##')).toBe('malformed');
    expect(await reasonOf(r, `${b64([1])}.${b64(c)}.x`)).toBe('malformed');
    // A key carried in the header is never honoured.
    const rogue = generateKey(key.kid);
    const embedded = signWith(rogue, { alg: 'EdDSA', typ: 'secevent+jwt', kid: 'unknown', jwk: rogue.jwk }, c);
    expect(await reasonOf(r, embedded)).toBe('invalid_key');
  });
});

// ── 3 ──
describe('§32.8 receiver (3) — another key or a tampered payload is invalid_key', () => {
  it('refuses both', async () => {
    const key = generateKey();
    serveJwks([key.jwk]);
    const r = receiver();
    const rogue = generateKey(key.kid);
    expect(await reasonOf(r, signSet(rogue, claims()))).toBe('invalid_key');
    const parts = signSet(key, claims()).split('.');
    parts[1] = b64(claims({ txn: 'x' }));
    expect(await reasonOf(r, parts.join('.'))).toBe('invalid_key');
  });
});

// ── 4 ──
describe('§32.8 receiver (4) — another issuer or audience is refused', () => {
  it('invalid_issuer and invalid_audience', async () => {
    const key = generateKey();
    serveJwks([key.jwk]);
    const r = receiver();
    expect(await reasonOf(r, signSet(key, claims({ iss: 'https://iam.example.test' })))).toBe('invalid_issuer');
    expect(await reasonOf(r, signSet(key, claims({ aud: ['https://elsewhere.test'] })))).toBe('invalid_audience');
    expect(await reasonOf(r, signSet(key, claims({ aud: 'https://elsewhere.test' })))).toBe('invalid_audience');
  });
});

// ── 5 ──
describe('§32.8 receiver (5) — exp, sub, two events or no jti is invalid_request', () => {
  it('and no iat, no sub_id, an empty jti', async () => {
    const key = generateKey();
    serveJwks([key.jwk]);
    const r = receiver();
    for (const c of [
      claims({ exp: 1_891_500_000 }),
      claims({ sub: 'u' }),
      claims({ events: { [SSF_EVENT_TYPES.ACCOUNT_DISABLED]: {}, [SSF_EVENT_TYPES.ACCOUNT_PURGED]: {} } }),
      without(claims(), 'jti'),
      claims({ jti: '' }),
      without(claims(), 'iat'),
      without(claims(), 'sub_id'),
      claims({ events: {} }),
    ]) {
      expect(await reasonOf(r, signSet(key, c))).toBe('invalid_request');
    }
  });
});

// ── 6 ──
describe('§32.8 receiver (6) — a replay is refused; a short window is refused at configuration', () => {
  it('the second sighting is replayed', async () => {
    const key = generateKey();
    serveJwks([key.jwk]);
    const r = receiver();
    const set = signSet(key, claims());
    await r.verifySet(set);
    expect(await reasonOf(r, set)).toBe('replayed');
  });

  it('a window below seven days, and a bad key source, are local ValidationErrors', () => {
    expect(() => receiver({ replayWindowMs: MIN_REPLAY_WINDOW_MS - 1 })).toThrow(ValidationError);
    expect(() => receiver({ issuer: '' })).toThrow(ValidationError);
    expect(() => receiver({ discoveryUrl: `${BASE_URL}/.well-known/ssf-configuration` })).toThrow(ValidationError);
    expect(() => receiver({ jwksUri: undefined })).toThrow(ValidationError);
    expect(() => receiver({ replayWindowMs: MIN_REPLAY_WINDOW_MS * 2 })).not.toThrow();
  });

  it('the memory store forgets after the window', () => {
    let now = 0;
    const store = new MemoryReplayStore(() => now);
    expect(store.checkAndRecord('a', 60)).toBe(true);
    expect(store.checkAndRecord('a', 60)).toBe(false);
    now = 61;
    expect(store.checkAndRecord('a', 60)).toBe(true);
  });
});

// ── 7 ──
describe('§32.8 receiver (7) — an unknown kid costs one refetch, a second one none', () => {
  it('1 fetch to prime, 2 after the first unknown kid, still 2 after the second; again after a minute', async () => {
    const key = generateKey();
    const counter = serveJwks([key.jwk]);
    let now = 1_000_000;
    const r = receiver({}, () => now);
    await r.verifySet(signSet(key, claims()));
    expect(counter.hits).toBe(1);
    expect(await reasonOf(r, signSet(generateKey(), claims()))).toBe('invalid_key');
    expect(counter.hits).toBe(2);
    expect(await reasonOf(r, signSet(generateKey(), claims()))).toBe('invalid_key');
    expect(counter.hits).toBe(2);
    now += 60_000;
    expect(await reasonOf(r, signSet(generateKey(), claims()))).toBe('invalid_key');
    expect(counter.hits).toBe(3);
  });

  it('a JWKS fetch failure is a NetworkError, not a verdict', async () => {
    server.use(http.get(JWKS_URI, () => new HttpResponse(null, { status: 503 })));
    const err = await receiver().verifySet(signSet(generateKey(), claims())).catch((e: unknown) => e);
    expect(err).toBeInstanceOf(NetworkError);
    expect(err).not.toBeInstanceOf(SetRefusedError);
  });
});

// ── 8 ──
describe('§32.8 receiver (8) — poll passes ack and setErrs through and sorts the answer', () => {
  it('exact JSON body, verified and refused apart, nothing acknowledged; a bare poll sends {}', async () => {
    const key = generateKey();
    serveJwks([key.jwk]);
    const stream = randomUUID();
    const good = claims();
    const bad = claims({ iss: 'https://impostor.test' });
    const mislabelled = claims();
    const sets: Record<string, unknown> = {
      [good.jti as string]: signSet(key, good),
      [bad.jti as string]: signSet(key, bad),
      'not-its-jti': signSet(key, mislabelled),
      'not-a-string': 42,
    };
    const seen: Array<{ body: string; authorization: string | null; cookie: string | null }> = [];
    server.use(
      http.post(`${BASE_URL}/ssf/v1/poll/${stream}`, async ({ request }) => {
        seen.push({
          body: await request.text(),
          authorization: request.headers.get('authorization'),
          cookie: request.headers.get('cookie'),
        });
        return HttpResponse.json({ sets, moreAvailable: true });
      }),
    );
    const r = receiver();
    const result = await r.poll(stream, {
      maxEvents: 10,
      returnImmediately: true,
      ack: ['done-1', 'done-2'],
      setErrs: { 'old-1': setErrFromReason('replayed') },
    });
    expect(result.moreAvailable).toBe(true);
    expect(result.events.map((e) => e.jti)).toEqual([good.jti]);
    expect(result.refused).toEqual([
      { jti: bad.jti, reason: 'invalid_issuer' },
      { jti: 'not-its-jti', reason: 'invalid_request' },
      { jti: 'not-a-string', reason: 'malformed' },
    ]);
    expect(seen).toHaveLength(1);
    expect(JSON.parse(seen[0]!.body)).toEqual({
      maxEvents: 10,
      returnImmediately: true,
      ack: ['done-1', 'done-2'],
      setErrs: { 'old-1': { err: 'invalid_request' } },
    });
    expect(seen[0]!.authorization === `Bearer ${pollToken}`, 'not the provider bearer').toBe(true);
    expect(seen[0]!.cookie).toBeNull();

    // A second poll with no options: still nothing acknowledged on the caller's behalf.
    server.resetHandlers();
    serveJwks([key.jwk]);
    server.use(
      http.post(`${BASE_URL}/ssf/v1/poll/${stream}`, async ({ request }) => {
        seen.push({ body: await request.text(), authorization: null, cookie: null });
        return HttpResponse.json({ sets: {}, moreAvailable: false });
      }),
    );
    const again = await r.poll(stream);
    expect(again).toEqual({ events: [], moreAvailable: false, refused: [], unjudged: [] });
    expect(seen[1]!.body).toBe('{}');
  });

  it('is not retried on 400, with retry enabled; a 503 is', async () => {
    let hits = 0;
    server.use(
      http.post(`${BASE_URL}/ssf/v1/poll/s-1`, () => {
        hits += 1;
        return HttpResponse.json({ error: 'push stream' }, { status: 400 });
      }),
    );
    const err = await receiver().poll('s-1').catch((e: unknown) => e);
    expect(err).toBeInstanceOf(ValidationError);
    expect(hits).toBe(1);

    let unavailable = 0;
    server.use(
      http.post(`${BASE_URL}/ssf/v1/poll/s-2`, () => {
        unavailable += 1;
        return new HttpResponse(null, { status: 503 });
      }),
    );
    await expect(receiver().poll('s-2')).rejects.toBeInstanceOf(NetworkError);
    expect(unavailable).toBeGreaterThan(1);
  });

  // Contract 1.59 §34.2 P1 (R-1, review F-2): `poll` never leaves a `jti`
  // recorded that it does not return. The batch's first SET verifies (and is
  // recorded); the second names an unknown kid while the refetch fails, which
  // is no verdict. Before 1.59 the poll threw, the first SET was lost to the
  // caller, and its re-offer read `replayed`.
  it('a two-SET batch whose second SET fails its key fetch: the first is returned, the second unrecorded', async () => {
    const key = generateKey();
    let jwksHits = 0;
    server.use(
      http.get(JWKS_URI, () => {
        jwksHits += 1;
        return jwksHits === 1 ? HttpResponse.json({ keys: [key.jwk] }) : new HttpResponse(null, { status: 503 });
      }),
    );
    const first = claims();
    const second = claims();
    const firstSet = signSet(key, first);
    const secondSet = signSet(generateKey(), second);
    server.use(
      http.post(`${BASE_URL}/ssf/v1/poll/s-4`, () =>
        HttpResponse.json({ sets: { [first.jti as string]: firstSet, [second.jti as string]: secondSet }, moreAvailable: false }),
      ),
    );
    const recorded = new Set<string>();
    const memory = new MemoryReplayStore();
    const store = {
      checkAndRecord(jti: string, windowMs: number): boolean {
        const fresh = memory.checkAndRecord(jti, windowMs);
        if (fresh) recorded.add(jti);
        return fresh;
      },
    };
    const r = receiver({ replayStore: store });
    const outcome = await r.poll('s-4').then(
      (result) => ({ result, error: undefined }),
      (error: unknown) => ({ result: undefined, error }),
    );
    expect(jwksHits).toBe(2);
    // The contract's assertion: the first jti is not in the store, or the first SET is returned.
    const returned = outcome.result?.events.some((e) => e.jti === first.jti) ?? false;
    expect(!recorded.has(first.jti as string) || returned, 'the first SET was recorded and not returned').toBe(true);
    // This SDK's form: what was judged is returned; the unjudged SET is neither
    // returned nor refused nor recorded, and is listed by jti.
    expect(outcome.error).toBeUndefined();
    expect(outcome.result?.events.map((e) => e.jti)).toEqual([first.jti]);
    expect(outcome.result?.refused).toEqual([]);
    expect(outcome.result?.unjudged).toEqual([second.jti]);
    expect(recorded.has(second.jti as string)).toBe(false);
  });

  it('a replay store that cannot answer leaves that SET unjudged and unrecorded, the rest returned', async () => {
    const key = generateKey();
    serveJwks([key.jwk]);
    const first = claims();
    const second = claims();
    server.use(
      http.post(`${BASE_URL}/ssf/v1/poll/s-5`, () =>
        HttpResponse.json({
          sets: { [first.jti as string]: signSet(key, first), [second.jti as string]: signSet(key, second) },
          moreAvailable: false,
        }),
      ),
    );
    const memory = new MemoryReplayStore();
    const store = {
      checkAndRecord(jti: string, windowMs: number): boolean {
        if (jti === second.jti) throw new NetworkError('replay store unavailable');
        return memory.checkAndRecord(jti, windowMs);
      },
    };
    const result = await receiver({ replayStore: store }).poll('s-5');
    expect(result.events.map((e) => e.jti)).toEqual([first.jti]);
    expect(result.refused).toEqual([]);
    expect(result.unjudged).toEqual([second.jti]);
    expect(memory.checkAndRecord(second.jti as string, MIN_REPLAY_WINDOW_MS), 'the unjudged jti was recorded').toBe(true);
  });

  it('a JWKS failure during a poll aborts it; no provider is a local AuthError', async () => {
    server.use(
      http.get(JWKS_URI, () => new HttpResponse(null, { status: 500 })),
      http.post(`${BASE_URL}/ssf/v1/poll/s-3`, () =>
        HttpResponse.json({ sets: { a: signSet(generateKey(), claims()) }, moreAvailable: false }),
      ),
    );
    await expect(receiver({}, undefined).poll('s-3')).rejects.toBeInstanceOf(NetworkError);
    await expect(receiver({ accessTokenProvider: undefined }).poll('s-3')).rejects.toBeInstanceOf(AuthError);
  });
});

// Contract 1.59 §34.2 P7 (R-7, review F-9): `poll` is not retried on a `4xx`
// other than `408` and `429`, which §16.3 retries. The code always did; the
// README said "not retried on a `4xx`".
describe('§32.7 / §34.2 P7 — poll retries 408 and 429, and the README says so', () => {
  it('408 and 429 are retried, as a 503 is', async () => {
    for (const status of [408, 429]) {
      let hits = 0;
      server.use(
        http.post(`${BASE_URL}/ssf/v1/poll/s-${status}`, () => {
          hits += 1;
          return hits === 1 ? new HttpResponse(null, { status }) : HttpResponse.json({ sets: {}, moreAvailable: false });
        }),
      );
      const result = await receiver().poll(`s-${status}`);
      expect(result.events).toEqual([]);
      expect(hits, `HTTP ${status} was not retried`).toBe(2);
    }
  });

  it("the README's SSF receiver section states the 408 / 429 exception", () => {
    const readme = readFileSync(new URL('../../README.md', import.meta.url), 'utf8');
    const start = readme.indexOf('## SSF receiver');
    const end = readme.indexOf('\n## ', start + 1);
    const section = readme.slice(start, end).replace(/\s+/g, ' ');
    expect(start).toBeGreaterThan(-1);
    expect(section).not.toMatch(/not retried on a `4xx`(?! other than `408` and `429`)/);
    expect(section).toContain('not retried on a `4xx` other than `408` and `429`');
  });
});

describe('discovery and push codes', () => {
  it('discovery supplies the jwks_uri and must name the issuer', async () => {
    const key = generateKey();
    serveJwks([key.jwk]);
    server.use(
      http.get(`${BASE_URL}/.well-known/ssf-configuration`, () =>
        HttpResponse.json({ issuer: ISSUER, jwks_uri: JWKS_URI }),
      ),
    );
    const discovery = `${BASE_URL}/.well-known/ssf-configuration`;
    await receiver({ jwksUri: undefined, discoveryUrl: discovery }).verifySet(signSet(key, claims()));

    const wrong = receiver({ jwksUri: undefined, discoveryUrl: discovery, issuer: 'https://someone-else.test' });
    const err = await wrong.verifySet(signSet(key, claims())).catch((e: unknown) => e);
    expect(err).toBeInstanceOf(NetworkError);
    expect(err).not.toBeInstanceOf(SetRefusedError);

    const plain = receiver({ jwksUri: 'http://jwks.example.test/keys' });
    await expect(plain.verifySet(signSet(key, claims()))).rejects.toBeInstanceOf(NetworkError);
  });

  it('push codes are RFC 8935 codes', () => {
    const cases: Array<[SetFailureReason, string]> = [
      ['malformed', 'invalid_request'],
      ['invalid_type', 'invalid_request'],
      ['replayed', 'invalid_request'],
      ['invalid_key', 'invalid_key'],
      ['invalid_issuer', 'invalid_issuer'],
      ['invalid_audience', 'invalid_audience'],
      ['invalid_request', 'invalid_request'],
    ];
    for (const [reason, code] of cases) {
      expect(pushErrorCode(reason)).toBe(code);
      expect(setErrFromReason(reason)).toEqual({ err: code });
    }
    expect(setErrFromReason('invalid_key', 'why')).toEqual({ err: 'invalid_key', description: 'why' });
  });
});
