// @generated by scripts/gen-management.mjs from management-registry.json and
// openapi.json. DO NOT EDIT — your changes will be overwritten. Regenerate with
// `node scripts/gen-management.mjs`; CI verifies the committed output is current.

/**
 * The `audit` management namespace (CONTRACT §27.1).
 *
 * Append-only audit log, read-only by construction.
 */

import type { AxiamClient } from '../../rest/client.js';
import * as models from '../models.js';
import type { Page, PageRequest } from '../page.js';
import { collectPages, pageQuery } from '../page.js';
import { sendManagement } from '../request.js';
import type { Scope } from '../scope.js';

/**
 * Optional filters for `audit.list`.
 *
 * Six loose optional arguments is a call site a reader cannot check and a
 * refactor silently reorders, so they travel as one object.
 */
export interface AuditListFilter {
  /** Filter on `actor_id`. */
  actorId?: string;
  /** Filter on `action`. */
  action?: string;
  /** Filter on `outcome`. */
  outcome?: string;
  /** Filter on `resource_id`. */
  resourceId?: string;
  /** Filter on `from`. */
  from?: string;
  /** Filter on `to`. */
  to?: string;
}

/**
 * Optional filters for `audit.list_system`.
 *
 * Six loose optional arguments is a call site a reader cannot check and a
 * refactor silently reorders, so they travel as one object.
 */
export interface AuditListSystemFilter {
  /** Filter on `actor_id`. */
  actorId?: string;
  /** Filter on `action`. */
  action?: string;
  /** Filter on `outcome`. */
  outcome?: string;
  /** Filter on `resource_id`. */
  resourceId?: string;
  /** Filter on `from`. */
  from?: string;
  /** Filter on `to`. */
  to?: string;
}

/**
 * The `audit` namespace handle.
 *
 * Append-only audit log, read-only by construction.
 *
 * Acquiring one performs no I/O and allocates nothing meaningful (§27.2 rule
 * 1); it holds the client and cannot be constructed without one.
 */
export class AuditApi {
  readonly #client: AxiamClient;
  readonly #scope: Scope;

  /** @internal — reached through `client.<namespace>`, never constructed directly. */
  constructor(client: AxiamClient, scope: Scope = {}) {
    this.#client = client;
    this.#scope = scope;
  }

  /** `GET /api/v1/audit-logs` */
  async list(filter: AuditListFilter = {}, page: PageRequest = {}): Promise<Page<models.AuditLogEntry>> {
    const wire = await sendManagement<Page<models.AuditLogEntry>>(this.#client, {
      operation: 'audit.list',
      method: 'GET',
      pathTemplate: '/api/v1/audit-logs',
      path: '/api/v1/audit-logs',
      query: { ...pageQuery(page), 'actor_id': filter.actorId, 'action': filter.action, 'outcome': filter.outcome, 'resource_id': filter.resourceId, 'from': filter.from, 'to': filter.to },
    });
    return wire;
  }

  /**
   * Walk `audit.list` to exhaustion, concatenating every page.
   *
   * The auto-paging form §27.4 rule 4 requires. It stops on an empty page even
   * if `total` disagrees, so a misreporting server costs one wasted request
   * rather than an unbounded loop.
   */
  listAll(filter: AuditListFilter = {}, start: PageRequest = {}): Promise<models.AuditLogEntry[]> {
    return collectPages(start, (p) => this.list(filter, p));
  }

  /** `GET /api/v1/audit-logs/system` */
  async listSystem(filter: AuditListSystemFilter = {}, page: PageRequest = {}): Promise<Page<models.AuditLogEntry>> {
    const wire = await sendManagement<Page<models.AuditLogEntry>>(this.#client, {
      operation: 'audit.list_system',
      method: 'GET',
      pathTemplate: '/api/v1/audit-logs/system',
      path: '/api/v1/audit-logs/system',
      query: { ...pageQuery(page), 'actor_id': filter.actorId, 'action': filter.action, 'outcome': filter.outcome, 'resource_id': filter.resourceId, 'from': filter.from, 'to': filter.to },
    });
    return wire;
  }

  /**
   * Walk `audit.list_system` to exhaustion, concatenating every page.
   *
   * The auto-paging form §27.4 rule 4 requires. It stops on an empty page even
   * if `total` disagrees, so a misreporting server costs one wasted request
   * rather than an unbounded loop.
   */
  listSystemAll(filter: AuditListSystemFilter = {}, start: PageRequest = {}): Promise<models.AuditLogEntry[]> {
    return collectPages(start, (p) => this.listSystem(filter, p));
  }

}
