// @generated by scripts/gen-management.mjs from management-registry.json and
// openapi.json. DO NOT EDIT — your changes will be overwritten. Regenerate with
// `node scripts/gen-management.mjs`; CI verifies the committed output is current.

/**
 * The `ca_certificates` management namespace (CONTRACT §27.1).
 *
 * Organization CAs and the per-tenant signing CAs chained beneath them.
 */

import type { AxiamClient } from '../../rest/client.js';
import * as models from '../models.js';
import type { Page, PageRequest } from '../page.js';
import { collectPages, pageQuery } from '../page.js';
import { sendManagement } from '../request.js';
import type { Scope } from '../scope.js';
import { resolveOrg, resolveTenant } from '../scope.js';

/**
 * The `ca_certificates` namespace handle.
 *
 * Organization CAs and the per-tenant signing CAs chained beneath them.
 *
 * Acquiring one performs no I/O and allocates nothing meaningful (§27.2 rule
 * 1); it holds the client and cannot be constructed without one.
 */
export class CaCertificatesApi {
  readonly #client: AxiamClient;
  readonly #scope: Scope;

  /** @internal — reached through `client.<namespace>`, never constructed directly. */
  constructor(client: AxiamClient, scope: Scope = {}) {
    this.#client = client;
    this.#scope = scope;
  }

  /**
   * Address a different organization than the client's own.
   *
   * §27.4 rule 3: the client's `orgId` is the default, and a platform-admin
   * token legitimately overrides it. Returns a new handle; the original is
   * unchanged.
   */
  inOrg(orgId: string): CaCertificatesApi {
    return new CaCertificatesApi(this.#client, { ...this.#scope, orgId });
  }

  /** `GET /api/v1/organizations/{org_id}/ca-certificates` */
  async list(page: PageRequest = {}): Promise<Page<models.CaCertificate>> {
    const orgId = resolveOrg(this.#client, this.#scope, "ca_certificates.list");
    const wire = await sendManagement<Page<models.CaCertificate>>(this.#client, {
      operation: 'ca_certificates.list',
      method: 'GET',
      pathTemplate: '/api/v1/organizations/{org_id}/ca-certificates',
      path: `/api/v1/organizations/${orgId}/ca-certificates`,
      query: { ...pageQuery(page) },
    });
    return wire;
  }

  /**
   * Walk `ca_certificates.list` to exhaustion, concatenating every page.
   *
   * The auto-paging form §27.4 rule 4 requires. It stops on an empty page even
   * if `total` disagrees, so a misreporting server costs one wasted request
   * rather than an unbounded loop.
   */
  listAll(start: PageRequest = {}): Promise<models.CaCertificate[]> {
    return collectPages(start, (p) => this.list(p));
  }

  /**
   * `POST /api/v1/organizations/{org_id}/ca-certificates`
   *
   * **Returns secret material, once.** `private_key_pem` is returned by this
   * call and by no other; no later `get` will return it again, and the `get`
   * projection has no field where it was. Discarding the result destroys the
   * credential (§27.5 rule 3).
   *
   * Not retried on failure (§27.4 rule 8): every write on this surface is
   * issued exactly once, including the ones that look idempotent.
   */
  async generate(body: models.CreateCaCertificateRequest): Promise<models.GeneratedCaCertificate> {
    const orgId = resolveOrg(this.#client, this.#scope, "ca_certificates.generate");
    const wire = await sendManagement<models.GeneratedCaCertificateWire>(this.#client, {
      operation: 'ca_certificates.generate',
      method: 'POST',
      pathTemplate: '/api/v1/organizations/{org_id}/ca-certificates',
      path: `/api/v1/organizations/${orgId}/ca-certificates`,
      body: body,
    });
    return models.generatedCaCertificateFromWire(wire);
  }

  /**
   * `POST /api/v1/organizations/{org_id}/ca-certificates/import`
   *
   * Not retried on failure (§27.4 rule 8): every write on this surface is
   * issued exactly once, including the ones that look idempotent.
   */
  async importCa(body: models.ImportCaCertificateRequest): Promise<models.CaCertificate> {
    const orgId = resolveOrg(this.#client, this.#scope, "ca_certificates.import_ca");
    const wire = await sendManagement<models.CaCertificate>(this.#client, {
      operation: 'ca_certificates.import_ca',
      method: 'POST',
      pathTemplate: '/api/v1/organizations/{org_id}/ca-certificates/import',
      path: `/api/v1/organizations/${orgId}/ca-certificates/import`,
      body: models.importCaCertificateRequestToWire(body),
    });
    return wire;
  }

  /** `GET /api/v1/organizations/{org_id}/ca-certificates/{id}` */
  async get(id: string): Promise<models.CaCertificate> {
    const orgId = resolveOrg(this.#client, this.#scope, "ca_certificates.get");
    const wire = await sendManagement<models.CaCertificate>(this.#client, {
      operation: 'ca_certificates.get',
      method: 'GET',
      pathTemplate: '/api/v1/organizations/{org_id}/ca-certificates/{id}',
      path: `/api/v1/organizations/${orgId}/ca-certificates/${encodeURIComponent(id)}`,
    });
    return wire;
  }

  /**
   * `POST /api/v1/organizations/{org_id}/ca-certificates/{id}/revoke`
   *
   * Not retried on failure (§27.4 rule 8): every write on this surface is
   * issued exactly once, including the ones that look idempotent.
   */
  async revoke(id: string): Promise<void> {
    const orgId = resolveOrg(this.#client, this.#scope, "ca_certificates.revoke");
    await sendManagement<void>(this.#client, {
      operation: 'ca_certificates.revoke',
      method: 'POST',
      pathTemplate: '/api/v1/organizations/{org_id}/ca-certificates/{id}/revoke',
      path: `/api/v1/organizations/${orgId}/ca-certificates/${encodeURIComponent(id)}/revoke`,
    });
  }

  /**
   * `POST /api/v1/organizations/{org_id}/ca-certificates/{id}/migrate-custody`
   *
   * Not retried on failure (§27.4 rule 8): every write on this surface is
   * issued exactly once, including the ones that look idempotent.
   */
  async migrateCustody(id: string): Promise<models.MigrateCustodyResponse> {
    const orgId = resolveOrg(this.#client, this.#scope, "ca_certificates.migrate_custody");
    const wire = await sendManagement<models.MigrateCustodyResponse>(this.#client, {
      operation: 'ca_certificates.migrate_custody',
      method: 'POST',
      pathTemplate: '/api/v1/organizations/{org_id}/ca-certificates/{id}/migrate-custody',
      path: `/api/v1/organizations/${orgId}/ca-certificates/${encodeURIComponent(id)}/migrate-custody`,
    });
    return wire;
  }

  /**
   * `PUT
   * /api/v1/organizations/{org_id}/ca-certificates/{id}/mtls-trust-anchor`
   *
   * **This is a replacement, not a patch** (§27.4 rule 5). Every field of the
   * body is required, and what you do not carry over from a prior read is not
   * preserved — it is overwritten. Read first, change the field you mean, send
   * the whole thing back.
   *
   * Not retried on failure (§27.4 rule 8): every write on this surface is
   * issued exactly once, including the ones that look idempotent.
   */
  async setMtlsTrustAnchor(id: string, body: models.SetMtlsTrustAnchor): Promise<models.MtlsTrustAnchorResponse> {
    const orgId = resolveOrg(this.#client, this.#scope, "ca_certificates.set_mtls_trust_anchor");
    const wire = await sendManagement<models.MtlsTrustAnchorResponse>(this.#client, {
      operation: 'ca_certificates.set_mtls_trust_anchor',
      method: 'PUT',
      pathTemplate: '/api/v1/organizations/{org_id}/ca-certificates/{id}/mtls-trust-anchor',
      path: `/api/v1/organizations/${orgId}/ca-certificates/${encodeURIComponent(id)}/mtls-trust-anchor`,
      body: body,
    });
    return wire;
  }

  /** `GET /api/v1/organizations/{org_id}/tenants/{tenant_id}/signing-cas` */
  async listSigningCas(tenantId: string, page: PageRequest = {}): Promise<Page<models.CaCertificate>> {
    const orgId = resolveOrg(this.#client, this.#scope, "ca_certificates.list_signing_cas");
    const wire = await sendManagement<Page<models.CaCertificate>>(this.#client, {
      operation: 'ca_certificates.list_signing_cas',
      method: 'GET',
      pathTemplate: '/api/v1/organizations/{org_id}/tenants/{tenant_id}/signing-cas',
      path: `/api/v1/organizations/${orgId}/tenants/${encodeURIComponent(tenantId)}/signing-cas`,
      query: { ...pageQuery(page) },
    });
    return wire;
  }

  /**
   * Walk `ca_certificates.list_signing_cas` to exhaustion, concatenating every
   * page.
   *
   * The auto-paging form §27.4 rule 4 requires. It stops on an empty page even
   * if `total` disagrees, so a misreporting server costs one wasted request
   * rather than an unbounded loop.
   */
  listSigningCasAll(tenantId: string, start: PageRequest = {}): Promise<models.CaCertificate[]> {
    return collectPages(start, (p) => this.listSigningCas(tenantId, p));
  }

  /**
   * `POST /api/v1/organizations/{org_id}/tenants/{tenant_id}/signing-cas`
   *
   * **Returns secret material, once.** `private_key_pem` is returned by this
   * call and by no other; no later `get` will return it again, and the `get`
   * projection has no field where it was. Discarding the result destroys the
   * credential (§27.5 rule 3).
   *
   * Not retried on failure (§27.4 rule 8): every write on this surface is
   * issued exactly once, including the ones that look idempotent.
   */
  async generateSigningCa(tenantId: string, body: models.CreateIntermediateCaRequest): Promise<models.GeneratedCaCertificate> {
    const orgId = resolveOrg(this.#client, this.#scope, "ca_certificates.generate_signing_ca");
    const wire = await sendManagement<models.GeneratedCaCertificateWire>(this.#client, {
      operation: 'ca_certificates.generate_signing_ca',
      method: 'POST',
      pathTemplate: '/api/v1/organizations/{org_id}/tenants/{tenant_id}/signing-cas',
      path: `/api/v1/organizations/${orgId}/tenants/${encodeURIComponent(tenantId)}/signing-cas`,
      body: body,
    });
    return models.generatedCaCertificateFromWire(wire);
  }

  /**
   * `POST
   * /api/v1/organizations/{org_id}/tenants/{tenant_id}/signing-cas/sign-csr`
   *
   * Not retried on failure (§27.4 rule 8): every write on this surface is
   * issued exactly once, including the ones that look idempotent.
   */
  async signSigningCaCsr(tenantId: string, body: models.SignIntermediateCsrRequest): Promise<models.CaCertificate> {
    const orgId = resolveOrg(this.#client, this.#scope, "ca_certificates.sign_signing_ca_csr");
    const wire = await sendManagement<models.CaCertificate>(this.#client, {
      operation: 'ca_certificates.sign_signing_ca_csr',
      method: 'POST',
      pathTemplate: '/api/v1/organizations/{org_id}/tenants/{tenant_id}/signing-cas/sign-csr',
      path: `/api/v1/organizations/${orgId}/tenants/${encodeURIComponent(tenantId)}/signing-cas/sign-csr`,
      body: body,
    });
    return wire;
  }

}
