// @generated by scripts/gen-management.mjs from management-registry.json and
// openapi.json. DO NOT EDIT — your changes will be overwritten. Regenerate with
// `node scripts/gen-management.mjs`; CI verifies the committed output is current.

/**
 * The `certificates` management namespace (CONTRACT §27.1).
 *
 * End-entity X.509 certificates -- the ones issued to users, services and
 * IoT devices.
 */

import type { AxiamClient } from '../../rest/client.js';
import * as models from '../models.js';
import type { Page, PageRequest } from '../page.js';
import { collectPages, pageQuery } from '../page.js';
import { sendManagement } from '../request.js';
import type { Scope } from '../scope.js';

/**
 * The `certificates` namespace handle.
 *
 * End-entity X.509 certificates -- the ones issued to users, services and
 * IoT devices.
 *
 * Acquiring one performs no I/O and allocates nothing meaningful (§27.2 rule
 * 1); it holds the client and cannot be constructed without one.
 */
export class CertificatesApi {
  readonly #client: AxiamClient;
  readonly #scope: Scope;

  /** @internal — reached through `client.<namespace>`, never constructed directly. */
  constructor(client: AxiamClient, scope: Scope = {}) {
    this.#client = client;
    this.#scope = scope;
  }

  /** `GET /api/v1/certificates` */
  async list(page: PageRequest = {}): Promise<Page<models.Certificate>> {
    const wire = await sendManagement<Page<models.Certificate>>(this.#client, {
      operation: 'certificates.list',
      method: 'GET',
      pathTemplate: '/api/v1/certificates',
      path: '/api/v1/certificates',
      query: { ...pageQuery(page) },
    });
    return wire;
  }

  /**
   * Walk `certificates.list` to exhaustion, concatenating every page.
   *
   * The auto-paging form §27.4 rule 4 requires. It stops on an empty page even
   * if `total` disagrees, so a misreporting server costs one wasted request
   * rather than an unbounded loop.
   */
  listAll(start: PageRequest = {}): Promise<models.Certificate[]> {
    return collectPages(start, (p) => this.list(p));
  }

  /**
   * `POST /api/v1/certificates`
   *
   * **Returns secret material, once.** `private_key_pem` is returned by this
   * call and by no other; no later `get` will return it again, and the `get`
   * projection has no field where it was. Discarding the result destroys the
   * credential (§27.5 rule 3).
   *
   * Not retried on failure (§27.4 rule 8): every write on this surface is
   * issued exactly once, including the ones that look idempotent.
   */
  async generate(body: models.CreateCertificateRequest): Promise<models.GeneratedCertificate> {
    const wire = await sendManagement<models.GeneratedCertificateWire>(this.#client, {
      operation: 'certificates.generate',
      method: 'POST',
      pathTemplate: '/api/v1/certificates',
      path: '/api/v1/certificates',
      body: body,
    });
    return models.generatedCertificateFromWire(wire);
  }

  /** `GET /api/v1/certificates/{id}` */
  async get(id: string): Promise<models.Certificate> {
    const wire = await sendManagement<models.Certificate>(this.#client, {
      operation: 'certificates.get',
      method: 'GET',
      pathTemplate: '/api/v1/certificates/{id}',
      path: `/api/v1/certificates/${encodeURIComponent(id)}`,
    });
    return wire;
  }

  /**
   * `POST /api/v1/certificates/{id}/revoke`
   *
   * Not retried on failure (§27.4 rule 8): every write on this surface is
   * issued exactly once, including the ones that look idempotent.
   */
  async revoke(id: string): Promise<void> {
    await sendManagement<void>(this.#client, {
      operation: 'certificates.revoke',
      method: 'POST',
      pathTemplate: '/api/v1/certificates/{id}/revoke',
      path: `/api/v1/certificates/${encodeURIComponent(id)}/revoke`,
    });
  }

}
