// @generated by scripts/gen-management.mjs from management-registry.json and
// openapi.json. DO NOT EDIT — your changes will be overwritten. Regenerate with
// `node scripts/gen-management.mjs`; CI verifies the committed output is current.

/**
 * The `directory` management namespace (CONTRACT §27.1).
 *
 * A tenant's LDAP / Active Directory identity source (CONTRACT §30): the one
 * configuration, the explicit act that links an existing local account to
 * its directory entry, and a read-only view of the sync job. Signing in
 * needs nothing new -- a directory account calls the same §1 `login`.
 */

import type { AxiamClient } from '../../rest/client.js';
import * as models from '../models.js';
import { sendManagement } from '../request.js';
import type { NamespaceScope } from '../scope.js';
import { resolveOrg, resolveTenant } from '../scope.js';

/**
 * The `directory` namespace handle.
 *
 * A tenant's LDAP / Active Directory identity source (CONTRACT §30): the one
 * configuration, the explicit act that links an existing local account to
 * its directory entry, and a read-only view of the sync job. Signing in
 * needs nothing new -- a directory account calls the same §1 `login`.
 *
 * Acquiring one performs no I/O and allocates nothing meaningful (§27.2 rule
 * 1); it holds the client and cannot be constructed without one.
 */
export class DirectoryApi {
  readonly #client: AxiamClient;
  readonly #scope: NamespaceScope;

  /** @internal — reached through `client.<namespace>`, never constructed directly. */
  constructor(client: AxiamClient, scope: NamespaceScope = {}) {
    this.#client = client;
    this.#scope = scope;
  }

  /**
   * Address a different tenant than the client's own (§27.4 rule 3).
   *
   * Returns a new handle; the original is unchanged.
   */
  forTenant(tenantId: string): DirectoryApi {
    return new DirectoryApi(this.#client, { ...this.#scope, tenantId });
  }

  /** `GET /api/v1/tenants/{tenant_id}/directory` */
  async get(): Promise<models.DirectoryConfig> {
    const tenantId = resolveTenant(this.#client, this.#scope, "directory.get");
    const wire = await sendManagement<models.DirectoryConfig>(this.#client, {
      operation: 'directory.get',
      method: 'GET',
      pathTemplate: '/api/v1/tenants/{tenant_id}/directory',
      path: `/api/v1/tenants/${tenantId}/directory`,
    });
    return models.scrubDirectoryConfig(wire);
  }

  /**
   * `PUT /api/v1/tenants/{tenant_id}/directory`
   *
   * **Moving the connection requires the secret again** (§30.3 rule 2): a
   * `set` that changes `url`, `start_tls`, `bind_dn` or `trust_anchors_pem`
   * without `bind_secret` is refused `400` and changes nothing. The SDK holds
   * no copy of the secret and cannot re-send one for you. `bind_secret` is
   * required while the tenant has no configuration; otherwise absent keeps the
   * stored secret. Every other optional member left out is **reset to its
   * default** — start from `setDirectoryConfigFrom(await directory.get())`. An
   * enabled directory and an effective `opaque_mode = required` never coexist
   * (`409`); without the deployment's directory key a write carrying a secret
   * is `503`.
   *
   * **This is a replacement, not a patch** (§27.4 rule 5). Every field of the
   * body is required, and what you do not carry over from a prior read is not
   * preserved — it is overwritten. Read first, change the field you mean, send
   * the whole thing back.
   *
   * Not retried on failure (§27.4 rule 8): every write on this surface is
   * issued exactly once, including the ones that look idempotent.
   */
  async set(body: models.SetDirectoryConfig): Promise<models.DirectoryConfig> {
    const tenantId = resolveTenant(this.#client, this.#scope, "directory.set");
    const wire = await sendManagement<models.DirectoryConfig>(this.#client, {
      operation: 'directory.set',
      method: 'PUT',
      pathTemplate: '/api/v1/tenants/{tenant_id}/directory',
      path: `/api/v1/tenants/${tenantId}/directory`,
      body: models.setDirectoryConfigToWire(body),
    });
    return models.scrubDirectoryConfig(wire);
  }

  /**
   * `PATCH /api/v1/tenants/{tenant_id}/directory`
   *
   * **Moving the connection requires the secret again** (§30.3 rule 2): an
   * `update` that changes `url`, `start_tls`, `bind_dn` or `trust_anchors_pem`
   * without `bind_secret` is refused `400` and changes nothing; the SDK holds
   * no copy of the secret to re-send. A member left `undefined` is not sent
   * and stays as stored; `group_base_dn` / `group_filter` set to `null` are
   * sent as `null` and clear the value. An enabled directory and an effective
   * `opaque_mode = required` never coexist (`409`).
   *
   * Not retried on failure (§27.4 rule 8): every write on this surface is
   * issued exactly once, including the ones that look idempotent.
   */
  async update(body: models.UpdateDirectoryConfig): Promise<models.DirectoryConfig> {
    const tenantId = resolveTenant(this.#client, this.#scope, "directory.update");
    const wire = await sendManagement<models.DirectoryConfig>(this.#client, {
      operation: 'directory.update',
      method: 'PATCH',
      pathTemplate: '/api/v1/tenants/{tenant_id}/directory',
      path: `/api/v1/tenants/${tenantId}/directory`,
      body: models.updateDirectoryConfigToWire(body),
    });
    return models.scrubDirectoryConfig(wire);
  }

  /**
   * `DELETE /api/v1/tenants/{tenant_id}/directory`
   *
   * **Deleting stops the directory, and only that** (§30.3 rule 5): directory
   * accounts can no longer sign in with a password — there is no fallback to a
   * local hash — and the sync stops. Sessions, refresh tokens and passkeys
   * those accounts already hold keep working until they expire or the accounts
   * are deactivated. There is no unlink: a linked account stays a directory
   * account.
   *
   * Not retried on failure (§27.4 rule 8): every write on this surface is
   * issued exactly once, including the ones that look idempotent.
   */
  async delete(): Promise<void> {
    const tenantId = resolveTenant(this.#client, this.#scope, "directory.delete");
    await sendManagement<void>(this.#client, {
      operation: 'directory.delete',
      method: 'DELETE',
      pathTemplate: '/api/v1/tenants/{tenant_id}/directory',
      path: `/api/v1/tenants/${tenantId}/directory`,
    });
  }

  /**
   * `POST /api/v1/tenants/{tenant_id}/directory/links`
   *
   * **Signs the account's owner out everywhere** (§30.3 rule 6): linking
   * deletes the account's WebAuthn credentials and federation links, revokes
   * its `User` certificates, all its sessions and its OAuth2 refresh tokens
   * (TOTP is kept). The entry is found by the account's own username; a repeat
   * on an already-linked account answers `was_already_linked` and repeats the
   * revocations.
   *
   * Not retried on failure (§27.4 rule 8): every write on this surface is
   * issued exactly once, including the ones that look idempotent.
   */
  async linkAccount(body: models.LinkDirectoryAccount): Promise<models.DirectoryLinkResult> {
    const tenantId = resolveTenant(this.#client, this.#scope, "directory.link_account");
    const wire = await sendManagement<models.DirectoryLinkResult>(this.#client, {
      operation: 'directory.link_account',
      method: 'POST',
      pathTemplate: '/api/v1/tenants/{tenant_id}/directory/links',
      path: `/api/v1/tenants/${tenantId}/directory/links`,
      body: body,
    });
    return models.scrubDirectoryLinkResult(wire);
  }

  /** `GET /api/v1/tenants/{tenant_id}/directory/sync-status` */
  async getSyncStatus(): Promise<models.DirectorySyncStatus> {
    const tenantId = resolveTenant(this.#client, this.#scope, "directory.get_sync_status");
    const wire = await sendManagement<models.DirectorySyncStatus>(this.#client, {
      operation: 'directory.get_sync_status',
      method: 'GET',
      pathTemplate: '/api/v1/tenants/{tenant_id}/directory/sync-status',
      path: `/api/v1/tenants/${tenantId}/directory/sync-status`,
    });
    return models.scrubDirectorySyncStatus(wire);
  }

}
