// @generated by scripts/gen-management.mjs from management-registry.json and
// openapi.json. DO NOT EDIT — your changes will be overwritten. Regenerate with
// `node scripts/gen-management.mjs`; CI verifies the committed output is current.

/**
 * The `directory` management namespace (CONTRACT §27.1).
 *
 * A tenant's LDAP / Active Directory identity source (CONTRACT §30): the one
 * configuration, the explicit act that links an existing local account to
 * its directory entry, and a read-only view of the sync job. Signing in
 * needs nothing new -- a directory account calls the same §1 `login`.
 */

import type { AxiamClient } from '../../rest/client.js';
import * as models from '../models.js';
import { sendManagement } from '../request.js';
import type { NamespaceScope } from '../scope.js';
import { resolveOrg, resolveTenant } from '../scope.js';

/**
 * The `directory` namespace handle.
 *
 * A tenant's LDAP / Active Directory identity source (CONTRACT §30): the one
 * configuration, the explicit act that links an existing local account to
 * its directory entry, and a read-only view of the sync job. Signing in
 * needs nothing new -- a directory account calls the same §1 `login`.
 *
 * Acquiring one performs no I/O and allocates nothing meaningful (§27.2 rule
 * 1); it holds the client and cannot be constructed without one.
 */
export class DirectoryApi {
  readonly #client: AxiamClient;
  readonly #scope: NamespaceScope;

  /** @internal — reached through `client.<namespace>`, never constructed directly. */
  constructor(client: AxiamClient, scope: NamespaceScope = {}) {
    this.#client = client;
    this.#scope = scope;
  }

  /**
   * Address a different tenant than the client's own (§27.4 rule 3).
   *
   * Returns a new handle; the original is unchanged.
   */
  forTenant(tenantId: string): DirectoryApi {
    return new DirectoryApi(this.#client, { ...this.#scope, tenantId });
  }

  /** `GET /api/v1/tenants/{tenant_id}/directory` */
  async get(): Promise<models.DirectoryConfig> {
    const tenantId = resolveTenant(this.#client, this.#scope, "directory.get");
    const wire = await sendManagement<models.DirectoryConfig>(this.#client, {
      operation: 'directory.get',
      method: 'GET',
      pathTemplate: '/api/v1/tenants/{tenant_id}/directory',
      path: `/api/v1/tenants/${tenantId}/directory`,
    });
    return wire;
  }

  /**
   * `PUT /api/v1/tenants/{tenant_id}/directory`
   *
   * **This is a replacement, not a patch** (§27.4 rule 5). Every field of the
   * body is required, and what you do not carry over from a prior read is not
   * preserved — it is overwritten. Read first, change the field you mean, send
   * the whole thing back.
   *
   * Not retried on failure (§27.4 rule 8): every write on this surface is
   * issued exactly once, including the ones that look idempotent.
   */
  async set(body: models.SetDirectoryConfig): Promise<models.DirectoryConfig> {
    const tenantId = resolveTenant(this.#client, this.#scope, "directory.set");
    const wire = await sendManagement<models.DirectoryConfig>(this.#client, {
      operation: 'directory.set',
      method: 'PUT',
      pathTemplate: '/api/v1/tenants/{tenant_id}/directory',
      path: `/api/v1/tenants/${tenantId}/directory`,
      body: models.setDirectoryConfigToWire(body),
    });
    return wire;
  }

  /**
   * `PATCH /api/v1/tenants/{tenant_id}/directory`
   *
   * Not retried on failure (§27.4 rule 8): every write on this surface is
   * issued exactly once, including the ones that look idempotent.
   */
  async update(body: models.UpdateDirectoryConfig): Promise<models.DirectoryConfig> {
    const tenantId = resolveTenant(this.#client, this.#scope, "directory.update");
    const wire = await sendManagement<models.DirectoryConfig>(this.#client, {
      operation: 'directory.update',
      method: 'PATCH',
      pathTemplate: '/api/v1/tenants/{tenant_id}/directory',
      path: `/api/v1/tenants/${tenantId}/directory`,
      body: models.updateDirectoryConfigToWire(body),
    });
    return wire;
  }

  /**
   * `DELETE /api/v1/tenants/{tenant_id}/directory`
   *
   * Not retried on failure (§27.4 rule 8): every write on this surface is
   * issued exactly once, including the ones that look idempotent.
   */
  async delete(): Promise<void> {
    const tenantId = resolveTenant(this.#client, this.#scope, "directory.delete");
    await sendManagement<void>(this.#client, {
      operation: 'directory.delete',
      method: 'DELETE',
      pathTemplate: '/api/v1/tenants/{tenant_id}/directory',
      path: `/api/v1/tenants/${tenantId}/directory`,
    });
  }

  /**
   * `POST /api/v1/tenants/{tenant_id}/directory/links`
   *
   * Not retried on failure (§27.4 rule 8): every write on this surface is
   * issued exactly once, including the ones that look idempotent.
   */
  async linkAccount(body: models.LinkDirectoryAccount): Promise<models.DirectoryLinkResult> {
    const tenantId = resolveTenant(this.#client, this.#scope, "directory.link_account");
    const wire = await sendManagement<models.DirectoryLinkResult>(this.#client, {
      operation: 'directory.link_account',
      method: 'POST',
      pathTemplate: '/api/v1/tenants/{tenant_id}/directory/links',
      path: `/api/v1/tenants/${tenantId}/directory/links`,
      body: body,
    });
    return wire;
  }

  /** `GET /api/v1/tenants/{tenant_id}/directory/sync-status` */
  async getSyncStatus(): Promise<models.DirectorySyncStatus> {
    const tenantId = resolveTenant(this.#client, this.#scope, "directory.get_sync_status");
    const wire = await sendManagement<models.DirectorySyncStatus>(this.#client, {
      operation: 'directory.get_sync_status',
      method: 'GET',
      pathTemplate: '/api/v1/tenants/{tenant_id}/directory/sync-status',
      path: `/api/v1/tenants/${tenantId}/directory/sync-status`,
    });
    return wire;
  }

}
