// @generated by scripts/gen-management.mjs from management-registry.json and
// openapi.json. DO NOT EDIT — your changes will be overwritten. Regenerate with
// `node scripts/gen-management.mjs`; CI verifies the committed output is current.

/**
 * The `email_config` management namespace (CONTRACT §27.1).
 *
 * Transactional-mail transport, configurable at organization level and
 * overridable per tenant.
 */

import type { AxiamClient } from '../../rest/client.js';
import * as models from '../models.js';
import { sendManagement } from '../request.js';
import type { Scope } from '../scope.js';
import { resolveOrg, resolveTenant } from '../scope.js';

/**
 * The `email_config` namespace handle.
 *
 * Transactional-mail transport, configurable at organization level and
 * overridable per tenant.
 *
 * Acquiring one performs no I/O and allocates nothing meaningful (§27.2 rule
 * 1); it holds the client and cannot be constructed without one.
 */
export class EmailConfigApi {
  readonly #client: AxiamClient;
  readonly #scope: Scope;

  /** @internal — reached through `client.<namespace>`, never constructed directly. */
  constructor(client: AxiamClient, scope: Scope = {}) {
    this.#client = client;
    this.#scope = scope;
  }

  /**
   * Address a different organization than the client's own.
   *
   * §27.4 rule 3: the client's `orgId` is the default, and a platform-admin
   * token legitimately overrides it. Returns a new handle; the original is
   * unchanged.
   */
  inOrg(orgId: string): EmailConfigApi {
    return new EmailConfigApi(this.#client, { ...this.#scope, orgId });
  }

  /**
   * Address a different tenant than the client's own (§27.4 rule 3).
   *
   * Returns a new handle; the original is unchanged.
   */
  forTenant(tenantId: string): EmailConfigApi {
    return new EmailConfigApi(this.#client, { ...this.#scope, tenantId });
  }

  /** `GET /api/v1/organizations/{org_id}/email-config` */
  async getOrg(): Promise<models.EmailConfig> {
    const orgId = resolveOrg(this.#client, this.#scope, "email_config.get_org");
    const wire = await sendManagement<models.EmailConfig>(this.#client, {
      operation: 'email_config.get_org',
      method: 'GET',
      pathTemplate: '/api/v1/organizations/{org_id}/email-config',
      path: `/api/v1/organizations/${orgId}/email-config`,
    });
    return wire;
  }

  /**
   * `PUT /api/v1/organizations/{org_id}/email-config`
   *
   * **This is a replacement, not a patch** (§27.4 rule 5). Every field of the
   * body is required, and what you do not carry over from a prior read is not
   * preserved — it is overwritten. Read first, change the field you mean, send
   * the whole thing back.
   *
   * Not retried on failure (§27.4 rule 8): every write on this surface is
   * issued exactly once, including the ones that look idempotent.
   */
  async setOrg(body: models.SetOrgEmailConfig): Promise<models.EmailConfig> {
    const orgId = resolveOrg(this.#client, this.#scope, "email_config.set_org");
    const wire = await sendManagement<models.EmailConfig>(this.#client, {
      operation: 'email_config.set_org',
      method: 'PUT',
      pathTemplate: '/api/v1/organizations/{org_id}/email-config',
      path: `/api/v1/organizations/${orgId}/email-config`,
      body: body,
    });
    return wire;
  }

  /**
   * `DELETE /api/v1/organizations/{org_id}/email-config`
   *
   * Not retried on failure (§27.4 rule 8): every write on this surface is
   * issued exactly once, including the ones that look idempotent.
   */
  async deleteOrg(): Promise<void> {
    const orgId = resolveOrg(this.#client, this.#scope, "email_config.delete_org");
    await sendManagement<void>(this.#client, {
      operation: 'email_config.delete_org',
      method: 'DELETE',
      pathTemplate: '/api/v1/organizations/{org_id}/email-config',
      path: `/api/v1/organizations/${orgId}/email-config`,
    });
  }

  /**
   * `POST /api/v1/organizations/{org_id}/email-config/test`
   *
   * Not retried on failure (§27.4 rule 8): every write on this surface is
   * issued exactly once, including the ones that look idempotent.
   */
  async testOrg(): Promise<models.EmailTestResult> {
    const orgId = resolveOrg(this.#client, this.#scope, "email_config.test_org");
    const wire = await sendManagement<models.EmailTestResult>(this.#client, {
      operation: 'email_config.test_org',
      method: 'POST',
      pathTemplate: '/api/v1/organizations/{org_id}/email-config/test',
      path: `/api/v1/organizations/${orgId}/email-config/test`,
    });
    return wire;
  }

  /** `GET /api/v1/tenants/{tenant_id}/email-config` */
  async getTenant(): Promise<models.EmailConfigOverride> {
    const tenantId = resolveTenant(this.#client, this.#scope, "email_config.get_tenant");
    const wire = await sendManagement<models.EmailConfigOverride>(this.#client, {
      operation: 'email_config.get_tenant',
      method: 'GET',
      pathTemplate: '/api/v1/tenants/{tenant_id}/email-config',
      path: `/api/v1/tenants/${tenantId}/email-config`,
    });
    return wire;
  }

  /**
   * `PUT /api/v1/tenants/{tenant_id}/email-config`
   *
   * Not retried on failure (§27.4 rule 8): every write on this surface is
   * issued exactly once, including the ones that look idempotent.
   */
  async setTenant(body: models.EmailConfigOverride): Promise<models.EmailConfigOverride> {
    const tenantId = resolveTenant(this.#client, this.#scope, "email_config.set_tenant");
    const wire = await sendManagement<models.EmailConfigOverride>(this.#client, {
      operation: 'email_config.set_tenant',
      method: 'PUT',
      pathTemplate: '/api/v1/tenants/{tenant_id}/email-config',
      path: `/api/v1/tenants/${tenantId}/email-config`,
      body: body,
    });
    return wire;
  }

  /**
   * `DELETE /api/v1/tenants/{tenant_id}/email-config`
   *
   * Not retried on failure (§27.4 rule 8): every write on this surface is
   * issued exactly once, including the ones that look idempotent.
   */
  async deleteTenant(): Promise<void> {
    const tenantId = resolveTenant(this.#client, this.#scope, "email_config.delete_tenant");
    await sendManagement<void>(this.#client, {
      operation: 'email_config.delete_tenant',
      method: 'DELETE',
      pathTemplate: '/api/v1/tenants/{tenant_id}/email-config',
      path: `/api/v1/tenants/${tenantId}/email-config`,
    });
  }

  /**
   * `POST /api/v1/tenants/{tenant_id}/email-config/test`
   *
   * Not retried on failure (§27.4 rule 8): every write on this surface is
   * issued exactly once, including the ones that look idempotent.
   */
  async testTenant(): Promise<models.EmailTestResult> {
    const tenantId = resolveTenant(this.#client, this.#scope, "email_config.test_tenant");
    const wire = await sendManagement<models.EmailTestResult>(this.#client, {
      operation: 'email_config.test_tenant',
      method: 'POST',
      pathTemplate: '/api/v1/tenants/{tenant_id}/email-config/test',
      path: `/api/v1/tenants/${tenantId}/email-config/test`,
    });
    return wire;
  }

}
