// @generated by scripts/gen-management.mjs from management-registry.json and
// openapi.json. DO NOT EDIT — your changes will be overwritten. Regenerate with
// `node scripts/gen-management.mjs`; CI verifies the committed output is current.

/**
 * The `federation` management namespace (CONTRACT §27.1).
 *
 * Upstream IdP configuration and the per-user links it produces.
 */

import type { AxiamClient } from '../../rest/client.js';
import * as models from '../models.js';
import type { Page, PageRequest } from '../page.js';
import { collectPages, pageQuery } from '../page.js';
import { sendManagement } from '../request.js';
import type { NamespaceScope } from '../scope.js';

/**
 * The `federation` namespace handle.
 *
 * Upstream IdP configuration and the per-user links it produces.
 *
 * Acquiring one performs no I/O and allocates nothing meaningful (§27.2 rule
 * 1); it holds the client and cannot be constructed without one.
 */
export class FederationApi {
  readonly #client: AxiamClient;
  readonly #scope: NamespaceScope;

  /** @internal — reached through `client.<namespace>`, never constructed directly. */
  constructor(client: AxiamClient, scope: NamespaceScope = {}) {
    this.#client = client;
    this.#scope = scope;
  }

  /** `GET /api/v1/federation-configs` */
  async listConfigs(page: PageRequest = {}): Promise<Page<models.FederationConfigResponse>> {
    const wire = await sendManagement<Page<models.FederationConfigResponse>>(this.#client, {
      operation: 'federation.list_configs',
      method: 'GET',
      pathTemplate: '/api/v1/federation-configs',
      path: '/api/v1/federation-configs',
      query: { ...pageQuery(page) },
    });
    return wire;
  }

  /**
   * Walk `federation.list_configs` to exhaustion, concatenating every page.
   *
   * The auto-paging form §27.4 rule 4 requires. It stops on an empty page even
   * if `total` disagrees, so a misreporting server costs one wasted request
   * rather than an unbounded loop.
   */
  listConfigsAll(start: PageRequest = {}): Promise<models.FederationConfigResponse[]> {
    return collectPages(start, (p) => this.listConfigs(p));
  }

  /**
   * `POST /api/v1/federation-configs`
   *
   * Not retried on failure (§27.4 rule 8): every write on this surface is
   * issued exactly once, including the ones that look idempotent.
   */
  async createConfig(body: models.CreateFederationConfigRequest): Promise<models.FederationConfigResponse> {
    const wire = await sendManagement<models.FederationConfigResponse>(this.#client, {
      operation: 'federation.create_config',
      method: 'POST',
      pathTemplate: '/api/v1/federation-configs',
      path: '/api/v1/federation-configs',
      body: models.createFederationConfigRequestToWire(body),
    });
    return wire;
  }

  /** `GET /api/v1/federation-configs/{id}` */
  async getConfig(id: string): Promise<models.FederationConfigResponse> {
    const wire = await sendManagement<models.FederationConfigResponse>(this.#client, {
      operation: 'federation.get_config',
      method: 'GET',
      pathTemplate: '/api/v1/federation-configs/{id}',
      path: `/api/v1/federation-configs/${encodeURIComponent(id)}`,
    });
    return wire;
  }

  /**
   * `PUT /api/v1/federation-configs/{id}`
   *
   * Not retried on failure (§27.4 rule 8): every write on this surface is
   * issued exactly once, including the ones that look idempotent.
   */
  async updateConfig(id: string, body: models.UpdateFederationConfigRequest): Promise<models.FederationConfigResponse> {
    const wire = await sendManagement<models.FederationConfigResponse>(this.#client, {
      operation: 'federation.update_config',
      method: 'PUT',
      pathTemplate: '/api/v1/federation-configs/{id}',
      path: `/api/v1/federation-configs/${encodeURIComponent(id)}`,
      body: models.updateFederationConfigRequestToWire(body),
    });
    return wire;
  }

  /**
   * `DELETE /api/v1/federation-configs/{id}`
   *
   * Not retried on failure (§27.4 rule 8): every write on this surface is
   * issued exactly once, including the ones that look idempotent.
   */
  async deleteConfig(id: string): Promise<void> {
    await sendManagement<void>(this.#client, {
      operation: 'federation.delete_config',
      method: 'DELETE',
      pathTemplate: '/api/v1/federation-configs/{id}',
      path: `/api/v1/federation-configs/${encodeURIComponent(id)}`,
    });
  }

  /** `GET /api/v1/federation-links/user/{user_id}` */
  async listUserLinks(userId: string): Promise<models.FederationLinkResponse[]> {
    const wire = await sendManagement<models.FederationLinkResponse[]>(this.#client, {
      operation: 'federation.list_user_links',
      method: 'GET',
      pathTemplate: '/api/v1/federation-links/user/{user_id}',
      path: `/api/v1/federation-links/user/${encodeURIComponent(userId)}`,
    });
    return wire;
  }

  /**
   * `DELETE /api/v1/federation-links/{id}`
   *
   * Not retried on failure (§27.4 rule 8): every write on this surface is
   * issued exactly once, including the ones that look idempotent.
   */
  async deleteLink(id: string): Promise<void> {
    await sendManagement<void>(this.#client, {
      operation: 'federation.delete_link',
      method: 'DELETE',
      pathTemplate: '/api/v1/federation-links/{id}',
      path: `/api/v1/federation-links/${encodeURIComponent(id)}`,
    });
  }

  /**
   * `POST /api/v1/federation/oidc/authorize`
   *
   * Not retried on failure (§27.4 rule 8): every write on this surface is
   * issued exactly once, including the ones that look idempotent.
   */
  async oidcAuthorize(body: models.OidcAuthorizeRequest): Promise<models.OidcAuthorizeResponse> {
    const wire = await sendManagement<models.OidcAuthorizeResponse>(this.#client, {
      operation: 'federation.oidc_authorize',
      method: 'POST',
      pathTemplate: '/api/v1/federation/oidc/authorize',
      path: '/api/v1/federation/oidc/authorize',
      body: body,
    });
    return wire;
  }

  /**
   * `POST /api/v1/federation/oidc/callback`
   *
   * Not retried on failure (§27.4 rule 8): every write on this surface is
   * issued exactly once, including the ones that look idempotent.
   */
  async oidcCallback(body: models.OidcCallbackRequest): Promise<models.OidcCallbackResponse> {
    const wire = await sendManagement<models.OidcCallbackResponse>(this.#client, {
      operation: 'federation.oidc_callback',
      method: 'POST',
      pathTemplate: '/api/v1/federation/oidc/callback',
      path: '/api/v1/federation/oidc/callback',
      body: body,
    });
    return wire;
  }

}
