// @generated by scripts/gen-management.mjs from management-registry.json and
// openapi.json. DO NOT EDIT — your changes will be overwritten. Regenerate with
// `node scripts/gen-management.mjs`; CI verifies the committed output is current.

/**
 * The `groups` management namespace (CONTRACT §27.1).
 *
 * Named collections of users. Roles assigned to a group are inherited by
 * every member.
 */

import type { AxiamClient } from '../../rest/client.js';
import * as models from '../models.js';
import type { Page, PageRequest } from '../page.js';
import { collectPages, pageQuery } from '../page.js';
import { sendManagement } from '../request.js';
import type { NamespaceScope } from '../scope.js';

/**
 * The `groups` namespace handle.
 *
 * Named collections of users. Roles assigned to a group are inherited by
 * every member.
 *
 * Acquiring one performs no I/O and allocates nothing meaningful (§27.2 rule
 * 1); it holds the client and cannot be constructed without one.
 */
export class GroupsApi {
  readonly #client: AxiamClient;
  readonly #scope: NamespaceScope;

  /** @internal — reached through `client.<namespace>`, never constructed directly. */
  constructor(client: AxiamClient, scope: NamespaceScope = {}) {
    this.#client = client;
    this.#scope = scope;
  }

  /** `GET /api/v1/groups` */
  async list(page: PageRequest = {}): Promise<Page<models.Group>> {
    const wire = await sendManagement<Page<models.Group>>(this.#client, {
      operation: 'groups.list',
      method: 'GET',
      pathTemplate: '/api/v1/groups',
      path: '/api/v1/groups',
      query: { ...pageQuery(page) },
    });
    return wire;
  }

  /**
   * Walk `groups.list` to exhaustion, concatenating every page.
   *
   * The auto-paging form §27.4 rule 4 requires. It stops on an empty page even
   * if `total` disagrees, so a misreporting server costs one wasted request
   * rather than an unbounded loop.
   */
  listAll(start: PageRequest = {}): Promise<models.Group[]> {
    return collectPages(start, (p) => this.list(p));
  }

  /**
   * `POST /api/v1/groups`
   *
   * Not retried on failure (§27.4 rule 8): every write on this surface is
   * issued exactly once, including the ones that look idempotent.
   */
  async create(body: models.CreateGroupRequest): Promise<models.Group> {
    const wire = await sendManagement<models.Group>(this.#client, {
      operation: 'groups.create',
      method: 'POST',
      pathTemplate: '/api/v1/groups',
      path: '/api/v1/groups',
      body: body,
    });
    return wire;
  }

  /** `GET /api/v1/groups/{group_id}` */
  async get(groupId: string): Promise<models.Group> {
    const wire = await sendManagement<models.Group>(this.#client, {
      operation: 'groups.get',
      method: 'GET',
      pathTemplate: '/api/v1/groups/{group_id}',
      path: `/api/v1/groups/${encodeURIComponent(groupId)}`,
    });
    return wire;
  }

  /**
   * `PUT /api/v1/groups/{group_id}`
   *
   * Not retried on failure (§27.4 rule 8): every write on this surface is
   * issued exactly once, including the ones that look idempotent.
   */
  async update(groupId: string, body: models.UpdateGroup): Promise<models.Group> {
    const wire = await sendManagement<models.Group>(this.#client, {
      operation: 'groups.update',
      method: 'PUT',
      pathTemplate: '/api/v1/groups/{group_id}',
      path: `/api/v1/groups/${encodeURIComponent(groupId)}`,
      body: body,
    });
    return wire;
  }

  /**
   * `DELETE /api/v1/groups/{group_id}`
   *
   * Not retried on failure (§27.4 rule 8): every write on this surface is
   * issued exactly once, including the ones that look idempotent.
   */
  async delete(groupId: string): Promise<void> {
    await sendManagement<void>(this.#client, {
      operation: 'groups.delete',
      method: 'DELETE',
      pathTemplate: '/api/v1/groups/{group_id}',
      path: `/api/v1/groups/${encodeURIComponent(groupId)}`,
    });
  }

  /** `GET /api/v1/groups/{group_id}/members` */
  async listMembers(groupId: string, page: PageRequest = {}): Promise<Page<models.UserResponse>> {
    const wire = await sendManagement<Page<models.UserResponse>>(this.#client, {
      operation: 'groups.list_members',
      method: 'GET',
      pathTemplate: '/api/v1/groups/{group_id}/members',
      path: `/api/v1/groups/${encodeURIComponent(groupId)}/members`,
      query: { ...pageQuery(page) },
    });
    return wire;
  }

  /**
   * Walk `groups.list_members` to exhaustion, concatenating every page.
   *
   * The auto-paging form §27.4 rule 4 requires. It stops on an empty page even
   * if `total` disagrees, so a misreporting server costs one wasted request
   * rather than an unbounded loop.
   */
  listMembersAll(groupId: string, start: PageRequest = {}): Promise<models.UserResponse[]> {
    return collectPages(start, (p) => this.listMembers(groupId, p));
  }

  /**
   * `POST /api/v1/groups/{group_id}/members`
   *
   * Not retried on failure (§27.4 rule 8): every write on this surface is
   * issued exactly once, including the ones that look idempotent.
   */
  async addMember(groupId: string, body: models.AddMemberRequest): Promise<void> {
    await sendManagement<void>(this.#client, {
      operation: 'groups.add_member',
      method: 'POST',
      pathTemplate: '/api/v1/groups/{group_id}/members',
      path: `/api/v1/groups/${encodeURIComponent(groupId)}/members`,
      body: body,
    });
  }

  /**
   * `DELETE /api/v1/groups/{group_id}/members/{user_id}`
   *
   * Not retried on failure (§27.4 rule 8): every write on this surface is
   * issued exactly once, including the ones that look idempotent.
   */
  async removeMember(groupId: string, userId: string): Promise<void> {
    await sendManagement<void>(this.#client, {
      operation: 'groups.remove_member',
      method: 'DELETE',
      pathTemplate: '/api/v1/groups/{group_id}/members/{user_id}',
      path: `/api/v1/groups/${encodeURIComponent(groupId)}/members/${encodeURIComponent(userId)}`,
    });
  }

  /** `GET /api/v1/groups/{group_id}/roles` */
  async listRoles(groupId: string): Promise<models.RoleAssignment[]> {
    const wire = await sendManagement<models.RoleAssignment[]>(this.#client, {
      operation: 'groups.list_roles',
      method: 'GET',
      pathTemplate: '/api/v1/groups/{group_id}/roles',
      path: `/api/v1/groups/${encodeURIComponent(groupId)}/roles`,
    });
    return wire;
  }

  /** `GET /api/v1/groups/{group_id}/service-accounts` */
  async listServiceAccounts(groupId: string, page: PageRequest = {}): Promise<Page<models.ServiceAccountResponse>> {
    const wire = await sendManagement<Page<models.ServiceAccountResponse>>(this.#client, {
      operation: 'groups.list_service_accounts',
      method: 'GET',
      pathTemplate: '/api/v1/groups/{group_id}/service-accounts',
      path: `/api/v1/groups/${encodeURIComponent(groupId)}/service-accounts`,
      query: { ...pageQuery(page) },
    });
    return wire;
  }

  /**
   * Walk `groups.list_service_accounts` to exhaustion, concatenating every
   * page.
   *
   * The auto-paging form §27.4 rule 4 requires. It stops on an empty page even
   * if `total` disagrees, so a misreporting server costs one wasted request
   * rather than an unbounded loop.
   */
  listServiceAccountsAll(groupId: string, start: PageRequest = {}): Promise<models.ServiceAccountResponse[]> {
    return collectPages(start, (p) => this.listServiceAccounts(groupId, p));
  }

  /**
   * `POST /api/v1/groups/{group_id}/service-accounts`
   *
   * Not retried on failure (§27.4 rule 8): every write on this surface is
   * issued exactly once, including the ones that look idempotent.
   */
  async addServiceAccount(groupId: string, body: models.AddServiceAccountMemberRequest): Promise<void> {
    await sendManagement<void>(this.#client, {
      operation: 'groups.add_service_account',
      method: 'POST',
      pathTemplate: '/api/v1/groups/{group_id}/service-accounts',
      path: `/api/v1/groups/${encodeURIComponent(groupId)}/service-accounts`,
      body: body,
    });
  }

  /**
   * `DELETE /api/v1/groups/{group_id}/service-accounts/{service_account_id}`
   *
   * Not retried on failure (§27.4 rule 8): every write on this surface is
   * issued exactly once, including the ones that look idempotent.
   */
  async removeServiceAccount(groupId: string, serviceAccountId: string): Promise<void> {
    await sendManagement<void>(this.#client, {
      operation: 'groups.remove_service_account',
      method: 'DELETE',
      pathTemplate: '/api/v1/groups/{group_id}/service-accounts/{service_account_id}',
      path: `/api/v1/groups/${encodeURIComponent(groupId)}/service-accounts/${encodeURIComponent(serviceAccountId)}`,
    });
  }

}
