// @generated by scripts/gen-management.mjs from management-registry.json and
// openapi.json. DO NOT EDIT — your changes will be overwritten. Regenerate with
// `node scripts/gen-management.mjs`; CI verifies the committed output is current.

/**
 * One handle per §27 namespace, and the accessors that reach them.
 *
 * §27.2 makes this namespacing normative rather than stylistic: twenty
 * namespaces have a `list` and fourteen a `get`, so flattening 147 operations
 * onto the client would need a disambiguating prefix invented once per
 * operation — and would bury the eight §1 methods most callers actually want
 * under five times as many they do not.
 */

export * from './organizations.js';
export * from './tenants.js';
export * from './users.js';
export * from './groups.js';
export * from './roles.js';
export * from './permissions.js';
export * from './resources.js';
export * from './scopes.js';
export * from './service_accounts.js';
export * from './certificates.js';
export * from './ca_certificates.js';
export * from './pgp_keys.js';
export * from './webhooks.js';
export * from './oauth2_clients.js';
export * from './federation.js';
export * from './notification_rules.js';
export * from './email_config.js';
export * from './settings.js';
export * from './scim_tokens.js';
export * from './reactors.js';
export * from './webauthn_policy.js';
export * from './audit.js';
export * from './privacy.js';
export * from './platform.js';

import { OrganizationsApi } from './organizations.js';
import { TenantsApi } from './tenants.js';
import { UsersApi } from './users.js';
import { GroupsApi } from './groups.js';
import { RolesApi } from './roles.js';
import { PermissionsApi } from './permissions.js';
import { ResourcesApi } from './resources.js';
import { ScopesApi } from './scopes.js';
import { ServiceAccountsApi } from './service_accounts.js';
import { CertificatesApi } from './certificates.js';
import { CaCertificatesApi } from './ca_certificates.js';
import { PgpKeysApi } from './pgp_keys.js';
import { WebhooksApi } from './webhooks.js';
import { Oauth2ClientsApi } from './oauth2_clients.js';
import { FederationApi } from './federation.js';
import { NotificationRulesApi } from './notification_rules.js';
import { EmailConfigApi } from './email_config.js';
import { SettingsApi } from './settings.js';
import { ScimTokensApi } from './scim_tokens.js';
import { ReactorsApi } from './reactors.js';
import { WebauthnPolicyApi } from './webauthn_policy.js';
import { AuditApi } from './audit.js';
import { PrivacyApi } from './privacy.js';
import { PlatformApi } from './platform.js';
import type { AxiamClient } from '../../rest/client.js';

/** Every §27 namespace handle, lazily constructed per access. */
export interface ManagementNamespaces {
  /**
   * Organizations an SDK client may read and configure. Creation and deletion
   * are outside the SDK boundary (§27.0).
   */
  readonly organizations: OrganizationsApi;
  /**
   * Tenants within an organization -- the isolation boundary every other
   * namespace is scoped to.
   */
  readonly tenants: TenantsApi;
  /**
   * Users within the client's tenant, and the administrative side of their
   * second factor and lockout state.
   */
  readonly users: UsersApi;
  /**
   * Named collections of users. Roles assigned to a group are inherited by
   * every member.
   */
  readonly groups: GroupsApi;
  /** Roles, their permission sets, and their assignment to users and groups. */
  readonly roles: RolesApi;
  /** Permissions -- an action on a resource, optionally narrowed by a scope. */
  readonly permissions: PermissionsApi;
  /** The resource hierarchy role assignments cascade down. */
  readonly resources: ResourcesApi;
  /** Sub-resource granularity, always addressed under their resource. */
  readonly scopes: ScopesApi;
  /**
   * Machine identities, their secrets, and the certificate a device-bound one
   * authenticates with.
   */
  readonly serviceAccounts: ServiceAccountsApi;
  /**
   * End-entity X.509 certificates -- the ones issued to users, services and
   * IoT devices.
   */
  readonly certificates: CertificatesApi;
  /** Organization CAs and the per-tenant signing CAs chained beneath them. */
  readonly caCertificates: CaCertificatesApi;
  /** OpenPGP keys used for audit signing and encrypted data export. */
  readonly pgpKeys: PgpKeysApi;
  /**
   * Outbound event notifications. Delivery signatures are verified with the
   * §13 helper, which this namespace configures.
   */
  readonly webhooks: WebhooksApi;
  /**
   * Registered OAuth2/OIDC clients -- the registration half of what §12, §21
   * and §26 then speak to.
   */
  readonly oauth2Clients: Oauth2ClientsApi;
  /** Upstream IdP configuration and the per-user links it produces. */
  readonly federation: FederationApi;
  /** Which events raise a notification, and to whom. */
  readonly notificationRules: NotificationRulesApi;
  /**
   * Transactional-mail transport, configurable at organization level and
   * overridable per tenant.
   */
  readonly emailConfig: EmailConfigApi;
  /** Effective settings, and the organization/tenant layers they resolve from. */
  readonly settings: SettingsApi;
  /** Bearer tokens for the SCIM 2.0 provisioning endpoint. */
  readonly scimTokens: ScimTokensApi;
  /**
   * Registration of §22 AMQP extension actors -- the admin surface §22.9
   * describes, which no SDK could previously reach.
   */
  readonly reactors: ReactorsApi;
  /**
   * Per-tenant attestation policy governing the §24 ceremonies, and the
   * compliance report over it.
   */
  readonly webauthnPolicy: WebauthnPolicyApi;
  /** Append-only audit log, read-only by construction. */
  readonly audit: AuditApi;
  /**
   * GDPR self-service: the authenticated account's own export and erasure.
   * Scoped to the caller, never to another user.
   */
  readonly privacy: PrivacyApi;
  /**
   * Deployment-level probes and FIDO metadata state. Unauthenticated where the
   * server leaves them so.
   */
  readonly platform: PlatformApi;
}

/**
 * Build the namespace handles for `client`.
 *
 * @internal — reached as `client.users`, `client.roles`, and so on.
 */
export function managementNamespaces(client: AxiamClient): ManagementNamespaces {
  return {
    get organizations() {
      return new OrganizationsApi(client);
    },
    get tenants() {
      return new TenantsApi(client);
    },
    get users() {
      return new UsersApi(client);
    },
    get groups() {
      return new GroupsApi(client);
    },
    get roles() {
      return new RolesApi(client);
    },
    get permissions() {
      return new PermissionsApi(client);
    },
    get resources() {
      return new ResourcesApi(client);
    },
    get scopes() {
      return new ScopesApi(client);
    },
    get serviceAccounts() {
      return new ServiceAccountsApi(client);
    },
    get certificates() {
      return new CertificatesApi(client);
    },
    get caCertificates() {
      return new CaCertificatesApi(client);
    },
    get pgpKeys() {
      return new PgpKeysApi(client);
    },
    get webhooks() {
      return new WebhooksApi(client);
    },
    get oauth2Clients() {
      return new Oauth2ClientsApi(client);
    },
    get federation() {
      return new FederationApi(client);
    },
    get notificationRules() {
      return new NotificationRulesApi(client);
    },
    get emailConfig() {
      return new EmailConfigApi(client);
    },
    get settings() {
      return new SettingsApi(client);
    },
    get scimTokens() {
      return new ScimTokensApi(client);
    },
    get reactors() {
      return new ReactorsApi(client);
    },
    get webauthnPolicy() {
      return new WebauthnPolicyApi(client);
    },
    get audit() {
      return new AuditApi(client);
    },
    get privacy() {
      return new PrivacyApi(client);
    },
    get platform() {
      return new PlatformApi(client);
    },
  };
}
