// @generated by scripts/gen-management.mjs from management-registry.json and
// openapi.json. DO NOT EDIT — your changes will be overwritten. Regenerate with
// `node scripts/gen-management.mjs`; CI verifies the committed output is current.

/**
 * The `notification_rules` management namespace (CONTRACT §27.1).
 *
 * Which events raise a notification, and to whom.
 */

import type { AxiamClient } from '../../rest/client.js';
import * as models from '../models.js';
import type { Page, PageRequest } from '../page.js';
import { collectPages, pageQuery } from '../page.js';
import { sendManagement } from '../request.js';
import type { Scope } from '../scope.js';

/**
 * The `notification_rules` namespace handle.
 *
 * Which events raise a notification, and to whom.
 *
 * Acquiring one performs no I/O and allocates nothing meaningful (§27.2 rule
 * 1); it holds the client and cannot be constructed without one.
 */
export class NotificationRulesApi {
  readonly #client: AxiamClient;
  readonly #scope: Scope;

  /** @internal — reached through `client.<namespace>`, never constructed directly. */
  constructor(client: AxiamClient, scope: Scope = {}) {
    this.#client = client;
    this.#scope = scope;
  }

  /** `GET /api/v1/notification-rules` */
  async list(page: PageRequest = {}): Promise<Page<models.NotificationRuleResponse>> {
    const wire = await sendManagement<Page<models.NotificationRuleResponse>>(this.#client, {
      operation: 'notification_rules.list',
      method: 'GET',
      pathTemplate: '/api/v1/notification-rules',
      path: '/api/v1/notification-rules',
      query: { ...pageQuery(page) },
    });
    return wire;
  }

  /**
   * Walk `notification_rules.list` to exhaustion, concatenating every page.
   *
   * The auto-paging form §27.4 rule 4 requires. It stops on an empty page even
   * if `total` disagrees, so a misreporting server costs one wasted request
   * rather than an unbounded loop.
   */
  listAll(start: PageRequest = {}): Promise<models.NotificationRuleResponse[]> {
    return collectPages(start, (p) => this.list(p));
  }

  /**
   * `POST /api/v1/notification-rules`
   *
   * Not retried on failure (§27.4 rule 8): every write on this surface is
   * issued exactly once, including the ones that look idempotent.
   */
  async create(body: models.CreateNotificationRuleRequest): Promise<models.NotificationRuleResponse> {
    const wire = await sendManagement<models.NotificationRuleResponse>(this.#client, {
      operation: 'notification_rules.create',
      method: 'POST',
      pathTemplate: '/api/v1/notification-rules',
      path: '/api/v1/notification-rules',
      body: body,
    });
    return wire;
  }

  /** `GET /api/v1/notification-rules/{id}` */
  async get(id: string): Promise<models.NotificationRuleResponse> {
    const wire = await sendManagement<models.NotificationRuleResponse>(this.#client, {
      operation: 'notification_rules.get',
      method: 'GET',
      pathTemplate: '/api/v1/notification-rules/{id}',
      path: `/api/v1/notification-rules/${encodeURIComponent(id)}`,
    });
    return wire;
  }

  /**
   * `PUT /api/v1/notification-rules/{id}`
   *
   * Not retried on failure (§27.4 rule 8): every write on this surface is
   * issued exactly once, including the ones that look idempotent.
   */
  async update(id: string, body: models.UpdateNotificationRuleRequest): Promise<models.NotificationRuleResponse> {
    const wire = await sendManagement<models.NotificationRuleResponse>(this.#client, {
      operation: 'notification_rules.update',
      method: 'PUT',
      pathTemplate: '/api/v1/notification-rules/{id}',
      path: `/api/v1/notification-rules/${encodeURIComponent(id)}`,
      body: body,
    });
    return wire;
  }

  /**
   * `DELETE /api/v1/notification-rules/{id}`
   *
   * Not retried on failure (§27.4 rule 8): every write on this surface is
   * issued exactly once, including the ones that look idempotent.
   */
  async delete(id: string): Promise<void> {
    await sendManagement<void>(this.#client, {
      operation: 'notification_rules.delete',
      method: 'DELETE',
      pathTemplate: '/api/v1/notification-rules/{id}',
      path: `/api/v1/notification-rules/${encodeURIComponent(id)}`,
    });
  }

}
