// @generated by scripts/gen-management.mjs from management-registry.json and
// openapi.json. DO NOT EDIT — your changes will be overwritten. Regenerate with
// `node scripts/gen-management.mjs`; CI verifies the committed output is current.

/**
 * The `oauth2_clients` management namespace (CONTRACT §27.1).
 *
 * Registered OAuth2/OIDC clients -- the registration half of what §12, §21
 * and §26 then speak to.
 */

import type { AxiamClient } from '../../rest/client.js';
import * as models from '../models.js';
import type { Page, PageRequest } from '../page.js';
import { collectPages, pageQuery } from '../page.js';
import { sendManagement } from '../request.js';
import type { NamespaceScope } from '../scope.js';

/**
 * The `oauth2_clients` namespace handle.
 *
 * Registered OAuth2/OIDC clients -- the registration half of what §12, §21
 * and §26 then speak to.
 *
 * Acquiring one performs no I/O and allocates nothing meaningful (§27.2 rule
 * 1); it holds the client and cannot be constructed without one.
 */
export class Oauth2ClientsApi {
  readonly #client: AxiamClient;
  readonly #scope: NamespaceScope;

  /** @internal — reached through `client.<namespace>`, never constructed directly. */
  constructor(client: AxiamClient, scope: NamespaceScope = {}) {
    this.#client = client;
    this.#scope = scope;
  }

  /** `GET /api/v1/oauth2-clients` */
  async list(page: PageRequest = {}): Promise<Page<models.OAuth2ClientResponse>> {
    const wire = await sendManagement<Page<models.OAuth2ClientResponse>>(this.#client, {
      operation: 'oauth2_clients.list',
      method: 'GET',
      pathTemplate: '/api/v1/oauth2-clients',
      path: '/api/v1/oauth2-clients',
      query: { ...pageQuery(page) },
    });
    return wire;
  }

  /**
   * Walk `oauth2_clients.list` to exhaustion, concatenating every page.
   *
   * The auto-paging form §27.4 rule 4 requires. It stops on an empty page even
   * if `total` disagrees, so a misreporting server costs one wasted request
   * rather than an unbounded loop.
   */
  listAll(start: PageRequest = {}): Promise<models.OAuth2ClientResponse[]> {
    return collectPages(start, (p) => this.list(p));
  }

  /**
   * `POST /api/v1/oauth2-clients`
   *
   * **Returns secret material, once.** `client_secret` is returned by this
   * call and by no other; no later `get` will return it again, and the `get`
   * projection has no field where it was. Discarding the result destroys the
   * credential (§27.5 rule 3).
   *
   * Not retried on failure (§27.4 rule 8): every write on this surface is
   * issued exactly once, including the ones that look idempotent.
   */
  async create(body: models.CreateOAuth2ClientRequest): Promise<models.OAuth2ClientCreatedResponse> {
    const wire = await sendManagement<models.OAuth2ClientCreatedResponseWire>(this.#client, {
      operation: 'oauth2_clients.create',
      method: 'POST',
      pathTemplate: '/api/v1/oauth2-clients',
      path: '/api/v1/oauth2-clients',
      body: body,
    });
    return models.oAuth2ClientCreatedResponseFromWire(wire);
  }

  /** `GET /api/v1/oauth2-clients/{id}` */
  async get(id: string): Promise<models.OAuth2ClientResponse> {
    const wire = await sendManagement<models.OAuth2ClientResponse>(this.#client, {
      operation: 'oauth2_clients.get',
      method: 'GET',
      pathTemplate: '/api/v1/oauth2-clients/{id}',
      path: `/api/v1/oauth2-clients/${encodeURIComponent(id)}`,
    });
    return wire;
  }

  /**
   * `PUT /api/v1/oauth2-clients/{id}`
   *
   * Not retried on failure (§27.4 rule 8): every write on this surface is
   * issued exactly once, including the ones that look idempotent.
   */
  async update(id: string, body: models.UpdateOAuth2ClientRequest): Promise<models.OAuth2ClientResponse> {
    const wire = await sendManagement<models.OAuth2ClientResponse>(this.#client, {
      operation: 'oauth2_clients.update',
      method: 'PUT',
      pathTemplate: '/api/v1/oauth2-clients/{id}',
      path: `/api/v1/oauth2-clients/${encodeURIComponent(id)}`,
      body: body,
    });
    return wire;
  }

  /**
   * `DELETE /api/v1/oauth2-clients/{id}`
   *
   * Not retried on failure (§27.4 rule 8): every write on this surface is
   * issued exactly once, including the ones that look idempotent.
   */
  async delete(id: string): Promise<void> {
    await sendManagement<void>(this.#client, {
      operation: 'oauth2_clients.delete',
      method: 'DELETE',
      pathTemplate: '/api/v1/oauth2-clients/{id}',
      path: `/api/v1/oauth2-clients/${encodeURIComponent(id)}`,
    });
  }

}
