// @generated by scripts/gen-management.mjs from management-registry.json and
// openapi.json. DO NOT EDIT — your changes will be overwritten. Regenerate with
// `node scripts/gen-management.mjs`; CI verifies the committed output is current.

/**
 * The `organizations` management namespace (CONTRACT §27.1).
 *
 * Organizations an SDK client may read and configure. Creation and deletion
 * are outside the SDK boundary (§27.0).
 */

import type { AxiamClient } from '../../rest/client.js';
import * as models from '../models.js';
import type { Page, PageRequest } from '../page.js';
import { collectPages, pageQuery } from '../page.js';
import { sendManagement } from '../request.js';
import type { Scope } from '../scope.js';
import { resolveOrg, resolveTenant } from '../scope.js';

/**
 * The `organizations` namespace handle.
 *
 * Organizations an SDK client may read and configure. Creation and deletion
 * are outside the SDK boundary (§27.0).
 *
 * Acquiring one performs no I/O and allocates nothing meaningful (§27.2 rule
 * 1); it holds the client and cannot be constructed without one.
 */
export class OrganizationsApi {
  readonly #client: AxiamClient;
  readonly #scope: Scope;

  /** @internal — reached through `client.<namespace>`, never constructed directly. */
  constructor(client: AxiamClient, scope: Scope = {}) {
    this.#client = client;
    this.#scope = scope;
  }

  /**
   * Address a different organization than the client's own.
   *
   * §27.4 rule 3: the client's `orgId` is the default, and a platform-admin
   * token legitimately overrides it. Returns a new handle; the original is
   * unchanged.
   */
  inOrg(orgId: string): OrganizationsApi {
    return new OrganizationsApi(this.#client, { ...this.#scope, orgId });
  }

  /** `GET /api/v1/organizations` */
  async list(page: PageRequest = {}): Promise<Page<models.Organization>> {
    const wire = await sendManagement<Page<models.Organization>>(this.#client, {
      operation: 'organizations.list',
      method: 'GET',
      pathTemplate: '/api/v1/organizations',
      path: '/api/v1/organizations',
      query: { ...pageQuery(page) },
    });
    return wire;
  }

  /**
   * Walk `organizations.list` to exhaustion, concatenating every page.
   *
   * The auto-paging form §27.4 rule 4 requires. It stops on an empty page even
   * if `total` disagrees, so a misreporting server costs one wasted request
   * rather than an unbounded loop.
   */
  listAll(start: PageRequest = {}): Promise<models.Organization[]> {
    return collectPages(start, (p) => this.list(p));
  }

  /** `GET /api/v1/organizations/{org_id}` */
  async get(): Promise<models.Organization> {
    const orgId = resolveOrg(this.#client, this.#scope, "organizations.get");
    const wire = await sendManagement<models.Organization>(this.#client, {
      operation: 'organizations.get',
      method: 'GET',
      pathTemplate: '/api/v1/organizations/{org_id}',
      path: `/api/v1/organizations/${orgId}`,
    });
    return wire;
  }

  /**
   * `PUT /api/v1/organizations/{org_id}`
   *
   * Not retried on failure (§27.4 rule 8): every write on this surface is
   * issued exactly once, including the ones that look idempotent.
   */
  async update(body: models.UpdateOrganizationRequest): Promise<models.Organization> {
    const orgId = resolveOrg(this.#client, this.#scope, "organizations.update");
    const wire = await sendManagement<models.Organization>(this.#client, {
      operation: 'organizations.update',
      method: 'PUT',
      pathTemplate: '/api/v1/organizations/{org_id}',
      path: `/api/v1/organizations/${orgId}`,
      body: body,
    });
    return wire;
  }

}
