// @generated by scripts/gen-management.mjs from management-registry.json and
// openapi.json. DO NOT EDIT — your changes will be overwritten. Regenerate with
// `node scripts/gen-management.mjs`; CI verifies the committed output is current.

/**
 * The `permissions` management namespace (CONTRACT §27.1).
 *
 * Permissions -- an action on a resource, optionally narrowed by a scope.
 */

import type { AxiamClient } from '../../rest/client.js';
import * as models from '../models.js';
import type { Page, PageRequest } from '../page.js';
import { collectPages, pageQuery } from '../page.js';
import { sendManagement } from '../request.js';
import type { NamespaceScope } from '../scope.js';

/**
 * The `permissions` namespace handle.
 *
 * Permissions -- an action on a resource, optionally narrowed by a scope.
 *
 * Acquiring one performs no I/O and allocates nothing meaningful (§27.2 rule
 * 1); it holds the client and cannot be constructed without one.
 */
export class PermissionsApi {
  readonly #client: AxiamClient;
  readonly #scope: NamespaceScope;

  /** @internal — reached through `client.<namespace>`, never constructed directly. */
  constructor(client: AxiamClient, scope: NamespaceScope = {}) {
    this.#client = client;
    this.#scope = scope;
  }

  /** `GET /api/v1/permissions` */
  async list(page: PageRequest = {}): Promise<Page<models.Permission>> {
    const wire = await sendManagement<Page<models.Permission>>(this.#client, {
      operation: 'permissions.list',
      method: 'GET',
      pathTemplate: '/api/v1/permissions',
      path: '/api/v1/permissions',
      query: { ...pageQuery(page) },
    });
    return wire;
  }

  /**
   * Walk `permissions.list` to exhaustion, concatenating every page.
   *
   * The auto-paging form §27.4 rule 4 requires. It stops on an empty page even
   * if `total` disagrees, so a misreporting server costs one wasted request
   * rather than an unbounded loop.
   */
  listAll(start: PageRequest = {}): Promise<models.Permission[]> {
    return collectPages(start, (p) => this.list(p));
  }

  /**
   * `POST /api/v1/permissions`
   *
   * Not retried on failure (§27.4 rule 8): every write on this surface is
   * issued exactly once, including the ones that look idempotent.
   */
  async create(body: models.CreatePermissionRequest): Promise<models.Permission> {
    const wire = await sendManagement<models.Permission>(this.#client, {
      operation: 'permissions.create',
      method: 'POST',
      pathTemplate: '/api/v1/permissions',
      path: '/api/v1/permissions',
      body: body,
    });
    return wire;
  }

  /** `GET /api/v1/permissions/{permission_id}` */
  async get(permissionId: string): Promise<models.Permission> {
    const wire = await sendManagement<models.Permission>(this.#client, {
      operation: 'permissions.get',
      method: 'GET',
      pathTemplate: '/api/v1/permissions/{permission_id}',
      path: `/api/v1/permissions/${encodeURIComponent(permissionId)}`,
    });
    return wire;
  }

  /**
   * `PUT /api/v1/permissions/{permission_id}`
   *
   * Not retried on failure (§27.4 rule 8): every write on this surface is
   * issued exactly once, including the ones that look idempotent.
   */
  async update(permissionId: string, body: models.UpdatePermissionRequest): Promise<models.Permission> {
    const wire = await sendManagement<models.Permission>(this.#client, {
      operation: 'permissions.update',
      method: 'PUT',
      pathTemplate: '/api/v1/permissions/{permission_id}',
      path: `/api/v1/permissions/${encodeURIComponent(permissionId)}`,
      body: body,
    });
    return wire;
  }

  /**
   * `DELETE /api/v1/permissions/{permission_id}`
   *
   * Not retried on failure (§27.4 rule 8): every write on this surface is
   * issued exactly once, including the ones that look idempotent.
   */
  async delete(permissionId: string): Promise<void> {
    await sendManagement<void>(this.#client, {
      operation: 'permissions.delete',
      method: 'DELETE',
      pathTemplate: '/api/v1/permissions/{permission_id}',
      path: `/api/v1/permissions/${encodeURIComponent(permissionId)}`,
    });
  }

}
