// @generated by scripts/gen-management.mjs from management-registry.json and
// openapi.json. DO NOT EDIT — your changes will be overwritten. Regenerate with
// `node scripts/gen-management.mjs`; CI verifies the committed output is current.

/**
 * The `pgp_keys` management namespace (CONTRACT §27.1).
 *
 * OpenPGP keys used for audit signing and encrypted data export.
 */

import type { AxiamClient } from '../../rest/client.js';
import * as models from '../models.js';
import type { Page, PageRequest } from '../page.js';
import { collectPages, pageQuery } from '../page.js';
import { sendManagement } from '../request.js';
import type { Scope } from '../scope.js';

/**
 * The `pgp_keys` namespace handle.
 *
 * OpenPGP keys used for audit signing and encrypted data export.
 *
 * Acquiring one performs no I/O and allocates nothing meaningful (§27.2 rule
 * 1); it holds the client and cannot be constructed without one.
 */
export class PgpKeysApi {
  readonly #client: AxiamClient;
  readonly #scope: Scope;

  /** @internal — reached through `client.<namespace>`, never constructed directly. */
  constructor(client: AxiamClient, scope: Scope = {}) {
    this.#client = client;
    this.#scope = scope;
  }

  /** `GET /api/v1/pgp-keys` */
  async list(page: PageRequest = {}): Promise<Page<models.PgpKey>> {
    const wire = await sendManagement<Page<models.PgpKey>>(this.#client, {
      operation: 'pgp_keys.list',
      method: 'GET',
      pathTemplate: '/api/v1/pgp-keys',
      path: '/api/v1/pgp-keys',
      query: { ...pageQuery(page) },
    });
    return wire;
  }

  /**
   * Walk `pgp_keys.list` to exhaustion, concatenating every page.
   *
   * The auto-paging form §27.4 rule 4 requires. It stops on an empty page even
   * if `total` disagrees, so a misreporting server costs one wasted request
   * rather than an unbounded loop.
   */
  listAll(start: PageRequest = {}): Promise<models.PgpKey[]> {
    return collectPages(start, (p) => this.list(p));
  }

  /**
   * `POST /api/v1/pgp-keys`
   *
   * **Returns secret material, once.** `private_key_armored` is returned by
   * this call and by no other; no later `get` will return it again, and the
   * `get` projection has no field where it was. Discarding the result destroys
   * the credential (§27.5 rule 3).
   *
   * Not retried on failure (§27.4 rule 8): every write on this surface is
   * issued exactly once, including the ones that look idempotent.
   */
  async generate(body: models.CreatePgpKeyRequest): Promise<models.GeneratedPgpKey> {
    const wire = await sendManagement<models.GeneratedPgpKeyWire>(this.#client, {
      operation: 'pgp_keys.generate',
      method: 'POST',
      pathTemplate: '/api/v1/pgp-keys',
      path: '/api/v1/pgp-keys',
      body: body,
    });
    return models.generatedPgpKeyFromWire(wire);
  }

  /** `GET /api/v1/pgp-keys/{id}` */
  async get(id: string): Promise<models.PgpKey> {
    const wire = await sendManagement<models.PgpKey>(this.#client, {
      operation: 'pgp_keys.get',
      method: 'GET',
      pathTemplate: '/api/v1/pgp-keys/{id}',
      path: `/api/v1/pgp-keys/${encodeURIComponent(id)}`,
    });
    return wire;
  }

  /**
   * `POST /api/v1/pgp-keys/{id}/revoke`
   *
   * Not retried on failure (§27.4 rule 8): every write on this surface is
   * issued exactly once, including the ones that look idempotent.
   */
  async revoke(id: string): Promise<void> {
    await sendManagement<void>(this.#client, {
      operation: 'pgp_keys.revoke',
      method: 'POST',
      pathTemplate: '/api/v1/pgp-keys/{id}/revoke',
      path: `/api/v1/pgp-keys/${encodeURIComponent(id)}/revoke`,
    });
  }

  /**
   * `POST /api/v1/pgp-keys/{id}/encrypt`
   *
   * Not retried on failure (§27.4 rule 8): every write on this surface is
   * issued exactly once, including the ones that look idempotent.
   */
  async encrypt(id: string, body: models.EncryptRequest): Promise<models.EncryptedExport> {
    const wire = await sendManagement<models.EncryptedExport>(this.#client, {
      operation: 'pgp_keys.encrypt',
      method: 'POST',
      pathTemplate: '/api/v1/pgp-keys/{id}/encrypt',
      path: `/api/v1/pgp-keys/${encodeURIComponent(id)}/encrypt`,
      body: body,
    });
    return wire;
  }

  /**
   * `POST /api/v1/pgp-keys/sign-audit-batch`
   *
   * Not retried on failure (§27.4 rule 8): every write on this surface is
   * issued exactly once, including the ones that look idempotent.
   */
  async signAuditBatch(body: models.SignAuditBatchRequest): Promise<models.SignedAuditBatch> {
    const wire = await sendManagement<models.SignedAuditBatch>(this.#client, {
      operation: 'pgp_keys.sign_audit_batch',
      method: 'POST',
      pathTemplate: '/api/v1/pgp-keys/sign-audit-batch',
      path: '/api/v1/pgp-keys/sign-audit-batch',
      body: body,
    });
    return wire;
  }

}
