// @generated by scripts/gen-management.mjs from management-registry.json and
// openapi.json. DO NOT EDIT — your changes will be overwritten. Regenerate with
// `node scripts/gen-management.mjs`; CI verifies the committed output is current.

/**
 * The `platform` management namespace (CONTRACT §27.1).
 *
 * Deployment-level probes and FIDO metadata state. Unauthenticated where the
 * server leaves them so.
 */

import type { AxiamClient } from '../../rest/client.js';
import * as models from '../models.js';
import { sendManagement } from '../request.js';
import type { NamespaceScope } from '../scope.js';

/**
 * The `platform` namespace handle.
 *
 * Deployment-level probes and FIDO metadata state. Unauthenticated where the
 * server leaves them so.
 *
 * Acquiring one performs no I/O and allocates nothing meaningful (§27.2 rule
 * 1); it holds the client and cannot be constructed without one.
 */
export class PlatformApi {
  readonly #client: AxiamClient;
  readonly #scope: NamespaceScope;

  /** @internal — reached through `client.<namespace>`, never constructed directly. */
  constructor(client: AxiamClient, scope: NamespaceScope = {}) {
    this.#client = client;
    this.#scope = scope;
  }

  /** `GET /health` */
  async health(): Promise<models.HealthResponse> {
    const wire = await sendManagement<models.HealthResponse>(this.#client, {
      operation: 'platform.health',
      method: 'GET',
      pathTemplate: '/health',
      path: '/health',
    });
    return wire;
  }

  /** `GET /ready` */
  async ready(): Promise<models.ReadyResponse> {
    const wire = await sendManagement<models.ReadyResponse>(this.#client, {
      operation: 'platform.ready',
      method: 'GET',
      pathTemplate: '/ready',
      path: '/ready',
    });
    return wire;
  }

  /** `GET /api/v1/mds/status` */
  async mdsStatus(): Promise<models.MdsStatusResponse> {
    const wire = await sendManagement<models.MdsStatusResponse>(this.#client, {
      operation: 'platform.mds_status',
      method: 'GET',
      pathTemplate: '/api/v1/mds/status',
      path: '/api/v1/mds/status',
    });
    return wire;
  }

  /**
   * `POST /api/v1/mds/refresh`
   *
   * Not retried on failure (§27.4 rule 8): every write on this surface is
   * issued exactly once, including the ones that look idempotent.
   */
  async mdsRefresh(): Promise<models.MdsRefreshOutcome> {
    const wire = await sendManagement<models.MdsRefreshOutcome>(this.#client, {
      operation: 'platform.mds_refresh',
      method: 'POST',
      pathTemplate: '/api/v1/mds/refresh',
      path: '/api/v1/mds/refresh',
    });
    return wire;
  }

}
