// @generated by scripts/gen-management.mjs from management-registry.json and
// openapi.json. DO NOT EDIT — your changes will be overwritten. Regenerate with
// `node scripts/gen-management.mjs`; CI verifies the committed output is current.

/**
 * The `privacy` management namespace (CONTRACT §27.1).
 *
 * GDPR self-service: the authenticated account's own export and erasure.
 * Scoped to the caller, never to another user.
 */

import type { AxiamClient } from '../../rest/client.js';
import * as models from '../models.js';
import { sendManagement } from '../request.js';
import type { NamespaceScope } from '../scope.js';

/**
 * The `privacy` namespace handle.
 *
 * GDPR self-service: the authenticated account's own export and erasure.
 * Scoped to the caller, never to another user.
 *
 * Acquiring one performs no I/O and allocates nothing meaningful (§27.2 rule
 * 1); it holds the client and cannot be constructed without one.
 */
export class PrivacyApi {
  readonly #client: AxiamClient;
  readonly #scope: NamespaceScope;

  /** @internal — reached through `client.<namespace>`, never constructed directly. */
  constructor(client: AxiamClient, scope: NamespaceScope = {}) {
    this.#client = client;
    this.#scope = scope;
  }

  /**
   * `POST /api/v1/account/export`
   *
   * Not retried on failure (§27.4 rule 8): every write on this surface is
   * issued exactly once, including the ones that look idempotent.
   */
  async requestExport(body: unknown): Promise<void> {
    await sendManagement<void>(this.#client, {
      operation: 'privacy.request_export',
      method: 'POST',
      pathTemplate: '/api/v1/account/export',
      path: '/api/v1/account/export',
      body: body,
    });
  }

  /** `GET /api/v1/account/export/{token}` */
  async downloadExport(token: string): Promise<void> {
    await sendManagement<void>(this.#client, {
      operation: 'privacy.download_export',
      method: 'GET',
      pathTemplate: '/api/v1/account/export/{token}',
      path: `/api/v1/account/export/${encodeURIComponent(token)}`,
    });
  }

  /**
   * `POST /api/v1/account/delete`
   *
   * Not retried on failure (§27.4 rule 8): every write on this surface is
   * issued exactly once, including the ones that look idempotent.
   */
  async requestDelete(body: unknown): Promise<void> {
    await sendManagement<void>(this.#client, {
      operation: 'privacy.request_delete',
      method: 'POST',
      pathTemplate: '/api/v1/account/delete',
      path: '/api/v1/account/delete',
      body: body,
    });
  }

  /** `GET /api/v1/auth/account/delete/cancel` */
  async cancelDelete(token: string): Promise<void> {
    await sendManagement<void>(this.#client, {
      operation: 'privacy.cancel_delete',
      method: 'GET',
      pathTemplate: '/api/v1/auth/account/delete/cancel',
      path: '/api/v1/auth/account/delete/cancel',
      query: { "token": token },
    });
  }

}
