// @generated by scripts/gen-management.mjs from management-registry.json and
// openapi.json. DO NOT EDIT — your changes will be overwritten. Regenerate with
// `node scripts/gen-management.mjs`; CI verifies the committed output is current.

/**
 * The `reactors` management namespace (CONTRACT §27.1).
 *
 * Registration of §22 AMQP extension actors -- the admin surface §22.9
 * describes, which no SDK could previously reach.
 */

import type { AxiamClient } from '../../rest/client.js';
import * as models from '../models.js';
import type { Page, PageRequest } from '../page.js';
import { collectPages, pageQuery } from '../page.js';
import { sendManagement } from '../request.js';
import type { Scope } from '../scope.js';

/**
 * The `reactors` namespace handle.
 *
 * Registration of §22 AMQP extension actors -- the admin surface §22.9
 * describes, which no SDK could previously reach.
 *
 * Acquiring one performs no I/O and allocates nothing meaningful (§27.2 rule
 * 1); it holds the client and cannot be constructed without one.
 */
export class ReactorsApi {
  readonly #client: AxiamClient;
  readonly #scope: Scope;

  /** @internal — reached through `client.<namespace>`, never constructed directly. */
  constructor(client: AxiamClient, scope: Scope = {}) {
    this.#client = client;
    this.#scope = scope;
  }

  /** `GET /api/v1/reactors` */
  async list(page: PageRequest = {}): Promise<Page<models.ReactorResponse>> {
    const wire = await sendManagement<Page<models.ReactorResponse>>(this.#client, {
      operation: 'reactors.list',
      method: 'GET',
      pathTemplate: '/api/v1/reactors',
      path: '/api/v1/reactors',
      query: { ...pageQuery(page) },
    });
    return wire;
  }

  /**
   * Walk `reactors.list` to exhaustion, concatenating every page.
   *
   * The auto-paging form §27.4 rule 4 requires. It stops on an empty page even
   * if `total` disagrees, so a misreporting server costs one wasted request
   * rather than an unbounded loop.
   */
  listAll(start: PageRequest = {}): Promise<models.ReactorResponse[]> {
    return collectPages(start, (p) => this.list(p));
  }

  /**
   * `POST /api/v1/reactors`
   *
   * Not retried on failure (§27.4 rule 8): every write on this surface is
   * issued exactly once, including the ones that look idempotent.
   */
  async create(body: models.CreateReactorRequest): Promise<models.ReactorResponse> {
    const wire = await sendManagement<models.ReactorResponse>(this.#client, {
      operation: 'reactors.create',
      method: 'POST',
      pathTemplate: '/api/v1/reactors',
      path: '/api/v1/reactors',
      body: body,
    });
    return wire;
  }

  /** `GET /api/v1/reactors/{id}` */
  async get(id: string): Promise<models.ReactorResponse> {
    const wire = await sendManagement<models.ReactorResponse>(this.#client, {
      operation: 'reactors.get',
      method: 'GET',
      pathTemplate: '/api/v1/reactors/{id}',
      path: `/api/v1/reactors/${encodeURIComponent(id)}`,
    });
    return wire;
  }

  /**
   * `PUT /api/v1/reactors/{id}`
   *
   * Not retried on failure (§27.4 rule 8): every write on this surface is
   * issued exactly once, including the ones that look idempotent.
   */
  async update(id: string, body: models.UpdateReactorRequest): Promise<models.ReactorResponse> {
    const wire = await sendManagement<models.ReactorResponse>(this.#client, {
      operation: 'reactors.update',
      method: 'PUT',
      pathTemplate: '/api/v1/reactors/{id}',
      path: `/api/v1/reactors/${encodeURIComponent(id)}`,
      body: body,
    });
    return wire;
  }

  /**
   * `DELETE /api/v1/reactors/{id}`
   *
   * Not retried on failure (§27.4 rule 8): every write on this surface is
   * issued exactly once, including the ones that look idempotent.
   */
  async delete(id: string): Promise<void> {
    await sendManagement<void>(this.#client, {
      operation: 'reactors.delete',
      method: 'DELETE',
      pathTemplate: '/api/v1/reactors/{id}',
      path: `/api/v1/reactors/${encodeURIComponent(id)}`,
    });
  }

  /** `GET /api/v1/reactors/events` */
  async listEvents(): Promise<models.ReactorEventDescriptor[]> {
    const wire = await sendManagement<models.ReactorEventDescriptor[]>(this.#client, {
      operation: 'reactors.list_events',
      method: 'GET',
      pathTemplate: '/api/v1/reactors/events',
      path: '/api/v1/reactors/events',
    });
    return wire;
  }

}
