// @generated by scripts/gen-management.mjs from management-registry.json and
// openapi.json. DO NOT EDIT — your changes will be overwritten. Regenerate with
// `node scripts/gen-management.mjs`; CI verifies the committed output is current.

/**
 * The `resources` management namespace (CONTRACT §27.1).
 *
 * The resource hierarchy role assignments cascade down.
 */

import type { AxiamClient } from '../../rest/client.js';
import * as models from '../models.js';
import type { Page, PageRequest } from '../page.js';
import { collectPages, pageQuery } from '../page.js';
import { sendManagement } from '../request.js';
import type { NamespaceScope } from '../scope.js';

/**
 * The `resources` namespace handle.
 *
 * The resource hierarchy role assignments cascade down.
 *
 * Acquiring one performs no I/O and allocates nothing meaningful (§27.2 rule
 * 1); it holds the client and cannot be constructed without one.
 */
export class ResourcesApi {
  readonly #client: AxiamClient;
  readonly #scope: NamespaceScope;

  /** @internal — reached through `client.<namespace>`, never constructed directly. */
  constructor(client: AxiamClient, scope: NamespaceScope = {}) {
    this.#client = client;
    this.#scope = scope;
  }

  /** `GET /api/v1/resources` */
  async list(page: PageRequest = {}): Promise<Page<models.Resource>> {
    const wire = await sendManagement<Page<models.Resource>>(this.#client, {
      operation: 'resources.list',
      method: 'GET',
      pathTemplate: '/api/v1/resources',
      path: '/api/v1/resources',
      query: { ...pageQuery(page) },
    });
    return wire;
  }

  /**
   * Walk `resources.list` to exhaustion, concatenating every page.
   *
   * The auto-paging form §27.4 rule 4 requires. It stops on an empty page even
   * if `total` disagrees, so a misreporting server costs one wasted request
   * rather than an unbounded loop.
   */
  listAll(start: PageRequest = {}): Promise<models.Resource[]> {
    return collectPages(start, (p) => this.list(p));
  }

  /**
   * `POST /api/v1/resources`
   *
   * Not retried on failure (§27.4 rule 8): every write on this surface is
   * issued exactly once, including the ones that look idempotent.
   */
  async create(body: models.CreateResourceRequest): Promise<models.Resource> {
    const wire = await sendManagement<models.Resource>(this.#client, {
      operation: 'resources.create',
      method: 'POST',
      pathTemplate: '/api/v1/resources',
      path: '/api/v1/resources',
      body: body,
    });
    return wire;
  }

  /** `GET /api/v1/resources/{resource_id}` */
  async get(resourceId: string): Promise<models.Resource> {
    const wire = await sendManagement<models.Resource>(this.#client, {
      operation: 'resources.get',
      method: 'GET',
      pathTemplate: '/api/v1/resources/{resource_id}',
      path: `/api/v1/resources/${encodeURIComponent(resourceId)}`,
    });
    return wire;
  }

  /**
   * `PUT /api/v1/resources/{resource_id}`
   *
   * Not retried on failure (§27.4 rule 8): every write on this surface is
   * issued exactly once, including the ones that look idempotent.
   */
  async update(resourceId: string, body: models.UpdateResourceRequest): Promise<models.Resource> {
    const wire = await sendManagement<models.Resource>(this.#client, {
      operation: 'resources.update',
      method: 'PUT',
      pathTemplate: '/api/v1/resources/{resource_id}',
      path: `/api/v1/resources/${encodeURIComponent(resourceId)}`,
      body: body,
    });
    return wire;
  }

  /**
   * `DELETE /api/v1/resources/{resource_id}`
   *
   * Not retried on failure (§27.4 rule 8): every write on this surface is
   * issued exactly once, including the ones that look idempotent.
   */
  async delete(resourceId: string): Promise<void> {
    await sendManagement<void>(this.#client, {
      operation: 'resources.delete',
      method: 'DELETE',
      pathTemplate: '/api/v1/resources/{resource_id}',
      path: `/api/v1/resources/${encodeURIComponent(resourceId)}`,
    });
  }

  /** `GET /api/v1/resources/{resource_id}/children` */
  async listChildren(resourceId: string): Promise<models.Resource[]> {
    const wire = await sendManagement<models.Resource[]>(this.#client, {
      operation: 'resources.list_children',
      method: 'GET',
      pathTemplate: '/api/v1/resources/{resource_id}/children',
      path: `/api/v1/resources/${encodeURIComponent(resourceId)}/children`,
    });
    return wire;
  }

  /** `GET /api/v1/resources/{resource_id}/ancestors` */
  async listAncestors(resourceId: string): Promise<models.Resource[]> {
    const wire = await sendManagement<models.Resource[]>(this.#client, {
      operation: 'resources.list_ancestors',
      method: 'GET',
      pathTemplate: '/api/v1/resources/{resource_id}/ancestors',
      path: `/api/v1/resources/${encodeURIComponent(resourceId)}/ancestors`,
    });
    return wire;
  }

}
