// @generated by scripts/gen-management.mjs from management-registry.json and
// openapi.json. DO NOT EDIT — your changes will be overwritten. Regenerate with
// `node scripts/gen-management.mjs`; CI verifies the committed output is current.

/**
 * The `roles` management namespace (CONTRACT §27.1).
 *
 * Roles, their permission sets, and their assignment to users and groups.
 */

import type { AxiamClient } from '../../rest/client.js';
import * as models from '../models.js';
import type { Page, PageRequest } from '../page.js';
import { collectPages, pageQuery } from '../page.js';
import { sendManagement } from '../request.js';
import type { NamespaceScope } from '../scope.js';

/**
 * The `roles` namespace handle.
 *
 * Roles, their permission sets, and their assignment to users and groups.
 *
 * Acquiring one performs no I/O and allocates nothing meaningful (§27.2 rule
 * 1); it holds the client and cannot be constructed without one.
 */
export class RolesApi {
  readonly #client: AxiamClient;
  readonly #scope: NamespaceScope;

  /** @internal — reached through `client.<namespace>`, never constructed directly. */
  constructor(client: AxiamClient, scope: NamespaceScope = {}) {
    this.#client = client;
    this.#scope = scope;
  }

  /** `GET /api/v1/roles` */
  async list(page: PageRequest = {}): Promise<Page<models.Role>> {
    const wire = await sendManagement<Page<models.Role>>(this.#client, {
      operation: 'roles.list',
      method: 'GET',
      pathTemplate: '/api/v1/roles',
      path: '/api/v1/roles',
      query: { ...pageQuery(page) },
    });
    return wire;
  }

  /**
   * Walk `roles.list` to exhaustion, concatenating every page.
   *
   * The auto-paging form §27.4 rule 4 requires. It stops on an empty page even
   * if `total` disagrees, so a misreporting server costs one wasted request
   * rather than an unbounded loop.
   */
  listAll(start: PageRequest = {}): Promise<models.Role[]> {
    return collectPages(start, (p) => this.list(p));
  }

  /**
   * `POST /api/v1/roles`
   *
   * Not retried on failure (§27.4 rule 8): every write on this surface is
   * issued exactly once, including the ones that look idempotent.
   */
  async create(body: models.CreateRoleRequest): Promise<models.Role> {
    const wire = await sendManagement<models.Role>(this.#client, {
      operation: 'roles.create',
      method: 'POST',
      pathTemplate: '/api/v1/roles',
      path: '/api/v1/roles',
      body: body,
    });
    return wire;
  }

  /** `GET /api/v1/roles/{role_id}` */
  async get(roleId: string): Promise<models.Role> {
    const wire = await sendManagement<models.Role>(this.#client, {
      operation: 'roles.get',
      method: 'GET',
      pathTemplate: '/api/v1/roles/{role_id}',
      path: `/api/v1/roles/${encodeURIComponent(roleId)}`,
    });
    return wire;
  }

  /**
   * `PUT /api/v1/roles/{role_id}`
   *
   * Not retried on failure (§27.4 rule 8): every write on this surface is
   * issued exactly once, including the ones that look idempotent.
   */
  async update(roleId: string, body: models.UpdateRole): Promise<models.Role> {
    const wire = await sendManagement<models.Role>(this.#client, {
      operation: 'roles.update',
      method: 'PUT',
      pathTemplate: '/api/v1/roles/{role_id}',
      path: `/api/v1/roles/${encodeURIComponent(roleId)}`,
      body: body,
    });
    return wire;
  }

  /**
   * `DELETE /api/v1/roles/{role_id}`
   *
   * Not retried on failure (§27.4 rule 8): every write on this surface is
   * issued exactly once, including the ones that look idempotent.
   */
  async delete(roleId: string): Promise<void> {
    await sendManagement<void>(this.#client, {
      operation: 'roles.delete',
      method: 'DELETE',
      pathTemplate: '/api/v1/roles/{role_id}',
      path: `/api/v1/roles/${encodeURIComponent(roleId)}`,
    });
  }

  /** `GET /api/v1/roles/{role_id}/users` */
  async listUsers(roleId: string): Promise<models.RoleUserAssignment[]> {
    const wire = await sendManagement<models.RoleUserAssignment[]>(this.#client, {
      operation: 'roles.list_users',
      method: 'GET',
      pathTemplate: '/api/v1/roles/{role_id}/users',
      path: `/api/v1/roles/${encodeURIComponent(roleId)}/users`,
    });
    return wire;
  }

  /**
   * `POST /api/v1/roles/{role_id}/users`
   *
   * Not retried on failure (§27.4 rule 8): every write on this surface is
   * issued exactly once, including the ones that look idempotent.
   */
  async assignToUser(roleId: string, body: models.AssignRoleToUserRequest): Promise<void> {
    await sendManagement<void>(this.#client, {
      operation: 'roles.assign_to_user',
      method: 'POST',
      pathTemplate: '/api/v1/roles/{role_id}/users',
      path: `/api/v1/roles/${encodeURIComponent(roleId)}/users`,
      body: body,
    });
  }

  /**
   * `DELETE /api/v1/roles/{role_id}/users/{user_id}`
   *
   * Not retried on failure (§27.4 rule 8): every write on this surface is
   * issued exactly once, including the ones that look idempotent.
   */
  async unassignFromUser(roleId: string, userId: string, resourceId?: string): Promise<void> {
    await sendManagement<void>(this.#client, {
      operation: 'roles.unassign_from_user',
      method: 'DELETE',
      pathTemplate: '/api/v1/roles/{role_id}/users/{user_id}',
      path: `/api/v1/roles/${encodeURIComponent(roleId)}/users/${encodeURIComponent(userId)}`,
      query: { 'resource_id': resourceId },
    });
  }

  /** `GET /api/v1/roles/{role_id}/groups` */
  async listGroups(roleId: string): Promise<models.RoleGroupAssignment[]> {
    const wire = await sendManagement<models.RoleGroupAssignment[]>(this.#client, {
      operation: 'roles.list_groups',
      method: 'GET',
      pathTemplate: '/api/v1/roles/{role_id}/groups',
      path: `/api/v1/roles/${encodeURIComponent(roleId)}/groups`,
    });
    return wire;
  }

  /**
   * `POST /api/v1/roles/{role_id}/groups`
   *
   * Not retried on failure (§27.4 rule 8): every write on this surface is
   * issued exactly once, including the ones that look idempotent.
   */
  async assignToGroup(roleId: string, body: models.AssignRoleToGroupRequest): Promise<void> {
    await sendManagement<void>(this.#client, {
      operation: 'roles.assign_to_group',
      method: 'POST',
      pathTemplate: '/api/v1/roles/{role_id}/groups',
      path: `/api/v1/roles/${encodeURIComponent(roleId)}/groups`,
      body: body,
    });
  }

  /**
   * `DELETE /api/v1/roles/{role_id}/groups/{group_id}`
   *
   * Not retried on failure (§27.4 rule 8): every write on this surface is
   * issued exactly once, including the ones that look idempotent.
   */
  async unassignFromGroup(roleId: string, groupId: string, resourceId?: string): Promise<void> {
    await sendManagement<void>(this.#client, {
      operation: 'roles.unassign_from_group',
      method: 'DELETE',
      pathTemplate: '/api/v1/roles/{role_id}/groups/{group_id}',
      path: `/api/v1/roles/${encodeURIComponent(roleId)}/groups/${encodeURIComponent(groupId)}`,
      query: { 'resource_id': resourceId },
    });
  }

  /** `GET /api/v1/roles/{role_id}/permissions` */
  async listPermissions(roleId: string): Promise<models.ResolvedPermissionGrant[]> {
    const wire = await sendManagement<models.ResolvedPermissionGrant[]>(this.#client, {
      operation: 'roles.list_permissions',
      method: 'GET',
      pathTemplate: '/api/v1/roles/{role_id}/permissions',
      path: `/api/v1/roles/${encodeURIComponent(roleId)}/permissions`,
    });
    return wire;
  }

  /**
   * `POST /api/v1/roles/{role_id}/permissions`
   *
   * Not retried on failure (§27.4 rule 8): every write on this surface is
   * issued exactly once, including the ones that look idempotent.
   */
  async grantPermission(roleId: string, body: models.GrantPermissionRequest): Promise<void> {
    await sendManagement<void>(this.#client, {
      operation: 'roles.grant_permission',
      method: 'POST',
      pathTemplate: '/api/v1/roles/{role_id}/permissions',
      path: `/api/v1/roles/${encodeURIComponent(roleId)}/permissions`,
      body: body,
    });
  }

  /**
   * `DELETE /api/v1/roles/{role_id}/permissions/{permission_id}`
   *
   * Not retried on failure (§27.4 rule 8): every write on this surface is
   * issued exactly once, including the ones that look idempotent.
   */
  async revokePermission(roleId: string, permissionId: string): Promise<void> {
    await sendManagement<void>(this.#client, {
      operation: 'roles.revoke_permission',
      method: 'DELETE',
      pathTemplate: '/api/v1/roles/{role_id}/permissions/{permission_id}',
      path: `/api/v1/roles/${encodeURIComponent(roleId)}/permissions/${encodeURIComponent(permissionId)}`,
    });
  }

}
