// @generated by scripts/gen-management.mjs from management-registry.json and
// openapi.json. DO NOT EDIT — your changes will be overwritten. Regenerate with
// `node scripts/gen-management.mjs`; CI verifies the committed output is current.

/**
 * The `saml` management namespace (CONTRACT §27.1).
 *
 * A tenant's SAML 2.0 identity provider (CONTRACT §29): the registry of
 * service providers, the import of an SP's metadata into a *draft*
 * registration (never a write), and the lifecycle of the IdP signing
 * credential. The protocol itself -- single sign-on, single logout, the IdP
 * metadata document -- is browser and SP-to-IdP surface under
 * /saml/v2/{tenant_id}, an SP's own SAML library speaks to it, and it is not
 * in this registry.
 */

import type { AxiamClient } from '../../rest/client.js';
import * as models from '../models.js';
import type { Page, PageRequest } from '../page.js';
import { collectPages, pageQuery } from '../page.js';
import { sendManagement } from '../request.js';
import type { NamespaceScope } from '../scope.js';
import { resolveOrg, resolveTenant } from '../scope.js';

/**
 * The `saml` namespace handle.
 *
 * A tenant's SAML 2.0 identity provider (CONTRACT §29): the registry of
 * service providers, the import of an SP's metadata into a *draft*
 * registration (never a write), and the lifecycle of the IdP signing
 * credential. The protocol itself -- single sign-on, single logout, the IdP
 * metadata document -- is browser and SP-to-IdP surface under
 * /saml/v2/{tenant_id}, an SP's own SAML library speaks to it, and it is not
 * in this registry.
 *
 * Acquiring one performs no I/O and allocates nothing meaningful (§27.2 rule
 * 1); it holds the client and cannot be constructed without one.
 */
export class SamlApi {
  readonly #client: AxiamClient;
  readonly #scope: NamespaceScope;

  /** @internal — reached through `client.<namespace>`, never constructed directly. */
  constructor(client: AxiamClient, scope: NamespaceScope = {}) {
    this.#client = client;
    this.#scope = scope;
  }

  /**
   * Address a different tenant than the client's own (§27.4 rule 3).
   *
   * Returns a new handle; the original is unchanged.
   */
  forTenant(tenantId: string): SamlApi {
    return new SamlApi(this.#client, { ...this.#scope, tenantId });
  }

  /** `GET /api/v1/tenants/{tenant_id}/saml/idp` */
  async getIdp(): Promise<models.SamlIdpInfo> {
    const tenantId = resolveTenant(this.#client, this.#scope, "saml.get_idp");
    const wire = await sendManagement<models.SamlIdpInfo>(this.#client, {
      operation: 'saml.get_idp',
      method: 'GET',
      pathTemplate: '/api/v1/tenants/{tenant_id}/saml/idp',
      path: `/api/v1/tenants/${tenantId}/saml/idp`,
    });
    return wire;
  }

  /** `GET /api/v1/tenants/{tenant_id}/saml/service-providers` */
  async listServiceProviders(page: PageRequest = {}): Promise<Page<models.SamlServiceProvider>> {
    const tenantId = resolveTenant(this.#client, this.#scope, "saml.list_service_providers");
    const wire = await sendManagement<Page<models.SamlServiceProvider>>(this.#client, {
      operation: 'saml.list_service_providers',
      method: 'GET',
      pathTemplate: '/api/v1/tenants/{tenant_id}/saml/service-providers',
      path: `/api/v1/tenants/${tenantId}/saml/service-providers`,
      query: { ...pageQuery(page) },
    });
    return wire;
  }

  /**
   * Walk `saml.list_service_providers` to exhaustion, concatenating every
   * page.
   *
   * The auto-paging form §27.4 rule 4 requires. It stops on an empty page even
   * if `total` disagrees, so a misreporting server costs one wasted request
   * rather than an unbounded loop.
   */
  listServiceProvidersAll(start: PageRequest = {}): Promise<models.SamlServiceProvider[]> {
    return collectPages(start, (p) => this.listServiceProviders(p));
  }

  /**
   * `POST /api/v1/tenants/{tenant_id}/saml/service-providers`
   *
   * Not retried on failure (§27.4 rule 8): every write on this surface is
   * issued exactly once, including the ones that look idempotent.
   */
  async createServiceProvider(body: models.SamlServiceProviderInput): Promise<models.SamlServiceProvider> {
    const tenantId = resolveTenant(this.#client, this.#scope, "saml.create_service_provider");
    const wire = await sendManagement<models.SamlServiceProvider>(this.#client, {
      operation: 'saml.create_service_provider',
      method: 'POST',
      pathTemplate: '/api/v1/tenants/{tenant_id}/saml/service-providers',
      path: `/api/v1/tenants/${tenantId}/saml/service-providers`,
      body: body,
    });
    return wire;
  }

  /** `GET /api/v1/tenants/{tenant_id}/saml/service-providers/{sp_id}` */
  async getServiceProvider(spId: string): Promise<models.SamlServiceProvider> {
    const tenantId = resolveTenant(this.#client, this.#scope, "saml.get_service_provider");
    const wire = await sendManagement<models.SamlServiceProvider>(this.#client, {
      operation: 'saml.get_service_provider',
      method: 'GET',
      pathTemplate: '/api/v1/tenants/{tenant_id}/saml/service-providers/{sp_id}',
      path: `/api/v1/tenants/${tenantId}/saml/service-providers/${encodeURIComponent(spId)}`,
    });
    return wire;
  }

  /**
   * `PUT /api/v1/tenants/{tenant_id}/saml/service-providers/{sp_id}`
   *
   * **This is a replacement, not a patch** (§27.4 rule 5). Every field of the
   * body is required, and what you do not carry over from a prior read is not
   * preserved — it is overwritten. Read first, change the field you mean, send
   * the whole thing back.
   *
   * Not retried on failure (§27.4 rule 8): every write on this surface is
   * issued exactly once, including the ones that look idempotent.
   */
  async updateServiceProvider(spId: string, body: models.SamlServiceProviderInput): Promise<models.SamlServiceProvider> {
    const tenantId = resolveTenant(this.#client, this.#scope, "saml.update_service_provider");
    const wire = await sendManagement<models.SamlServiceProvider>(this.#client, {
      operation: 'saml.update_service_provider',
      method: 'PUT',
      pathTemplate: '/api/v1/tenants/{tenant_id}/saml/service-providers/{sp_id}',
      path: `/api/v1/tenants/${tenantId}/saml/service-providers/${encodeURIComponent(spId)}`,
      body: body,
    });
    return wire;
  }

  /**
   * `DELETE /api/v1/tenants/{tenant_id}/saml/service-providers/{sp_id}`
   *
   * Not retried on failure (§27.4 rule 8): every write on this surface is
   * issued exactly once, including the ones that look idempotent.
   */
  async deleteServiceProvider(spId: string): Promise<void> {
    const tenantId = resolveTenant(this.#client, this.#scope, "saml.delete_service_provider");
    await sendManagement<void>(this.#client, {
      operation: 'saml.delete_service_provider',
      method: 'DELETE',
      pathTemplate: '/api/v1/tenants/{tenant_id}/saml/service-providers/{sp_id}',
      path: `/api/v1/tenants/${tenantId}/saml/service-providers/${encodeURIComponent(spId)}`,
    });
  }

  /**
   * `POST /api/v1/tenants/{tenant_id}/saml/parse-sp-metadata`
   *
   * Not retried on failure (§27.4 rule 8): every write on this surface is
   * issued exactly once, including the ones that look idempotent.
   */
  async parseSpMetadata(body: models.ParseSamlSpMetadata): Promise<models.SamlSpMetadataDraft> {
    const tenantId = resolveTenant(this.#client, this.#scope, "saml.parse_sp_metadata");
    const wire = await sendManagement<models.SamlSpMetadataDraft>(this.#client, {
      operation: 'saml.parse_sp_metadata',
      method: 'POST',
      pathTemplate: '/api/v1/tenants/{tenant_id}/saml/parse-sp-metadata',
      path: `/api/v1/tenants/${tenantId}/saml/parse-sp-metadata`,
      body: body,
    });
    return wire;
  }

  /** `GET /api/v1/tenants/{tenant_id}/saml/idp-credentials` */
  async listIdpCredentials(): Promise<models.SamlIdpCredential[]> {
    const tenantId = resolveTenant(this.#client, this.#scope, "saml.list_idp_credentials");
    const wire = await sendManagement<models.SamlIdpCredential[]>(this.#client, {
      operation: 'saml.list_idp_credentials',
      method: 'GET',
      pathTemplate: '/api/v1/tenants/{tenant_id}/saml/idp-credentials',
      path: `/api/v1/tenants/${tenantId}/saml/idp-credentials`,
    });
    return wire;
  }

  /**
   * `POST /api/v1/tenants/{tenant_id}/saml/idp-credentials`
   *
   * Not retried on failure (§27.4 rule 8): every write on this surface is
   * issued exactly once, including the ones that look idempotent.
   */
  async issueIdpCredential(body: models.IssueSamlIdpCredential): Promise<models.SamlIdpCredential> {
    const tenantId = resolveTenant(this.#client, this.#scope, "saml.issue_idp_credential");
    const wire = await sendManagement<models.SamlIdpCredential>(this.#client, {
      operation: 'saml.issue_idp_credential',
      method: 'POST',
      pathTemplate: '/api/v1/tenants/{tenant_id}/saml/idp-credentials',
      path: `/api/v1/tenants/${tenantId}/saml/idp-credentials`,
      body: body,
    });
    return wire;
  }

  /**
   * `POST
   * /api/v1/tenants/{tenant_id}/saml/idp-credentials/{credential_id}/promote`
   *
   * Not retried on failure (§27.4 rule 8): every write on this surface is
   * issued exactly once, including the ones that look idempotent.
   */
  async promoteIdpCredential(credentialId: string): Promise<models.SamlIdpCredentialPromotion> {
    const tenantId = resolveTenant(this.#client, this.#scope, "saml.promote_idp_credential");
    const wire = await sendManagement<models.SamlIdpCredentialPromotion>(this.#client, {
      operation: 'saml.promote_idp_credential',
      method: 'POST',
      pathTemplate: '/api/v1/tenants/{tenant_id}/saml/idp-credentials/{credential_id}/promote',
      path: `/api/v1/tenants/${tenantId}/saml/idp-credentials/${encodeURIComponent(credentialId)}/promote`,
    });
    return wire;
  }

  /**
   * `POST
   * /api/v1/tenants/{tenant_id}/saml/idp-credentials/{credential_id}/retire`
   *
   * Not retried on failure (§27.4 rule 8): every write on this surface is
   * issued exactly once, including the ones that look idempotent.
   */
  async retireIdpCredential(credentialId: string): Promise<models.SamlIdpCredential> {
    const tenantId = resolveTenant(this.#client, this.#scope, "saml.retire_idp_credential");
    const wire = await sendManagement<models.SamlIdpCredential>(this.#client, {
      operation: 'saml.retire_idp_credential',
      method: 'POST',
      pathTemplate: '/api/v1/tenants/{tenant_id}/saml/idp-credentials/{credential_id}/retire',
      path: `/api/v1/tenants/${tenantId}/saml/idp-credentials/${encodeURIComponent(credentialId)}/retire`,
    });
    return wire;
  }

}
