// @generated by scripts/gen-management.mjs from management-registry.json and
// openapi.json. DO NOT EDIT — your changes will be overwritten. Regenerate with
// `node scripts/gen-management.mjs`; CI verifies the committed output is current.

/**
 * The `scim_targets` management namespace (CONTRACT §27.1).
 *
 * A tenant's outbound SCIM targets (CONTRACT §31): the downstream SCIM 2.0
 * service providers AXIAM pushes the tenant's users and groups to, each with
 * its delivery state. The credential AXIAM pushes with is write-only.
 * Deleting a target does not deprovision anything downstream.
 */

import type { AxiamClient } from '../../rest/client.js';
import * as models from '../models.js';
import type { Page, PageRequest } from '../page.js';
import { collectPages, pageQuery } from '../page.js';
import { sendManagement } from '../request.js';
import type { NamespaceScope } from '../scope.js';

/**
 * The `scim_targets` namespace handle.
 *
 * A tenant's outbound SCIM targets (CONTRACT §31): the downstream SCIM 2.0
 * service providers AXIAM pushes the tenant's users and groups to, each with
 * its delivery state. The credential AXIAM pushes with is write-only.
 * Deleting a target does not deprovision anything downstream.
 *
 * Acquiring one performs no I/O and allocates nothing meaningful (§27.2 rule
 * 1); it holds the client and cannot be constructed without one.
 */
export class ScimTargetsApi {
  readonly #client: AxiamClient;
  readonly #scope: NamespaceScope;

  /** @internal — reached through `client.<namespace>`, never constructed directly. */
  constructor(client: AxiamClient, scope: NamespaceScope = {}) {
    this.#client = client;
    this.#scope = scope;
  }

  /** `GET /api/v1/scim-targets` */
  async list(page: PageRequest = {}): Promise<Page<models.ScimTargetResponse>> {
    const wire = await sendManagement<Page<models.ScimTargetResponse>>(this.#client, {
      operation: 'scim_targets.list',
      method: 'GET',
      pathTemplate: '/api/v1/scim-targets',
      path: '/api/v1/scim-targets',
      query: { ...pageQuery(page) },
    });
    return wire;
  }

  /**
   * Walk `scim_targets.list` to exhaustion, concatenating every page.
   *
   * The auto-paging form §27.4 rule 4 requires. It stops on an empty page even
   * if `total` disagrees, so a misreporting server costs one wasted request
   * rather than an unbounded loop.
   */
  listAll(start: PageRequest = {}): Promise<models.ScimTargetResponse[]> {
    return collectPages(start, (p) => this.list(p));
  }

  /**
   * `POST /api/v1/scim-targets`
   *
   * Not retried on failure (§27.4 rule 8): every write on this surface is
   * issued exactly once, including the ones that look idempotent.
   */
  async create(body: models.ScimTargetInput): Promise<models.ScimTargetResponse> {
    models.assertKnownScimTargetAuth(body.auth);
    models.assertKnownScimTargetScope(body.scope);
    const wire = await sendManagement<models.ScimTargetResponse>(this.#client, {
      operation: 'scim_targets.create',
      method: 'POST',
      pathTemplate: '/api/v1/scim-targets',
      path: '/api/v1/scim-targets',
      body: models.scimTargetInputToWire(body),
    });
    return wire;
  }

  /** `GET /api/v1/scim-targets/{id}` */
  async get(id: string): Promise<models.ScimTargetResponse> {
    const wire = await sendManagement<models.ScimTargetResponse>(this.#client, {
      operation: 'scim_targets.get',
      method: 'GET',
      pathTemplate: '/api/v1/scim-targets/{id}',
      path: `/api/v1/scim-targets/${encodeURIComponent(id)}`,
    });
    return wire;
  }

  /**
   * `PUT /api/v1/scim-targets/{id}`
   *
   * **This is a replacement, not a patch** (§27.4 rule 5). Every field of the
   * body is required, and what you do not carry over from a prior read is not
   * preserved — it is overwritten. Read first, change the field you mean, send
   * the whole thing back.
   *
   * Not retried on failure (§27.4 rule 8): every write on this surface is
   * issued exactly once, including the ones that look idempotent.
   */
  async update(id: string, body: models.ScimTargetInput): Promise<models.ScimTargetResponse> {
    models.assertKnownScimTargetAuth(body.auth);
    models.assertKnownScimTargetScope(body.scope);
    const wire = await sendManagement<models.ScimTargetResponse>(this.#client, {
      operation: 'scim_targets.update',
      method: 'PUT',
      pathTemplate: '/api/v1/scim-targets/{id}',
      path: `/api/v1/scim-targets/${encodeURIComponent(id)}`,
      body: models.scimTargetInputToWire(body),
    });
    return wire;
  }

  /**
   * `DELETE /api/v1/scim-targets/{id}`
   *
   * Not retried on failure (§27.4 rule 8): every write on this surface is
   * issued exactly once, including the ones that look idempotent.
   */
  async delete(id: string): Promise<void> {
    await sendManagement<void>(this.#client, {
      operation: 'scim_targets.delete',
      method: 'DELETE',
      pathTemplate: '/api/v1/scim-targets/{id}',
      path: `/api/v1/scim-targets/${encodeURIComponent(id)}`,
    });
  }

  /**
   * `POST /api/v1/scim-targets/{id}/reconcile`
   *
   * Not retried on failure (§27.4 rule 8): every write on this surface is
   * issued exactly once, including the ones that look idempotent.
   */
  async reconcile(id: string): Promise<models.ScimReconcileAccepted> {
    const wire = await sendManagement<models.ScimReconcileAccepted>(this.#client, {
      operation: 'scim_targets.reconcile',
      method: 'POST',
      pathTemplate: '/api/v1/scim-targets/{id}/reconcile',
      path: `/api/v1/scim-targets/${encodeURIComponent(id)}/reconcile`,
    });
    return wire;
  }

}
