// @generated by scripts/gen-management.mjs from management-registry.json and
// openapi.json. DO NOT EDIT — your changes will be overwritten. Regenerate with
// `node scripts/gen-management.mjs`; CI verifies the committed output is current.

/**
 * The `scim_tokens` management namespace (CONTRACT §27.1).
 *
 * Bearer tokens for the SCIM 2.0 provisioning endpoint.
 */

import type { AxiamClient } from '../../rest/client.js';
import * as models from '../models.js';
import { sendManagement } from '../request.js';
import type { Scope } from '../scope.js';

/**
 * The `scim_tokens` namespace handle.
 *
 * Bearer tokens for the SCIM 2.0 provisioning endpoint.
 *
 * Acquiring one performs no I/O and allocates nothing meaningful (§27.2 rule
 * 1); it holds the client and cannot be constructed without one.
 */
export class ScimTokensApi {
  readonly #client: AxiamClient;
  readonly #scope: Scope;

  /** @internal — reached through `client.<namespace>`, never constructed directly. */
  constructor(client: AxiamClient, scope: Scope = {}) {
    this.#client = client;
    this.#scope = scope;
  }

  /** `GET /api/v1/scim-tokens` */
  async list(): Promise<models.ScimTokenResponse[]> {
    const wire = await sendManagement<models.ScimTokenResponse[]>(this.#client, {
      operation: 'scim_tokens.list',
      method: 'GET',
      pathTemplate: '/api/v1/scim-tokens',
      path: '/api/v1/scim-tokens',
    });
    return wire;
  }

  /**
   * `POST /api/v1/scim-tokens`
   *
   * **Returns secret material, once.** `provisioning_token` is returned by
   * this call and by no other; no later `get` will return it again, and the
   * `get` projection has no field where it was. Discarding the result destroys
   * the credential (§27.5 rule 3).
   *
   * Not retried on failure (§27.4 rule 8): every write on this surface is
   * issued exactly once, including the ones that look idempotent.
   */
  async create(body: models.CreateScimTokenRequest): Promise<models.CreateScimTokenResponse> {
    const wire = await sendManagement<models.CreateScimTokenResponseWire>(this.#client, {
      operation: 'scim_tokens.create',
      method: 'POST',
      pathTemplate: '/api/v1/scim-tokens',
      path: '/api/v1/scim-tokens',
      body: body,
    });
    return models.createScimTokenResponseFromWire(wire);
  }

  /**
   * `DELETE /api/v1/scim-tokens/{id}`
   *
   * Not retried on failure (§27.4 rule 8): every write on this surface is
   * issued exactly once, including the ones that look idempotent.
   */
  async revoke(id: string): Promise<void> {
    await sendManagement<void>(this.#client, {
      operation: 'scim_tokens.revoke',
      method: 'DELETE',
      pathTemplate: '/api/v1/scim-tokens/{id}',
      path: `/api/v1/scim-tokens/${encodeURIComponent(id)}`,
    });
  }

}
