// @generated by scripts/gen-management.mjs from management-registry.json and
// openapi.json. DO NOT EDIT — your changes will be overwritten. Regenerate with
// `node scripts/gen-management.mjs`; CI verifies the committed output is current.

/**
 * The `scopes` management namespace (CONTRACT §27.1).
 *
 * Sub-resource granularity, always addressed under their resource.
 */

import type { AxiamClient } from '../../rest/client.js';
import * as models from '../models.js';
import { sendManagement } from '../request.js';
import type { NamespaceScope } from '../scope.js';

/**
 * The `scopes` namespace handle.
 *
 * Sub-resource granularity, always addressed under their resource.
 *
 * Acquiring one performs no I/O and allocates nothing meaningful (§27.2 rule
 * 1); it holds the client and cannot be constructed without one.
 */
export class ScopesApi {
  readonly #client: AxiamClient;
  readonly #scope: NamespaceScope;

  /** @internal — reached through `client.<namespace>`, never constructed directly. */
  constructor(client: AxiamClient, scope: NamespaceScope = {}) {
    this.#client = client;
    this.#scope = scope;
  }

  /** `GET /api/v1/resources/{resource_id}/scopes` */
  async list(resourceId: string): Promise<models.Scope[]> {
    const wire = await sendManagement<models.Scope[]>(this.#client, {
      operation: 'scopes.list',
      method: 'GET',
      pathTemplate: '/api/v1/resources/{resource_id}/scopes',
      path: `/api/v1/resources/${encodeURIComponent(resourceId)}/scopes`,
    });
    return wire;
  }

  /**
   * `POST /api/v1/resources/{resource_id}/scopes`
   *
   * Not retried on failure (§27.4 rule 8): every write on this surface is
   * issued exactly once, including the ones that look idempotent.
   */
  async create(resourceId: string, body: models.CreateScopeRequest): Promise<models.Scope> {
    const wire = await sendManagement<models.Scope>(this.#client, {
      operation: 'scopes.create',
      method: 'POST',
      pathTemplate: '/api/v1/resources/{resource_id}/scopes',
      path: `/api/v1/resources/${encodeURIComponent(resourceId)}/scopes`,
      body: body,
    });
    return wire;
  }

  /** `GET /api/v1/resources/{resource_id}/scopes/{scope_id}` */
  async get(resourceId: string, scopeId: string): Promise<models.Scope> {
    const wire = await sendManagement<models.Scope>(this.#client, {
      operation: 'scopes.get',
      method: 'GET',
      pathTemplate: '/api/v1/resources/{resource_id}/scopes/{scope_id}',
      path: `/api/v1/resources/${encodeURIComponent(resourceId)}/scopes/${encodeURIComponent(scopeId)}`,
    });
    return wire;
  }

  /**
   * `PUT /api/v1/resources/{resource_id}/scopes/{scope_id}`
   *
   * Not retried on failure (§27.4 rule 8): every write on this surface is
   * issued exactly once, including the ones that look idempotent.
   */
  async update(resourceId: string, scopeId: string, body: models.UpdateScopeRequest): Promise<models.Scope> {
    const wire = await sendManagement<models.Scope>(this.#client, {
      operation: 'scopes.update',
      method: 'PUT',
      pathTemplate: '/api/v1/resources/{resource_id}/scopes/{scope_id}',
      path: `/api/v1/resources/${encodeURIComponent(resourceId)}/scopes/${encodeURIComponent(scopeId)}`,
      body: body,
    });
    return wire;
  }

  /**
   * `DELETE /api/v1/resources/{resource_id}/scopes/{scope_id}`
   *
   * Not retried on failure (§27.4 rule 8): every write on this surface is
   * issued exactly once, including the ones that look idempotent.
   */
  async delete(resourceId: string, scopeId: string): Promise<void> {
    await sendManagement<void>(this.#client, {
      operation: 'scopes.delete',
      method: 'DELETE',
      pathTemplate: '/api/v1/resources/{resource_id}/scopes/{scope_id}',
      path: `/api/v1/resources/${encodeURIComponent(resourceId)}/scopes/${encodeURIComponent(scopeId)}`,
    });
  }

}
