// @generated by scripts/gen-management.mjs from management-registry.json and
// openapi.json. DO NOT EDIT — your changes will be overwritten. Regenerate with
// `node scripts/gen-management.mjs`; CI verifies the committed output is current.

/**
 * The `service_accounts` management namespace (CONTRACT §27.1).
 *
 * Machine identities, their secrets, and the certificate a device-bound one
 * authenticates with.
 */

import type { AxiamClient } from '../../rest/client.js';
import * as models from '../models.js';
import type { Page, PageRequest } from '../page.js';
import { collectPages, pageQuery } from '../page.js';
import { sendManagement } from '../request.js';
import type { NamespaceScope } from '../scope.js';

/**
 * The `service_accounts` namespace handle.
 *
 * Machine identities, their secrets, and the certificate a device-bound one
 * authenticates with.
 *
 * Acquiring one performs no I/O and allocates nothing meaningful (§27.2 rule
 * 1); it holds the client and cannot be constructed without one.
 */
export class ServiceAccountsApi {
  readonly #client: AxiamClient;
  readonly #scope: NamespaceScope;

  /** @internal — reached through `client.<namespace>`, never constructed directly. */
  constructor(client: AxiamClient, scope: NamespaceScope = {}) {
    this.#client = client;
    this.#scope = scope;
  }

  /** `GET /api/v1/service-accounts` */
  async list(page: PageRequest = {}): Promise<Page<models.ServiceAccountResponse>> {
    const wire = await sendManagement<Page<models.ServiceAccountResponse>>(this.#client, {
      operation: 'service_accounts.list',
      method: 'GET',
      pathTemplate: '/api/v1/service-accounts',
      path: '/api/v1/service-accounts',
      query: { ...pageQuery(page) },
    });
    return wire;
  }

  /**
   * Walk `service_accounts.list` to exhaustion, concatenating every page.
   *
   * The auto-paging form §27.4 rule 4 requires. It stops on an empty page even
   * if `total` disagrees, so a misreporting server costs one wasted request
   * rather than an unbounded loop.
   */
  listAll(start: PageRequest = {}): Promise<models.ServiceAccountResponse[]> {
    return collectPages(start, (p) => this.list(p));
  }

  /**
   * `POST /api/v1/service-accounts`
   *
   * **Returns secret material, once.** `client_secret` is returned by this
   * call and by no other; no later `get` will return it again, and the `get`
   * projection has no field where it was. Discarding the result destroys the
   * credential (§27.5 rule 3).
   *
   * Not retried on failure (§27.4 rule 8): every write on this surface is
   * issued exactly once, including the ones that look idempotent.
   */
  async create(body: models.CreateServiceAccountRequest): Promise<models.ServiceAccountCreatedResponse> {
    const wire = await sendManagement<models.ServiceAccountCreatedResponseWire>(this.#client, {
      operation: 'service_accounts.create',
      method: 'POST',
      pathTemplate: '/api/v1/service-accounts',
      path: '/api/v1/service-accounts',
      body: body,
    });
    return models.serviceAccountCreatedResponseFromWire(wire);
  }

  /** `GET /api/v1/service-accounts/{sa_id}` */
  async get(saId: string): Promise<models.ServiceAccountResponse> {
    const wire = await sendManagement<models.ServiceAccountResponse>(this.#client, {
      operation: 'service_accounts.get',
      method: 'GET',
      pathTemplate: '/api/v1/service-accounts/{sa_id}',
      path: `/api/v1/service-accounts/${encodeURIComponent(saId)}`,
    });
    return wire;
  }

  /**
   * `PUT /api/v1/service-accounts/{sa_id}`
   *
   * Not retried on failure (§27.4 rule 8): every write on this surface is
   * issued exactly once, including the ones that look idempotent.
   */
  async update(saId: string, body: models.UpdateServiceAccount): Promise<models.ServiceAccountResponse> {
    const wire = await sendManagement<models.ServiceAccountResponse>(this.#client, {
      operation: 'service_accounts.update',
      method: 'PUT',
      pathTemplate: '/api/v1/service-accounts/{sa_id}',
      path: `/api/v1/service-accounts/${encodeURIComponent(saId)}`,
      body: body,
    });
    return wire;
  }

  /**
   * `DELETE /api/v1/service-accounts/{sa_id}`
   *
   * Not retried on failure (§27.4 rule 8): every write on this surface is
   * issued exactly once, including the ones that look idempotent.
   */
  async delete(saId: string): Promise<void> {
    await sendManagement<void>(this.#client, {
      operation: 'service_accounts.delete',
      method: 'DELETE',
      pathTemplate: '/api/v1/service-accounts/{sa_id}',
      path: `/api/v1/service-accounts/${encodeURIComponent(saId)}`,
    });
  }

  /**
   * `POST /api/v1/service-accounts/{sa_id}/rotate-secret`
   *
   * **Returns secret material, once.** `client_secret` is returned by this
   * call and by no other; no later `get` will return it again, and the `get`
   * projection has no field where it was. Discarding the result destroys the
   * credential (§27.5 rule 3).
   *
   * Not retried on failure (§27.4 rule 8): every write on this surface is
   * issued exactly once, including the ones that look idempotent.
   */
  async rotateSecret(saId: string): Promise<models.RotateSecretResponse> {
    const wire = await sendManagement<models.RotateSecretResponseWire>(this.#client, {
      operation: 'service_accounts.rotate_secret',
      method: 'POST',
      pathTemplate: '/api/v1/service-accounts/{sa_id}/rotate-secret',
      path: `/api/v1/service-accounts/${encodeURIComponent(saId)}/rotate-secret`,
    });
    return models.rotateSecretResponseFromWire(wire);
  }

  /**
   * `POST /api/v1/service-accounts/{sa_id}/bind-certificate`
   *
   * Not retried on failure (§27.4 rule 8): every write on this surface is
   * issued exactly once, including the ones that look idempotent.
   */
  async bindCertificate(saId: string, body: models.BindCertificate): Promise<void> {
    await sendManagement<void>(this.#client, {
      operation: 'service_accounts.bind_certificate',
      method: 'POST',
      pathTemplate: '/api/v1/service-accounts/{sa_id}/bind-certificate',
      path: `/api/v1/service-accounts/${encodeURIComponent(saId)}/bind-certificate`,
      body: body,
    });
  }

}
