// @generated by scripts/gen-management.mjs from management-registry.json and
// openapi.json. DO NOT EDIT — your changes will be overwritten. Regenerate with
// `node scripts/gen-management.mjs`; CI verifies the committed output is current.

/**
 * The `settings` management namespace (CONTRACT §27.1).
 *
 * Effective settings, and the organization/tenant layers they resolve from.
 */

import type { AxiamClient } from '../../rest/client.js';
import * as models from '../models.js';
import { sendManagement } from '../request.js';
import type { NamespaceScope } from '../scope.js';
import { resolveOrg, resolveTenant } from '../scope.js';

/**
 * The `settings` namespace handle.
 *
 * Effective settings, and the organization/tenant layers they resolve from.
 *
 * Acquiring one performs no I/O and allocates nothing meaningful (§27.2 rule
 * 1); it holds the client and cannot be constructed without one.
 */
export class SettingsApi {
  readonly #client: AxiamClient;
  readonly #scope: NamespaceScope;

  /** @internal — reached through `client.<namespace>`, never constructed directly. */
  constructor(client: AxiamClient, scope: NamespaceScope = {}) {
    this.#client = client;
    this.#scope = scope;
  }

  /**
   * Address a different organization than the client's own.
   *
   * §27.4 rule 3: the client's `orgId` is the default, and a platform-admin
   * token legitimately overrides it. Returns a new handle; the original is
   * unchanged.
   */
  inOrg(orgId: string): SettingsApi {
    return new SettingsApi(this.#client, { ...this.#scope, orgId });
  }

  /**
   * Address a different tenant than the client's own (§27.4 rule 3).
   *
   * Returns a new handle; the original is unchanged.
   */
  forTenant(tenantId: string): SettingsApi {
    return new SettingsApi(this.#client, { ...this.#scope, tenantId });
  }

  /** `GET /api/v1/organizations/{org_id}/settings` */
  async getOrg(): Promise<models.SecuritySettings> {
    const orgId = resolveOrg(this.#client, this.#scope, "settings.get_org");
    const wire = await sendManagement<models.SecuritySettings>(this.#client, {
      operation: 'settings.get_org',
      method: 'GET',
      pathTemplate: '/api/v1/organizations/{org_id}/settings',
      path: `/api/v1/organizations/${orgId}/settings`,
    });
    return wire;
  }

  /**
   * `PUT /api/v1/organizations/{org_id}/settings`
   *
   * **This is a replacement, not a patch** (§27.4 rule 5). Every field of the
   * body is required, and what you do not carry over from a prior read is not
   * preserved — it is overwritten. Read first, change the field you mean, send
   * the whole thing back.
   *
   * Not retried on failure (§27.4 rule 8): every write on this surface is
   * issued exactly once, including the ones that look idempotent.
   */
  async setOrg(body: models.SetOrgSettings): Promise<models.SecuritySettings> {
    const orgId = resolveOrg(this.#client, this.#scope, "settings.set_org");
    const wire = await sendManagement<models.SecuritySettings>(this.#client, {
      operation: 'settings.set_org',
      method: 'PUT',
      pathTemplate: '/api/v1/organizations/{org_id}/settings',
      path: `/api/v1/organizations/${orgId}/settings`,
      body: body,
    });
    return wire;
  }

  /** `GET /api/v1/settings` */
  async getEffective(): Promise<models.SecuritySettings> {
    const wire = await sendManagement<models.SecuritySettings>(this.#client, {
      operation: 'settings.get_effective',
      method: 'GET',
      pathTemplate: '/api/v1/settings',
      path: '/api/v1/settings',
    });
    return wire;
  }

  /**
   * `PUT /api/v1/settings`
   *
   * Not retried on failure (§27.4 rule 8): every write on this surface is
   * issued exactly once, including the ones that look idempotent.
   */
  async setEffective(body: models.TenantSettingsOverride): Promise<models.SecuritySettings> {
    const wire = await sendManagement<models.SecuritySettings>(this.#client, {
      operation: 'settings.set_effective',
      method: 'PUT',
      pathTemplate: '/api/v1/settings',
      path: '/api/v1/settings',
      body: body,
    });
    return wire;
  }

  /** `GET /api/v1/tenants/{tenant_id}/settings` */
  async getTenantOverride(): Promise<models.TenantSettingsOverride> {
    const tenantId = resolveTenant(this.#client, this.#scope, "settings.get_tenant_override");
    const wire = await sendManagement<models.TenantSettingsOverride>(this.#client, {
      operation: 'settings.get_tenant_override',
      method: 'GET',
      pathTemplate: '/api/v1/tenants/{tenant_id}/settings',
      path: `/api/v1/tenants/${tenantId}/settings`,
    });
    return wire;
  }

  /**
   * `PUT /api/v1/tenants/{tenant_id}/settings`
   *
   * Not retried on failure (§27.4 rule 8): every write on this surface is
   * issued exactly once, including the ones that look idempotent.
   */
  async setTenantOverride(body: models.TenantSettingsOverride): Promise<models.TenantSettingsOverride> {
    const tenantId = resolveTenant(this.#client, this.#scope, "settings.set_tenant_override");
    const wire = await sendManagement<models.TenantSettingsOverride>(this.#client, {
      operation: 'settings.set_tenant_override',
      method: 'PUT',
      pathTemplate: '/api/v1/tenants/{tenant_id}/settings',
      path: `/api/v1/tenants/${tenantId}/settings`,
      body: body,
    });
    return wire;
  }

  /**
   * `DELETE /api/v1/tenants/{tenant_id}/settings`
   *
   * Not retried on failure (§27.4 rule 8): every write on this surface is
   * issued exactly once, including the ones that look idempotent.
   */
  async deleteTenantOverride(): Promise<void> {
    const tenantId = resolveTenant(this.#client, this.#scope, "settings.delete_tenant_override");
    await sendManagement<void>(this.#client, {
      operation: 'settings.delete_tenant_override',
      method: 'DELETE',
      pathTemplate: '/api/v1/tenants/{tenant_id}/settings',
      path: `/api/v1/tenants/${tenantId}/settings`,
    });
  }

}
