// @generated by scripts/gen-management.mjs from management-registry.json and
// openapi.json. DO NOT EDIT — your changes will be overwritten. Regenerate with
// `node scripts/gen-management.mjs`; CI verifies the committed output is current.

/**
 * The `ssf` management namespace (CONTRACT §27.1).
 *
 * A tenant's Shared Signals Framework streams (CONTRACT §32): which receiver
 * -- an OAuth2 client of the tenant -- receives which CAEP and RISC security
 * events, as SETs pushed to its endpoint or polled. The receiver's own
 * protocol (transmitter metadata, the SSF stream management API, polling) is
 * not in this registry.
 */

import type { AxiamClient } from '../../rest/client.js';
import * as models from '../models.js';
import type { Page, PageRequest } from '../page.js';
import { collectPages, pageQuery } from '../page.js';
import { sendManagement } from '../request.js';
import type { NamespaceScope } from '../scope.js';
import { resolveOrg, resolveTenant } from '../scope.js';

/**
 * The `ssf` namespace handle.
 *
 * A tenant's Shared Signals Framework streams (CONTRACT §32): which receiver
 * -- an OAuth2 client of the tenant -- receives which CAEP and RISC security
 * events, as SETs pushed to its endpoint or polled. The receiver's own
 * protocol (transmitter metadata, the SSF stream management API, polling) is
 * not in this registry.
 *
 * Acquiring one performs no I/O and allocates nothing meaningful (§27.2 rule
 * 1); it holds the client and cannot be constructed without one.
 */
export class SsfApi {
  readonly #client: AxiamClient;
  readonly #scope: NamespaceScope;

  /** @internal — reached through `client.<namespace>`, never constructed directly. */
  constructor(client: AxiamClient, scope: NamespaceScope = {}) {
    this.#client = client;
    this.#scope = scope;
  }

  /**
   * Address a different tenant than the client's own (§27.4 rule 3).
   *
   * Returns a new handle; the original is unchanged.
   */
  forTenant(tenantId: string): SsfApi {
    return new SsfApi(this.#client, { ...this.#scope, tenantId });
  }

  /** `GET /api/v1/tenants/{tenant_id}/ssf/streams` */
  async listStreams(page: PageRequest = {}): Promise<Page<models.SsfStream>> {
    const tenantId = resolveTenant(this.#client, this.#scope, "ssf.list_streams");
    const wire = await sendManagement<Page<models.SsfStream>>(this.#client, {
      operation: 'ssf.list_streams',
      method: 'GET',
      pathTemplate: '/api/v1/tenants/{tenant_id}/ssf/streams',
      path: `/api/v1/tenants/${tenantId}/ssf/streams`,
      query: { ...pageQuery(page) },
    });
    return { items: wire.items.map(models.scrubSsfStream), total: wire.total, offset: wire.offset, limit: wire.limit };
  }

  /**
   * Walk `ssf.list_streams` to exhaustion, concatenating every page.
   *
   * The auto-paging form §27.4 rule 4 requires. It stops on an empty page even
   * if `total` disagrees, so a misreporting server costs one wasted request
   * rather than an unbounded loop.
   */
  listStreamsAll(start: PageRequest = {}): Promise<models.SsfStream[]> {
    return collectPages(start, (p) => this.listStreams(p));
  }

  /**
   * `POST /api/v1/tenants/{tenant_id}/ssf/streams`
   *
   * Not retried on failure (§27.4 rule 8): every write on this surface is
   * issued exactly once, including the ones that look idempotent.
   */
  async createStream(body: models.SsfStreamInput): Promise<models.SsfStream> {
    const tenantId = resolveTenant(this.#client, this.#scope, "ssf.create_stream");
    const wire = await sendManagement<models.SsfStream>(this.#client, {
      operation: 'ssf.create_stream',
      method: 'POST',
      pathTemplate: '/api/v1/tenants/{tenant_id}/ssf/streams',
      path: `/api/v1/tenants/${tenantId}/ssf/streams`,
      body: models.ssfStreamInputToWire(body),
    });
    return models.scrubSsfStream(wire);
  }

  /** `GET /api/v1/tenants/{tenant_id}/ssf/streams/{stream_id}` */
  async getStream(streamId: string): Promise<models.SsfStream> {
    const tenantId = resolveTenant(this.#client, this.#scope, "ssf.get_stream");
    const wire = await sendManagement<models.SsfStream>(this.#client, {
      operation: 'ssf.get_stream',
      method: 'GET',
      pathTemplate: '/api/v1/tenants/{tenant_id}/ssf/streams/{stream_id}',
      path: `/api/v1/tenants/${tenantId}/ssf/streams/${encodeURIComponent(streamId)}`,
    });
    return models.scrubSsfStream(wire);
  }

  /**
   * `PUT /api/v1/tenants/{tenant_id}/ssf/streams/{stream_id}`
   *
   * An omitted optional member takes its default (§32.2) — **except
   * `authorization_header`, which absent keeps the stored one** — unless the
   * update moves `endpoint_url` to another scheme, host or port while a header
   * is stored: then it must carry `authorization_header` again or
   * `clear_authorization_header: true`, else `400` (§32.3 rule 5). Start from
   * `ssfStreamInputFrom(await ssf.getStream(id))`. An update overtaken by the
   * receiver's own write is `409`: read the stream again.
   *
   * **This is a replacement, not a patch** (§27.4 rule 5). Only the required
   * members must be set, but what you do not carry over from a prior read is
   * not preserved: an optional member left out is overwritten with its
   * default, not kept (except where noted above). Read first, change the field
   * you mean, send the whole thing back.
   *
   * Not retried on failure (§27.4 rule 8): every write on this surface is
   * issued exactly once, including the ones that look idempotent.
   */
  async updateStream(streamId: string, body: models.SsfStreamInput): Promise<models.SsfStream> {
    const tenantId = resolveTenant(this.#client, this.#scope, "ssf.update_stream");
    const wire = await sendManagement<models.SsfStream>(this.#client, {
      operation: 'ssf.update_stream',
      method: 'PUT',
      pathTemplate: '/api/v1/tenants/{tenant_id}/ssf/streams/{stream_id}',
      path: `/api/v1/tenants/${tenantId}/ssf/streams/${encodeURIComponent(streamId)}`,
      body: models.ssfStreamInputToWire(body),
    });
    return models.scrubSsfStream(wire);
  }

  /**
   * `DELETE /api/v1/tenants/{tenant_id}/ssf/streams/{stream_id}`
   *
   * Not retried on failure (§27.4 rule 8): every write on this surface is
   * issued exactly once, including the ones that look idempotent.
   */
  async deleteStream(streamId: string): Promise<void> {
    const tenantId = resolveTenant(this.#client, this.#scope, "ssf.delete_stream");
    await sendManagement<void>(this.#client, {
      operation: 'ssf.delete_stream',
      method: 'DELETE',
      pathTemplate: '/api/v1/tenants/{tenant_id}/ssf/streams/{stream_id}',
      path: `/api/v1/tenants/${tenantId}/ssf/streams/${encodeURIComponent(streamId)}`,
    });
  }

}
