// @generated by scripts/gen-management.mjs from management-registry.json and
// openapi.json. DO NOT EDIT — your changes will be overwritten. Regenerate with
// `node scripts/gen-management.mjs`; CI verifies the committed output is current.

/**
 * The `tenants` management namespace (CONTRACT §27.1).
 *
 * Tenants within an organization -- the isolation boundary every other
 * namespace is scoped to.
 */

import type { AxiamClient } from '../../rest/client.js';
import * as models from '../models.js';
import type { Page, PageRequest } from '../page.js';
import { collectPages, pageQuery } from '../page.js';
import { sendManagement } from '../request.js';
import type { NamespaceScope } from '../scope.js';
import { resolveOrg, resolveTenant } from '../scope.js';

/**
 * The `tenants` namespace handle.
 *
 * Tenants within an organization -- the isolation boundary every other
 * namespace is scoped to.
 *
 * Acquiring one performs no I/O and allocates nothing meaningful (§27.2 rule
 * 1); it holds the client and cannot be constructed without one.
 */
export class TenantsApi {
  readonly #client: AxiamClient;
  readonly #scope: NamespaceScope;

  /** @internal — reached through `client.<namespace>`, never constructed directly. */
  constructor(client: AxiamClient, scope: NamespaceScope = {}) {
    this.#client = client;
    this.#scope = scope;
  }

  /**
   * Address a different organization than the client's own.
   *
   * §27.4 rule 3: the client's `orgId` is the default, and a platform-admin
   * token legitimately overrides it. Returns a new handle; the original is
   * unchanged.
   */
  inOrg(orgId: string): TenantsApi {
    return new TenantsApi(this.#client, { ...this.#scope, orgId });
  }

  /** `GET /api/v1/organizations/{org_id}/tenants` */
  async list(page: PageRequest = {}): Promise<Page<models.Tenant>> {
    const orgId = resolveOrg(this.#client, this.#scope, "tenants.list");
    const wire = await sendManagement<Page<models.Tenant>>(this.#client, {
      operation: 'tenants.list',
      method: 'GET',
      pathTemplate: '/api/v1/organizations/{org_id}/tenants',
      path: `/api/v1/organizations/${orgId}/tenants`,
      query: { ...pageQuery(page) },
    });
    return wire;
  }

  /**
   * Walk `tenants.list` to exhaustion, concatenating every page.
   *
   * The auto-paging form §27.4 rule 4 requires. It stops on an empty page even
   * if `total` disagrees, so a misreporting server costs one wasted request
   * rather than an unbounded loop.
   */
  listAll(start: PageRequest = {}): Promise<models.Tenant[]> {
    return collectPages(start, (p) => this.list(p));
  }

  /**
   * `POST /api/v1/organizations/{org_id}/tenants`
   *
   * Not retried on failure (§27.4 rule 8): every write on this surface is
   * issued exactly once, including the ones that look idempotent.
   */
  async create(body: models.CreateTenantRequest): Promise<models.Tenant> {
    const orgId = resolveOrg(this.#client, this.#scope, "tenants.create");
    const wire = await sendManagement<models.Tenant>(this.#client, {
      operation: 'tenants.create',
      method: 'POST',
      pathTemplate: '/api/v1/organizations/{org_id}/tenants',
      path: `/api/v1/organizations/${orgId}/tenants`,
      body: body,
    });
    return wire;
  }

  /** `GET /api/v1/organizations/{org_id}/tenants/{tenant_id}` */
  async get(tenantId: string): Promise<models.Tenant> {
    const orgId = resolveOrg(this.#client, this.#scope, "tenants.get");
    const wire = await sendManagement<models.Tenant>(this.#client, {
      operation: 'tenants.get',
      method: 'GET',
      pathTemplate: '/api/v1/organizations/{org_id}/tenants/{tenant_id}',
      path: `/api/v1/organizations/${orgId}/tenants/${encodeURIComponent(tenantId)}`,
    });
    return wire;
  }

  /**
   * `PUT /api/v1/organizations/{org_id}/tenants/{tenant_id}`
   *
   * Not retried on failure (§27.4 rule 8): every write on this surface is
   * issued exactly once, including the ones that look idempotent.
   */
  async update(tenantId: string, body: models.UpdateTenant): Promise<models.Tenant> {
    const orgId = resolveOrg(this.#client, this.#scope, "tenants.update");
    const wire = await sendManagement<models.Tenant>(this.#client, {
      operation: 'tenants.update',
      method: 'PUT',
      pathTemplate: '/api/v1/organizations/{org_id}/tenants/{tenant_id}',
      path: `/api/v1/organizations/${orgId}/tenants/${encodeURIComponent(tenantId)}`,
      body: body,
    });
    return wire;
  }

  /**
   * `DELETE /api/v1/organizations/{org_id}/tenants/{tenant_id}`
   *
   * Not retried on failure (§27.4 rule 8): every write on this surface is
   * issued exactly once, including the ones that look idempotent.
   */
  async delete(tenantId: string): Promise<void> {
    const orgId = resolveOrg(this.#client, this.#scope, "tenants.delete");
    await sendManagement<void>(this.#client, {
      operation: 'tenants.delete',
      method: 'DELETE',
      pathTemplate: '/api/v1/organizations/{org_id}/tenants/{tenant_id}',
      path: `/api/v1/organizations/${orgId}/tenants/${encodeURIComponent(tenantId)}`,
    });
  }

}
