// @generated by scripts/gen-management.mjs from management-registry.json and
// openapi.json. DO NOT EDIT — your changes will be overwritten. Regenerate with
// `node scripts/gen-management.mjs`; CI verifies the committed output is current.

/**
 * The `users` management namespace (CONTRACT §27.1).
 *
 * Users within the client's tenant, and the administrative side of their
 * second factor and lockout state.
 */

import type { AxiamClient } from '../../rest/client.js';
import * as models from '../models.js';
import type { Page, PageRequest } from '../page.js';
import { collectPages, pageQuery } from '../page.js';
import { sendManagement } from '../request.js';
import type { Scope } from '../scope.js';

/**
 * The `users` namespace handle.
 *
 * Users within the client's tenant, and the administrative side of their
 * second factor and lockout state.
 *
 * Acquiring one performs no I/O and allocates nothing meaningful (§27.2 rule
 * 1); it holds the client and cannot be constructed without one.
 */
export class UsersApi {
  readonly #client: AxiamClient;
  readonly #scope: Scope;

  /** @internal — reached through `client.<namespace>`, never constructed directly. */
  constructor(client: AxiamClient, scope: Scope = {}) {
    this.#client = client;
    this.#scope = scope;
  }

  /** `GET /api/v1/users` */
  async list(page: PageRequest = {}): Promise<Page<models.UserResponse>> {
    const wire = await sendManagement<Page<models.UserResponse>>(this.#client, {
      operation: 'users.list',
      method: 'GET',
      pathTemplate: '/api/v1/users',
      path: '/api/v1/users',
      query: { ...pageQuery(page) },
    });
    return wire;
  }

  /**
   * Walk `users.list` to exhaustion, concatenating every page.
   *
   * The auto-paging form §27.4 rule 4 requires. It stops on an empty page even
   * if `total` disagrees, so a misreporting server costs one wasted request
   * rather than an unbounded loop.
   */
  listAll(start: PageRequest = {}): Promise<models.UserResponse[]> {
    return collectPages(start, (p) => this.list(p));
  }

  /**
   * `POST /api/v1/users`
   *
   * Not retried on failure (§27.4 rule 8): every write on this surface is
   * issued exactly once, including the ones that look idempotent.
   */
  async create(body: models.CreateUserRequest): Promise<models.UserResponse> {
    const wire = await sendManagement<models.UserResponse>(this.#client, {
      operation: 'users.create',
      method: 'POST',
      pathTemplate: '/api/v1/users',
      path: '/api/v1/users',
      body: models.createUserRequestToWire(body),
    });
    return wire;
  }

  /** `GET /api/v1/users/{user_id}` */
  async get(userId: string): Promise<models.UserResponse> {
    const wire = await sendManagement<models.UserResponse>(this.#client, {
      operation: 'users.get',
      method: 'GET',
      pathTemplate: '/api/v1/users/{user_id}',
      path: `/api/v1/users/${encodeURIComponent(userId)}`,
    });
    return wire;
  }

  /**
   * `PUT /api/v1/users/{user_id}`
   *
   * Not retried on failure (§27.4 rule 8): every write on this surface is
   * issued exactly once, including the ones that look idempotent.
   */
  async update(userId: string, body: models.UpdateUserRequest): Promise<models.UserResponse> {
    const wire = await sendManagement<models.UserResponse>(this.#client, {
      operation: 'users.update',
      method: 'PUT',
      pathTemplate: '/api/v1/users/{user_id}',
      path: `/api/v1/users/${encodeURIComponent(userId)}`,
      body: body,
    });
    return wire;
  }

  /**
   * `DELETE /api/v1/users/{user_id}`
   *
   * Not retried on failure (§27.4 rule 8): every write on this surface is
   * issued exactly once, including the ones that look idempotent.
   */
  async delete(userId: string): Promise<void> {
    await sendManagement<void>(this.#client, {
      operation: 'users.delete',
      method: 'DELETE',
      pathTemplate: '/api/v1/users/{user_id}',
      path: `/api/v1/users/${encodeURIComponent(userId)}`,
    });
  }

  /** `GET /api/v1/users/{user_id}/mfa-methods` */
  async listMfaMethods(userId: string): Promise<models.MfaMethodResponse[]> {
    const wire = await sendManagement<models.MfaMethodResponse[]>(this.#client, {
      operation: 'users.list_mfa_methods',
      method: 'GET',
      pathTemplate: '/api/v1/users/{user_id}/mfa-methods',
      path: `/api/v1/users/${encodeURIComponent(userId)}/mfa-methods`,
    });
    return wire;
  }

  /**
   * `DELETE /api/v1/users/{user_id}/mfa-methods/{method_id}`
   *
   * Not retried on failure (§27.4 rule 8): every write on this surface is
   * issued exactly once, including the ones that look idempotent.
   */
  async deleteMfaMethod(userId: string, methodId: string): Promise<void> {
    await sendManagement<void>(this.#client, {
      operation: 'users.delete_mfa_method',
      method: 'DELETE',
      pathTemplate: '/api/v1/users/{user_id}/mfa-methods/{method_id}',
      path: `/api/v1/users/${encodeURIComponent(userId)}/mfa-methods/${encodeURIComponent(methodId)}`,
    });
  }

  /**
   * `POST /api/v1/users/{user_id}/reset-mfa`
   *
   * Not retried on failure (§27.4 rule 8): every write on this surface is
   * issued exactly once, including the ones that look idempotent.
   */
  async resetMfa(userId: string): Promise<void> {
    await sendManagement<void>(this.#client, {
      operation: 'users.reset_mfa',
      method: 'POST',
      pathTemplate: '/api/v1/users/{user_id}/reset-mfa',
      path: `/api/v1/users/${encodeURIComponent(userId)}/reset-mfa`,
    });
  }

  /**
   * `POST /api/v1/users/{user_id}/unlock`
   *
   * Not retried on failure (§27.4 rule 8): every write on this surface is
   * issued exactly once, including the ones that look idempotent.
   */
  async unlock(userId: string): Promise<models.UserResponse> {
    const wire = await sendManagement<models.UserResponse>(this.#client, {
      operation: 'users.unlock',
      method: 'POST',
      pathTemplate: '/api/v1/users/{user_id}/unlock',
      path: `/api/v1/users/${encodeURIComponent(userId)}/unlock`,
    });
    return wire;
  }

  /** `GET /api/v1/users/{user_id}/roles` */
  async listRoles(userId: string): Promise<models.RoleAssignment[]> {
    const wire = await sendManagement<models.RoleAssignment[]>(this.#client, {
      operation: 'users.list_roles',
      method: 'GET',
      pathTemplate: '/api/v1/users/{user_id}/roles',
      path: `/api/v1/users/${encodeURIComponent(userId)}/roles`,
    });
    return wire;
  }

}
