// @generated by scripts/gen-management.mjs from management-registry.json and
// openapi.json. DO NOT EDIT — your changes will be overwritten. Regenerate with
// `node scripts/gen-management.mjs`; CI verifies the committed output is current.

/**
 * The `webauthn_policy` management namespace (CONTRACT §27.1).
 *
 * Per-tenant attestation policy governing the §24 ceremonies, and the
 * compliance report over it.
 */

import type { AxiamClient } from '../../rest/client.js';
import * as models from '../models.js';
import { sendManagement } from '../request.js';
import type { NamespaceScope } from '../scope.js';
import { resolveOrg, resolveTenant } from '../scope.js';

/**
 * The `webauthn_policy` namespace handle.
 *
 * Per-tenant attestation policy governing the §24 ceremonies, and the
 * compliance report over it.
 *
 * Acquiring one performs no I/O and allocates nothing meaningful (§27.2 rule
 * 1); it holds the client and cannot be constructed without one.
 */
export class WebauthnPolicyApi {
  readonly #client: AxiamClient;
  readonly #scope: NamespaceScope;

  /** @internal — reached through `client.<namespace>`, never constructed directly. */
  constructor(client: AxiamClient, scope: NamespaceScope = {}) {
    this.#client = client;
    this.#scope = scope;
  }

  /**
   * Address a different tenant than the client's own (§27.4 rule 3).
   *
   * Returns a new handle; the original is unchanged.
   */
  forTenant(tenantId: string): WebauthnPolicyApi {
    return new WebauthnPolicyApi(this.#client, { ...this.#scope, tenantId });
  }

  /** `GET /api/v1/tenants/{tenant_id}/webauthn/attestation-policy` */
  async get(): Promise<models.PolicyResponse> {
    const tenantId = resolveTenant(this.#client, this.#scope, "webauthn_policy.get");
    const wire = await sendManagement<models.PolicyResponse>(this.#client, {
      operation: 'webauthn_policy.get',
      method: 'GET',
      pathTemplate: '/api/v1/tenants/{tenant_id}/webauthn/attestation-policy',
      path: `/api/v1/tenants/${tenantId}/webauthn/attestation-policy`,
    });
    return wire;
  }

  /**
   * `PUT /api/v1/tenants/{tenant_id}/webauthn/attestation-policy`
   *
   * **This is a replacement, not a patch** (§27.4 rule 5). Every field of the
   * body is required, and what you do not carry over from a prior read is not
   * preserved — it is overwritten. Read first, change the field you mean, send
   * the whole thing back.
   *
   * Not retried on failure (§27.4 rule 8): every write on this surface is
   * issued exactly once, including the ones that look idempotent.
   */
  async set(body: models.WebauthnAttestationPolicy): Promise<models.WebauthnAttestationPolicy> {
    const tenantId = resolveTenant(this.#client, this.#scope, "webauthn_policy.set");
    const wire = await sendManagement<models.WebauthnAttestationPolicy>(this.#client, {
      operation: 'webauthn_policy.set',
      method: 'PUT',
      pathTemplate: '/api/v1/tenants/{tenant_id}/webauthn/attestation-policy',
      path: `/api/v1/tenants/${tenantId}/webauthn/attestation-policy`,
      body: body,
    });
    return wire;
  }

  /** `GET /api/v1/tenants/{tenant_id}/webauthn/compliance-report` */
  async complianceReport(): Promise<models.ComplianceReportEntry[]> {
    const tenantId = resolveTenant(this.#client, this.#scope, "webauthn_policy.compliance_report");
    const wire = await sendManagement<models.ComplianceReportEntry[]>(this.#client, {
      operation: 'webauthn_policy.compliance_report',
      method: 'GET',
      pathTemplate: '/api/v1/tenants/{tenant_id}/webauthn/compliance-report',
      path: `/api/v1/tenants/${tenantId}/webauthn/compliance-report`,
    });
    return wire;
  }

}
