// @generated by scripts/gen-management.mjs from management-registry.json and
// openapi.json. DO NOT EDIT — your changes will be overwritten. Regenerate with
// `node scripts/gen-management.mjs`; CI verifies the committed output is current.

/**
 * The `webhooks` management namespace (CONTRACT §27.1).
 *
 * Outbound event notifications. Delivery signatures are verified with the
 * §13 helper, which this namespace configures.
 */

import type { AxiamClient } from '../../rest/client.js';
import * as models from '../models.js';
import type { Page, PageRequest } from '../page.js';
import { collectPages, pageQuery } from '../page.js';
import { sendManagement } from '../request.js';
import type { Scope } from '../scope.js';

/**
 * The `webhooks` namespace handle.
 *
 * Outbound event notifications. Delivery signatures are verified with the
 * §13 helper, which this namespace configures.
 *
 * Acquiring one performs no I/O and allocates nothing meaningful (§27.2 rule
 * 1); it holds the client and cannot be constructed without one.
 */
export class WebhooksApi {
  readonly #client: AxiamClient;
  readonly #scope: Scope;

  /** @internal — reached through `client.<namespace>`, never constructed directly. */
  constructor(client: AxiamClient, scope: Scope = {}) {
    this.#client = client;
    this.#scope = scope;
  }

  /** `GET /api/v1/webhooks` */
  async list(page: PageRequest = {}): Promise<Page<models.WebhookResponse>> {
    const wire = await sendManagement<Page<models.WebhookResponse>>(this.#client, {
      operation: 'webhooks.list',
      method: 'GET',
      pathTemplate: '/api/v1/webhooks',
      path: '/api/v1/webhooks',
      query: { ...pageQuery(page) },
    });
    return wire;
  }

  /**
   * Walk `webhooks.list` to exhaustion, concatenating every page.
   *
   * The auto-paging form §27.4 rule 4 requires. It stops on an empty page even
   * if `total` disagrees, so a misreporting server costs one wasted request
   * rather than an unbounded loop.
   */
  listAll(start: PageRequest = {}): Promise<models.WebhookResponse[]> {
    return collectPages(start, (p) => this.list(p));
  }

  /**
   * `POST /api/v1/webhooks`
   *
   * Not retried on failure (§27.4 rule 8): every write on this surface is
   * issued exactly once, including the ones that look idempotent.
   */
  async create(body: models.CreateWebhookRequest): Promise<models.WebhookResponse> {
    const wire = await sendManagement<models.WebhookResponse>(this.#client, {
      operation: 'webhooks.create',
      method: 'POST',
      pathTemplate: '/api/v1/webhooks',
      path: '/api/v1/webhooks',
      body: models.createWebhookRequestToWire(body),
    });
    return wire;
  }

  /** `GET /api/v1/webhooks/{id}` */
  async get(id: string): Promise<models.WebhookResponse> {
    const wire = await sendManagement<models.WebhookResponse>(this.#client, {
      operation: 'webhooks.get',
      method: 'GET',
      pathTemplate: '/api/v1/webhooks/{id}',
      path: `/api/v1/webhooks/${encodeURIComponent(id)}`,
    });
    return wire;
  }

  /**
   * `PUT /api/v1/webhooks/{id}`
   *
   * Not retried on failure (§27.4 rule 8): every write on this surface is
   * issued exactly once, including the ones that look idempotent.
   */
  async update(id: string, body: models.UpdateWebhookRequest): Promise<models.WebhookResponse> {
    const wire = await sendManagement<models.WebhookResponse>(this.#client, {
      operation: 'webhooks.update',
      method: 'PUT',
      pathTemplate: '/api/v1/webhooks/{id}',
      path: `/api/v1/webhooks/${encodeURIComponent(id)}`,
      body: models.updateWebhookRequestToWire(body),
    });
    return wire;
  }

  /**
   * `DELETE /api/v1/webhooks/{id}`
   *
   * Not retried on failure (§27.4 rule 8): every write on this surface is
   * issued exactly once, including the ones that look idempotent.
   */
  async delete(id: string): Promise<void> {
    await sendManagement<void>(this.#client, {
      operation: 'webhooks.delete',
      method: 'DELETE',
      pathTemplate: '/api/v1/webhooks/{id}',
      path: `/api/v1/webhooks/${encodeURIComponent(id)}`,
    });
  }

}
