// The reactor wire protocol — the signed event and the signed reply
// (CONTRACT.md §22.1–§22.4).
//
// Mirror, never import. These shapes reproduce the field order and serde
// behaviour of the server's `ReactorEventMessage` / `ReactorReply`
// (`crates/axiam-amqp/src/reactor/protocol.rs`) byte-for-byte using only Node
// built-ins. `testdata/reactor_v2_reference_vectors.json` — generated by the
// server's own sign path — is what pins them.
//
// ## The one canonicalization difference that will cost you a day
//
// §8's own two message types (`AuthzRequest`, `AuditEventMessage`) sign a body
// with `hmac_signature` OMITTED. A reactor event and a reactor reply sign it
// SERIALIZED AS `null`:
//
//   {"correlation_id":"…","tenant_id":"…", … ,"hmac_signature":null}
//                                                               ^^^^ present
//
// Everything else about §8 v2 is unchanged: the HKDF-derived per-tenant subkey,
// HMAC-SHA256 hex-encoded and compared in constant time, `key_version = 2` as a
// hard floor, a ±300 s freshness window checked in BOTH directions, and a fresh
// UUIDv4 `nonce` inside the signed bytes.
//
// ## The second thing that will cost you a day, and is TypeScript-specific
//
// `Date.prototype.toISOString()` ALWAYS emits three fractional digits
// (`…T12:00:00.000Z`). The server's `issued_at` is a `chrono::DateTime<Utc>`,
// which re-serializes with `SecondsFormat::AutoSi` — no fractional part at all
// when the nanoseconds are zero. So a reply timestamped with a bare
// `toISOString()` on a whole second is re-serialized by the server as
// `…T12:00:00Z`, over different bytes than the reactor signed, and the
// signature fails with no other symptom. {@link toChronoRfc3339} is the fix and
// it is not optional.

import { createHash, randomUUID } from 'node:crypto';
import { signPayload, verifyPayload } from '../hmac.js';
import { eventSpec, type ReactorEventSpec } from './registry.js';

/** Topic exchange every reactor event is published to (§22.1). */
export const REACTOR_EXCHANGE = 'axiam.reactor.events';

/**
 * Envelope key version this SDK emits, and the floor it accepts (§22.2). A body
 * carrying less than this is refused before anything else about it is
 * considered.
 */
export const REACTOR_KEY_VERSION = 2;

/**
 * Freshness window for `issued_at`, in milliseconds, in **both** directions
 * (§22.2). A future timestamp is not "extra fresh" — it is the shape of a
 * captured message held for later.
 */
export const REACTOR_FRESHNESS_SKEW_MS = 300_000;

/**
 * The routing key an event is published with: `<tenant_id>.<event>` (§22.1).
 *
 * Stated so an SDK can assert against it; a reactor runtime never *binds* with
 * it. See {@link reactorQueueName}.
 */
export function reactorRoutingKey(tenantId: string, event: string): string {
  return `${tenantId}.${event}`;
}

/**
 * The durable per-reactor queue name:
 * `axiam.reactor.q.<tenant_id>.<reactor_id>` (§22.1).
 *
 * **The server declares this queue; a reactor only consumes from it.** This SDK
 * derives the name for the reactor it is configured as and for no other: a
 * reactor that can declare and bind is a reactor that can bind itself to
 * `*.token.pre_issue` and read another tenant's issuance events, and refusing to
 * hold that capability at all is cheaper than proving each actor does not misuse
 * it.
 */
export function reactorQueueName(tenantId: string, reactorId: string): string {
  return `axiam.reactor.q.${tenantId}.${reactorId}`;
}

/**
 * Render `date` the way the server's `chrono::DateTime<Utc>` serializes it:
 * RFC 3339, UTC, with **no** fractional part when the milliseconds are zero and
 * exactly three digits otherwise.
 *
 * This is not cosmetic. The server verifies a reply by re-serializing the body
 * it parsed, so a timestamp this SDK wrote as `…T12:00:00.000Z` comes back out
 * as `…T12:00:00Z` — different bytes, different MAC, and a `bad_signature`
 * rejection with nothing in the payload to explain it.
 */
export function toChronoRfc3339(date: Date): string {
  const iso = date.toISOString();
  return iso.endsWith('.000Z') ? `${iso.slice(0, -5)}Z` : iso;
}

/** `true` when `issuedAt` lies within `±skewMs` of `now` — both directions. */
export function isFresh(issuedAtMs: number, nowMs: number, skewMs: number): boolean {
  return Math.abs(nowMs - issuedAtMs) <= skewMs;
}

// ---------------------------------------------------------------------------
// Event (server → reactor)
// ---------------------------------------------------------------------------

/**
 * One hook firing, delivered to a reactor (CONTRACT.md §22.3).
 *
 * Field order is load-bearing: it is the order the server serializes, and
 * therefore the order the canonical signed bytes carry.
 */
export interface ReactorEvent {
  /**
   * The tenant this firing belongs to. The signing subkey is derived from it,
   * so an event cannot be replayed into another tenant.
   */
  readonly tenant_id: string;
  /** A registry name (§22.5) — also the second half of the routing key. */
  readonly event: string;
  /**
   * The single-use handle for this dispatch. The runtime echoes it into the
   * reply **body**; copying it only into the AMQP property produces a reply the
   * server discards.
   */
  readonly correlation_id: string;
  /**
   * Event-specific body. Never carries a credential, a token, or a signing key
   * — a reactor is told *what is being decided*, not handed the means to act on
   * it elsewhere.
   *
   * On a chained event this object also carries `_reactor_patch`, the patch an
   * earlier reactor in the chain already returned (§22.3). Treat it as
   * **read-only context**: echoing it back inside your own `patch` is not how a
   * field is preserved — the server merges (§22.6).
   */
  readonly payload: Record<string, unknown>;
  /**
   * How long the server will actually wait for *this* dispatch, in
   * milliseconds. Inside the signed body, so it cannot be widened in transit.
   *
   * §22.3 sends it so an actor can shed load rather than answer into a closed
   * window: a late reply is discarded, and the CPU spent producing it was spent
   * for nothing.
   */
  readonly timeout_ms: number;
  /** §8 v2 envelope key version. Always `2` or higher. */
  readonly key_version: number;
  /** Fresh UUIDv4 per message, inside the signed bytes. */
  readonly nonce: string;
  /** Producer-side send time, RFC 3339, for the freshness gate. */
  readonly issued_at: string;
  /** HMAC-SHA256 over this body with the field serialized as `null`. */
  readonly hmac_signature: string | null;
}

/**
 * Why a delivered event was not usable, in the order §22.3 requires the checks
 * to run.
 */
export type EventRejection =
  /** The body is not a JSON object, or is missing a mandatory field. */
  | 'malformed'
  /**
   * `key_version` below the §8 v2 floor — refused **before** the signature is
   * even computed.
   */
  | 'key_version_too_old'
  /** Missing or wrong MAC. */
  | 'bad_signature'
  /** `issued_at` outside ±skew, in either direction. */
  | 'stale'
  /** This `nonce` was already seen inside the freshness window. */
  | 'replayed_nonce';

/**
 * Why the server would not use a reply (CONTRACT.md §22.4).
 *
 * Every member resolves to the registration's `failure_policy` and every member
 * is audited: a rejected reply is **not** a softer failure than no reply at all.
 * This SDK exposes the taxonomy so a reactor author can assert against it and
 * read it in a log line, and refuses locally only what it can detect without
 * guessing (see {@link reactorServe}).
 */
export type ReplyRejection =
  | 'wrong_correlation'
  | 'tenant_mismatch'
  | 'event_mismatch'
  | 'key_version_too_old'
  | 'stale'
  | 'bad_signature'
  | 'require_mfa_not_supported'
  | 'not_mutable'
  | 'forbidden_patch_field'
  | 'malformed_mutation';

/**
 * The canonical bytes of a delivered event: the body exactly as it arrived,
 * with `hmac_signature` **set to `null` in place** (§22.2).
 *
 * Setting the value rather than deleting the key is the whole difference from
 * §8's own two message types, and re-serializing the *parsed* body (rather than
 * a rebuilt struct) is what makes the payload's own key order and nesting
 * reproduce byte-for-byte — `JSON.parse` preserves insertion order for string
 * keys, and assigning to an existing key keeps its position.
 *
 * Returns `undefined` when the body carries no `hmac_signature` at all: an
 * unsigned event is not a weak event, it is not an event, and inserting the key
 * ourselves would put it in the wrong position anyway.
 */
export function canonicalEventBytes(body: Record<string, unknown>): Buffer | undefined {
  if (!('hmac_signature' in body)) return undefined;
  const canonical: Record<string, unknown> = { ...body, hmac_signature: null };
  return Buffer.from(JSON.stringify(canonical), 'utf8');
}

/** A successfully verified event, or the reason it was refused. */
export type VerifyEventResult =
  | { ok: true; event: ReactorEvent }
  | { ok: false; rejection: EventRejection };

/**
 * Verify a delivered event and decode it, in the order §22.3 fixes:
 * **`key_version`, then the MAC, then freshness**. The fourth check, the nonce
 * seen-set, is the runtime's rather than this function's, because it is state
 * rather than a property of the message.
 *
 * A runtime that hands an unverified payload to user code has already lost: the
 * handler will act on it, and "we checked afterwards" is not a check.
 */
export function verifyEvent(
  body: Record<string, unknown>,
  signingKey: Buffer,
  nowMs: number = Date.now(),
  skewMs: number = REACTOR_FRESHNESS_SKEW_MS,
): VerifyEventResult {
  // 1. key_version, before anything else about the body is considered.
  const keyVersion = body.key_version;
  if (typeof keyVersion !== 'number' || !Number.isInteger(keyVersion)) {
    return { ok: false, rejection: 'malformed' };
  }
  if (keyVersion < REACTOR_KEY_VERSION) {
    return { ok: false, rejection: 'key_version_too_old' };
  }

  // 2. the MAC, over the body with hmac_signature serialized as null.
  const signature = body.hmac_signature;
  if (typeof signature !== 'string') {
    return { ok: false, rejection: 'bad_signature' };
  }
  const canonical = canonicalEventBytes(body);
  if (!canonical || !verifyPayload(signingKey, canonical, signature)) {
    return { ok: false, rejection: 'bad_signature' };
  }

  // Only now is the body's shape trusted enough to read.
  if (
    typeof body.tenant_id !== 'string' ||
    typeof body.event !== 'string' ||
    typeof body.correlation_id !== 'string' ||
    typeof body.nonce !== 'string' ||
    typeof body.issued_at !== 'string' ||
    typeof body.timeout_ms !== 'number' ||
    typeof body.payload !== 'object' ||
    body.payload === null ||
    Array.isArray(body.payload)
  ) {
    return { ok: false, rejection: 'malformed' };
  }

  // 3. freshness, in both directions.
  const issuedAtMs = Date.parse(body.issued_at);
  if (Number.isNaN(issuedAtMs) || !isFresh(issuedAtMs, nowMs, skewMs)) {
    return { ok: false, rejection: 'stale' };
  }

  return {
    ok: true,
    event: {
      tenant_id: body.tenant_id,
      event: body.event,
      correlation_id: body.correlation_id,
      payload: body.payload as Record<string, unknown>,
      timeout_ms: body.timeout_ms,
      key_version: keyVersion,
      nonce: body.nonce,
      issued_at: body.issued_at,
      hmac_signature: signature,
    },
  };
}

/**
 * The accumulated patch an earlier reactor in the chain returned, if this is a
 * chained dispatch (§22.3's `_reactor_patch`).
 *
 * Read-only context: it tells you what the state will be if the chain commits,
 * so you can decide against that rather than against the original. It is **not**
 * something to copy into your own patch.
 */
export function chainedPatch(event: ReactorEvent): unknown {
  return event.payload._reactor_patch;
}

/** The registry spec for an event's name, if this SDK knows it. */
export function specForEvent(event: ReactorEvent): ReactorEventSpec | undefined {
  return eventSpec(event.event);
}

// ---------------------------------------------------------------------------
// Reply (reactor → server)
// ---------------------------------------------------------------------------

/** The closed set of decision values (§22.4). Lowercase on the wire. */
export type ReplyDecision = 'allow' | 'deny' | 'mutate';

/**
 * A reactor's answer to one event (CONTRACT.md §22.4), as it appears on the
 * wire.
 *
 * The three conditionally-present fields are load-bearing. A reply that
 * serializes `"require_mfa": false` rather than omitting it produces different
 * canonical bytes and therefore a different MAC — the omission rule, not just
 * the values, is part of the wire format. {@link buildReactorReply} is what
 * enforces it; do not assemble one of these by hand.
 */
export interface ReactorReply {
  readonly correlation_id: string;
  readonly tenant_id: string;
  readonly event: string;
  readonly decision: ReplyDecision;
  /** Audited on a `deny`. **Omitted when absent.** */
  readonly reason?: string;
  /** Flat `string → string` map, sorted by key. **Omitted when absent.** */
  readonly patch?: Record<string, string>;
  /** `login.post_auth` only. **Omitted when `false`.** */
  readonly require_mfa?: true;
  readonly key_version: number;
  /**
   * A **fresh** UUIDv4 per reply. It is inside the signed bytes, so a unique one
   * is what keeps two replies from being byte-identical — which is what makes a
   * captured reply distinguishable from a fresh one. Emitting a constant nonce
   * removes the only uniqueness a reply body carries beyond its timestamp.
   */
  readonly nonce: string;
  readonly issued_at: string;
  readonly hmac_signature: string | null;
}

/** What {@link buildReactorReply} needs beyond the event it answers. */
export interface ReplyInput {
  readonly decision: ReplyDecision;
  readonly reason?: string;
  readonly patch?: Record<string, string>;
  readonly requireMfa?: boolean;
  /** Overridable for tests; defaults to a fresh UUIDv4 per reply. */
  readonly nonce?: string;
  /** Overridable for tests; defaults to now. */
  readonly issuedAt?: Date;
}

/**
 * Build an **unsigned** reply answering `event`, with `correlation_id`,
 * `tenant_id` and `event` copied from the event body (§22.1, §22.4), in the
 * server's field order and with every omission rule applied.
 *
 * The patch's keys are emitted in sorted order, because the server's `patch` is
 * a `BTreeMap` and the signed bytes are the sorted rendering.
 */
export function buildReactorReply(
  event: Pick<ReactorEvent, 'correlation_id' | 'tenant_id' | 'event'>,
  input: ReplyInput,
): ReactorReply {
  // Assembled by assignment, in declaration order, because JSON.stringify
  // serializes string keys in insertion order and that order IS the wire format.
  const reply: Record<string, unknown> = {
    correlation_id: event.correlation_id,
    tenant_id: event.tenant_id,
    event: event.event,
    decision: input.decision,
  };
  // `reason` and `patch` are omitted when absent — not emitted as null.
  if (input.reason !== undefined) reply.reason = input.reason;
  if (input.patch !== undefined) reply.patch = sortedPatch(input.patch);
  // `require_mfa` is omitted when false. A reply carrying `false` explicitly
  // signs different bytes and its MAC will not verify.
  if (input.requireMfa === true) reply.require_mfa = true;
  reply.key_version = REACTOR_KEY_VERSION;
  reply.nonce = input.nonce ?? randomUUID();
  reply.issued_at = toChronoRfc3339(input.issuedAt ?? new Date());
  reply.hmac_signature = null;
  return reply as unknown as ReactorReply;
}

/** A patch object whose keys iterate in sorted order (the server's `BTreeMap`). */
function sortedPatch(patch: Record<string, string>): Record<string, string> {
  const sorted: Record<string, string> = {};
  for (const key of Object.keys(patch).sort()) {
    sorted[key] = patch[key] as string;
  }
  return sorted;
}

/**
 * The exact bytes a reply is signed over: itself, in declaration order, with
 * `hmac_signature` set to `null`.
 *
 * Clearing the field here rather than asking the caller to remember is what
 * makes it impossible to sign over a body that already contains a signature.
 */
export function canonicalReplyBytes(reply: ReactorReply): Buffer {
  const unsigned: Record<string, unknown> = { ...reply, hmac_signature: null };
  return Buffer.from(JSON.stringify(unsigned), 'utf8');
}

/**
 * Sign a reply with the tenant's derived AMQP subkey, returning a new object
 * carrying the MAC. The input is not mutated.
 */
export function signReactorReply(reply: ReactorReply, signingKey: Buffer): ReactorReply {
  const signature = signPayload(signingKey, canonicalReplyBytes(reply));
  return { ...reply, hmac_signature: signature };
}

/**
 * Verify a reply's own signature — the check the server performs, exposed so an
 * SDK test (or a proxy) can run it locally.
 */
export function reactorReplySignatureValid(reply: ReactorReply, signingKey: Buffer): boolean {
  if (typeof reply.hmac_signature !== 'string') return false;
  return verifyPayload(signingKey, canonicalReplyBytes(reply), reply.hmac_signature);
}

/**
 * HKDF-SHA256 is **not** performed by this SDK: §8.1 assumes the per-tenant
 * subkey is provisioned out of band, and {@link reactorServe} takes that
 * already-derived key. This helper exists only so a caller can fingerprint the
 * key they were handed for an operational log without ever printing it.
 *
 * The digest is truncated to eight hex characters — enough to tell two keys
 * apart in a log line, far too little to attack.
 */
export function signingKeyFingerprint(signingKey: Buffer): string {
  return createHash('sha256').update(signingKey).digest('hex').slice(0, 8);
}
